In [3]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [5]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(320928, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,06/14/2016 01:20:00 AM,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,12/13/2016 05:00:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,07/19/2020 03:09:00 AM,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,11/17/2014 08:08:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,04/20/2015 10:22:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [7]:
dfCrime['Incident Datetime'] = pd.to_datetime(dfCrime['Incident Datetime'])
dfCrime.head()

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,2016-06-14 01:20:00,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,2016-12-13 05:00:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,2020-07-19 03:09:00,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,2014-11-17 08:08:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,2015-04-20 10:22:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [9]:
dfCrime = dfCrime.loc[(dfCrime['Incident Datetime'] >= '2019-01-01') & (dfCrime['Incident Datetime'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(13672, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
7601,19-0140161,2019-01-13 22:30:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,22,Sunday,MAIN ST & CHURCH ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
7635,19-0230400,2019-01-23 00:00:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,0,Wednesday,200 Block LESLIE ST,Buffalo,...,1,1007,36,1,1010,District E,003600,36029003600,360290001101,360290025021007
10699,19-0420162,2019-02-11 07:19:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,7,Monday,MERCER AV & S PARK AV,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
13801,19-2580750,2019-09-15 17:10:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,17,Sunday,CHELTONHAM PW & DELAWARE AV,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
130455,19-2160973,2019-08-04 14:00:00,NaN,BURGLARY,Buffalo Police are investigating this report o...,Breaking & Entering,14,Sunday,1 Block KRAKOW ST,Buffalo,...,3,3021,167,3,3028,District A,016700,36029016700,360290001103,360290163003021

In [11]:
list(dfCrime.columns)

['Case Number',
 'Incident Datetime',
 'Incident ID',
 'Incident Type Primary',
 'Incident Description',
 'Parent Incident Type',
 'Hour of Day',
 'Day of Week',
 'Address',
 'City',
 'State',
 'Location',
 'Latitude',
 'Longitude',
 'Created At',
 'updated_at',
 'zip_code',
 'neighborhood',
 'Council District',
 'Council District 2011',
 'Census Tract',
 'Census Block Group',
 'Census Block',
 '2010 Census Tract ',
 '2010 Census Block Group',
 '2010 Census Block',
 'Police District',
 'TRACTCE20',
 'GEOID20_tract',
 'GEOID20_blockgroup',
 'GEOID20_block']

In [13]:
sorted(list(dfCrime['Incident Type Primary'].unique()))

['AGGR ASSAULT',
 'ASSAULT',
 'BURGLARY',
 'CRIM NEGLIGENT HOMICIDE',
 'LARCENY/THEFT',
 'MURDER',
 'RAPE',
 'ROBBERY',
 'SEXUAL ABUSE',
 'THEFT OF SERVICES',
 'UUV']

In [15]:
violentCrimes = ['AGGR ASSAULT', 'RAPE', 'MURDER', 'SEXUAL ABUSE', 'ROBBERY']
dfCrime = dfCrime[dfCrime['Incident Type Primary'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(1153, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
7601,19-0140161,2019-01-13 22:30:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,22,Sunday,MAIN ST & CHURCH ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
130644,19-0450441,2019-02-14 15:10:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,15,Thursday,100 Block ROOSEVELT AV,Buffalo,...,3,3006,44.01,3,3006,District E,004401,36029004401,360290001103,360290163003006
130854,19-0060644,2019-01-06 18:20:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,18,Sunday,900 Block JEFFERSON AV,Buffalo,...,1,1008,31,1,1006,District C,003100,36029003100,360290001101,360290002001008
131141,19-0990423,2019-04-07 05:45:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,5,Sunday,100 Block HAMPSHIRE ST,Buffalo,...,3,3010,69.01,3,3010,District B,006901,36029006901,360290001103,360290061003010
131530,19-0040759,2019-01-04 19:41:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,19,Friday,300 Block BRISTOL ST,Buffalo,...,2,2010,17,2,2013,District C,001700,36029001700,360290001102,360290033022010

In [17]:
dfCrime = dfCrime[['Incident Type Primary', 'Longitude', 'Latitude']]
dfCrime = dfCrime[dfCrime['Longitude'] != 'UNKNOWN']
dfCrime.head()

       Incident Type Primary Longitude Latitude
130644               ROBBERY    -78.81   42.934
130854               ROBBERY   -78.854     42.9
131141               ROBBERY   -78.895   42.912
131530               ROBBERY   -78.843   42.881
131572               ROBBERY   -78.854   42.923

In [19]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Type Primary', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(1143, 2)

       Incident Type Primary                geometry
130644               ROBBERY   POINT (-78.81 42.934)
130854               ROBBERY    POINT (-78.854 42.9)
131141               ROBBERY  POINT (-78.895 42.912)
131530               ROBBERY  POINT (-78.843 42.881)
131572               ROBBERY  POINT (-78.854 42.923)

In [21]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_36_bg_500k/cb_2018_36_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(15406, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,36,103,110401,1,1500000US361031104011,361031104011,1,BG,534139,0,"POLYGON ((-73.399 40.904, -73.394 40.904, -73...."
1,36,119,005600,1,1500000US361190056001,361190056001,1,BG,312476,180612,"POLYGON ((-73.773 40.885, -73.772 40.887, -73...."
2,36,067,011402,3,1500000US360670114023,360670114023,3,BG,45275086,887109,"POLYGON ((-76.479 43.228, -76.451 43.229, -76...."
3,36,069,051400,2,1500000US360690514002,360690514002,2,BG,46193661,0,"POLYGON ((-77.131 42.861, -77.121 42.861, -77...."
4,36,061,018600,2,1500000US360610186002,360610186002,2,BG,48762,0,"POLYGON ((-73.952 40.799, -73.95 40.799, -73.9..."

In [23]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident Type Primary                geometry
130644               ROBBERY   POINT (-78.81 42.934)
130854               ROBBERY    POINT (-78.854 42.9)
131141               ROBBERY  POINT (-78.895 42.912)
131530               ROBBERY  POINT (-78.843 42.881)
131572               ROBBERY  POINT (-78.854 42.923)

In [25]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(1143, 13)

,Incident Type Primary,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
130644,ROBBERY,POINT (-78.81 42.934),5986,36,029,004401,3,1500000US360290044013,360290044013,3,BG,351227,0
130854,ROBBERY,POINT (-78.854 42.9),10647,36,029,003100,2,1500000US360290031002,360290031002,2,BG,243795,0
131141,ROBBERY,POINT (-78.895 42.912),4412,36,029,006901,3,1500000US360290069013,360290069013,3,BG,203371,0
131530,ROBBERY,POINT (-78.843 42.881),11991,36,029,001700,2,1500000US360290017002,360290017002,2,BG,277478,0
131572,ROBBERY,POINT (-78.854 42.923),6672,36,029,005202,1,1500000US360290052021,360290052021,1,BG,256710,0

In [27]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    51
1500000US360290034002    24
1500000US360290024001    17
1500000US360290038003    16
1500000US360290017001    15
                         ..
1500000US360290053002     1
1500000US360290088003     1
1500000US360290067013     1
1500000US360290033021     1
1500000US360290054002     1
Name: count, Length: 256, dtype: int64

In [29]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_Violent_Crime_BG.csv')