In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [3]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crimes_-_2001_to_Present.csv')
print(dfCrime.shape)
dfCrime.head()

(8285876, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
4,13204489,JG416325,09/06/2023 11:00:00 AM,0000X E 8TH ST,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,4.0,32.0,06,1176857.0,1896680.0,2023,11/04/2023 03:40:18 PM,41.871835,-87.626151,"(41.871834768, -87.62615082)"

In [4]:
dfCrime.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [5]:
dfCrime = dfCrime[dfCrime['Year'] == 2019]
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(259172, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
5,11695116,JC272771,05/21/2019 08:20:00 AM,018XX S CALIFORNIA AVE,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE,False,False,...,25.0,29.0,05,1157982.0,1890961.0,2019,01/19/2024 03:40:50 PM,41.856547,-87.695605,"(41.856547057, -87.695604526)"
18,11662417,JC232642,04/21/2019 12:30:00 PM,009XX E 80TH ST,031A,ROBBERY,ARMED - HANDGUN,RESIDENCE,False,False,...,8.0,44.0,03,1184044.0,1852159.0,2019,09/14/2023 03:41:59 PM,41.749500,-87.601157,"(41.749500329, -87.6011574)"
32,12990873,JG161829,08/17/2019 01:14:00 PM,008XX N KARLOV AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,True,True,...,37.0,23.0,17,1148899.0,1905351.0,2019,09/14/2023 03:41:59 PM,41.896215,-87.728572,"(41.89621515, -87.728572048)"
847,11757563,JC348652,07/13/2019 11:30:00 PM,084XX S MACKINAW AVE,0320,ROBBERY,STRONG ARM - NO WEAPON,ALLEY,False,False,...,10.0,46.0,03,1199935.0,1849732.0,2019,04/18/2024 03:40:20 PM,41.742455,-87.543009,"(41.742454647, -87.543009205)"
879,11653698,JC222674,04/13/2019 01:30:00 AM,010XX W DIVISION ST,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,...,27.0,8.0,07,1169399.0,1908184.0,2019,12/22/2024 03:41:04 PM,41.903568,-87.653197,"(41.903567876, -87.653197209)"

In [9]:
violentCrimeCodes = ['03', '01A', '02', '04A', '01B']
dfCrime = dfCrime[dfCrime['FBI Code'].isin(violentCrimeCodes)]
print(dfCrime.shape)
dfCrime.head()

(16129, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
18,11662417,JC232642,04/21/2019 12:30:00 PM,009XX E 80TH ST,031A,ROBBERY,ARMED - HANDGUN,RESIDENCE,False,False,...,8.0,44.0,03,1184044.0,1852159.0,2019,09/14/2023 03:41:59 PM,41.749500,-87.601157,"(41.749500329, -87.6011574)"
847,11757563,JC348652,07/13/2019 11:30:00 PM,084XX S MACKINAW AVE,0320,ROBBERY,STRONG ARM - NO WEAPON,ALLEY,False,False,...,10.0,46.0,03,1199935.0,1849732.0,2019,04/18/2024 03:40:20 PM,41.742455,-87.543009,"(41.742454647, -87.543009205)"
881,11874498,JC489070,10/28/2019 01:15:00 AM,052XX S ARCHER AVE,0313,ROBBERY,ARMED - OTHER DANGEROUS WEAPON,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,23.0,57.0,03,1146707.0,1870103.0,2019,12/22/2024 03:41:04 PM,41.799532,-87.737521,"(41.799532089, -87.737521099)"
931,11885224,JC502442,11/05/2019 08:00:00 PM,075XX S RHODES AVE,031A,ROBBERY,ARMED - HANDGUN,STREET,False,True,...,6.0,69.0,03,1181207.0,1855239.0,2019,09/15/2023 03:41:25 PM,41.758018,-87.611459,"(41.75801796, -87.611458525)"
5550,24886,JC564006,12/29/2019 11:25:00 AM,030XX W 39TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,12.0,58.0,01A,1156684.0,1878275.0,2019,09/19/2023 03:41:47 PM,41.821762,-87.700712,"(41.821761535, -87.700711857)"

In [11]:
dfCrime = dfCrime[['FBI Code', 'Latitude', 'Longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['FBI Code', 'geometry']]
dfCrime.head()

     FBI Code                                 geometry
18         03  POINT (-87.60115740000001 41.749500329)
847        03       POINT (-87.543009205 41.742454647)
881        03  POINT (-87.73752109900001 41.799532089)
931        03        POINT (-87.611458525 41.75801796)
5550      01A       POINT (-87.700711857 41.821761535)

In [13]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_17_bg_500k/cb_2018_17_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(9689, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,17,031,081202,1,1500000US170310812021,170310812021,1,BG,119267,530065,"POLYGON ((-87.624 41.902, -87.623 41.902, -87...."
1,17,031,300900,3,1500000US170313009003,170313009003,3,BG,58576,0,"POLYGON ((-87.703 41.852, -87.702 41.852, -87...."
2,17,031,806700,3,1500000US170318067003,170318067003,3,BG,402672,0,"POLYGON ((-87.732 42.055, -87.727 42.055, -87...."
3,17,031,711400,3,1500000US170317114003,170317114003,3,BG,158934,0,"POLYGON ((-87.657 41.736, -87.653 41.736, -87...."
4,17,031,040700,3,1500000US170310407003,170310407003,3,BG,99758,0,"POLYGON ((-87.698 41.967, -87.696 41.967, -87...."

In [15]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

     FBI Code                geometry
18         03   POINT (-87.601 41.75)
847        03  POINT (-87.543 41.742)
881        03    POINT (-87.738 41.8)
931        03  POINT (-87.611 41.758)
5550      01A  POINT (-87.701 41.822)

In [17]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(16129, 13)

,FBI Code,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
18,03,POINT (-87.601 41.75),51.0,17,031,440101,1,1500000US170314401011,170314401011,1,BG,145946.0,0.0
847,03,POINT (-87.543 41.742),951.0,17,031,460200,1,1500000US170314602001,170314602001,1,BG,183147.0,0.0
881,03,POINT (-87.738 41.8),4849.0,17,031,570500,2,1500000US170315705002,170315705002,2,BG,243631.0,0.0
931,03,POINT (-87.611 41.758),299.0,17,031,691400,4,1500000US170316914004,170316914004,4,BG,122194.0,0.0
5550,01A,POINT (-87.701 41.822),8002.0,17,031,580501,1,1500000US170315805011,170315805011,1,BG,123172.0,0.0

In [19]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US170318391001    120
1500000US170318424002     89
1500000US170313204001     63
1500000US170310817002     58
1500000US170312607002     56
                        ...
1500000US170310302003      1
1500000US170311005005      1
1500000US170310207024      1
1500000US170312426004      1
1500000US170310901001      1
Name: count, Length: 2011, dtype: int64

In [21]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Chicago_Violent_Crime_BG.csv')