In [45]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [47]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Police_Department_Incident_Reports__2018_to_Present_20250412.csv')
print(dfCrime.shape)
dfCrime.head()

(947910, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023,Wednesday,2023/03/11 04:55:00 PM,125378606372,1253786,236046123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/11 03:00:00 PM,2023/03/11,15:00,2023,Saturday,2023/03/13 08:29:00 AM,125420606244,1254206,236045937,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(896213, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
6,2022/06/27 12:00:00 PM,2022/06/27,12:00,2022,Monday,2023/03/15 05:20:00 PM,125439371000,1254393,230184129,230742480.0,...,-122.408227,POINT (-122.40822672700406 37.78735926098589),19.0,NaN,1.0,NaN,NaN,NaN,3.0,6.0
8,2023/03/16 05:30:00 PM,2023/03/16,17:30,2023,Thursday,2023/03/16 06:02:00 PM,125482604134,1254826,230187101,230752550.0,...,-122.401324,POINT (-122.40132418490647 37.76228996810526),54.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
26,2023/03/21 03:50:00 PM,2023/03/21,15:50,2023,Tuesday,2023/03/21 04:01:00 PM,125656351040,1256563,230199764,230802198.0,...,-122.418271,POINT (-122.41827098126804 37.787037946181535),50.0,NaN,NaN,NaN,NaN,NaN,10.0,6.0
144,2021/07/03 12:00:00 PM,2021/07/03,12:00,2021,Saturday,2021/07/03 12:37:00 PM,104624471000,1046244,210417332,211841413.0,...,-122.446610,POINT (-122.44660957715965 37.801787342426636),17.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
145,2021/07/22 07:16:00 PM,2021/07/22,19:16,2021,Thursday,2021/07/23 01:35:00 PM,105341571000,1053415,216098495,NaN,...,-122.394829,POINT (-122.39482876133759 37.76524759917852),54.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0

In [49]:
dfCrime['Incident Date'] = pd.to_datetime(dfCrime['Incident Date'])
dfCrime = dfCrime[(dfCrime['Incident Date'] >= '2021-01-01') & (dfCrime['Incident Date'] < '2022-01-01')]
print(dfCrime.shape)
dfCrime.head()

(121731, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
144,2021/07/03 12:00:00 PM,2021-07-03,12:00,2021,Saturday,2021/07/03 12:37:00 PM,104624471000,1046244,210417332,211841413.0,...,-122.446610,POINT (-122.44660957715965 37.801787342426636),17.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
145,2021/07/22 07:16:00 PM,2021-07-22,19:16,2021,Thursday,2021/07/23 01:35:00 PM,105341571000,1053415,216098495,NaN,...,-122.394829,POINT (-122.39482876133759 37.76524759917852),54.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0
149,2021/07/12 06:18:00 PM,2021-07-12,18:18,2021,Monday,2021/07/12 06:26:00 PM,104984326080,1049843,210440565,211933224.0,...,-122.419171,POINT (-122.41917060471224 37.74817939136343),53.0,NaN,NaN,NaN,3.0,NaN,2.0,3.0
156,2021/08/20 10:00:00 PM,2021-08-20,22:00,2021,Friday,2021/08/26 05:47:00 PM,106420461030,1064204,210547860,212382753.0,...,-122.422955,POINT (-122.42295533494625 37.76161711991717),37.0,NaN,NaN,NaN,NaN,NaN,5.0,3.0
157,2021/06/05 01:36:00 AM,2021-06-05,01:36,2021,Saturday,2021/06/05 01:36:00 AM,103711751040,1037117,210347977,211560185.0,...,-122.432204,POINT (-122.43220428969965 37.797506948421855),15.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0

In [50]:
violentCrimes = ['Aggravated Assault', 'Rape - Attempted', 'Robbery - Residential', 'Robbery - Street', 'Robbery - Carjacking',
                'Sex Offense', 'Robbery - Commercial', 'Rape', 'Homicide', 'Robbery - Other']
dfCrime = dfCrime[dfCrime['Incident Subcategory'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(5801, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
284,2021/09/21 08:19:00 PM,2021-09-21,20:19,2021,Tuesday,2021/09/21 08:19:00 PM,107277604013,1072776,210613427,212643397.0,...,-122.407534,POINT (-122.40753423057456 37.76578329861651),53.0,NaN,NaN,NaN,3.0,NaN,9.0,3.0
430,2021/07/18 08:30:00 AM,2021-07-18,08:30,2021,Sunday,2021/07/19 06:23:00 AM,105184603071,1051846,210455401,212000390.0,...,-122.421560,POINT (-122.42155971686209 37.7870872505264),50.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0
694,2021/09/27 04:15:00 AM,2021-09-27,04:15,2021,Monday,2021/09/27 04:25:00 AM,107455304012,1074553,210626975,212700322.0,...,-122.419548,POINT (-122.41954785498713 37.784960258586636),20.0,NaN,1.0,NaN,NaN,NaN,10.0,4.0
3805,2021/07/21 12:00:00 AM,2021-07-21,00:00,2021,Wednesday,2023/03/25 06:04:00 PM,125795714052,1257957,230209404,230842474.0,...,-122.482899,POINT (-122.48289935733482 37.75395723424183),39.0,NaN,NaN,NaN,NaN,NaN,7.0,10.0
12822,2021/04/28 07:06:00 AM,2021-04-28,07:06,2021,Wednesday,2021/04/28 07:10:00 AM,102543703072,1025437,210259225,211180515.0,...,-122.386620,POINT (-122.3866195678711 37.73246765136719),86.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0

In [51]:
dfCrime = dfCrime[['Incident ID', 'Longitude', 'Latitude']]
dfCrime.head()

       Incident ID   Longitude   Latitude
284        1072776 -122.407534  37.765783
430        1051846 -122.421560  37.787087
694        1074553 -122.419548  37.784960
3805       1257957 -122.482899  37.753957
12822      1025437 -122.386620  37.732468

In [52]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident ID', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(5801, 2)

       Incident ID                                      geometry
284        1072776  POINT (-122.4075342305746 37.76578329861651)
430        1051846   POINT (-122.4215597168621 37.7870872505264)
694        1074553  POINT (-122.4195478549871 37.78496025858664)
3805       1257957  POINT (-122.4828993573348 37.75395723424183)
12822      1025437  POINT (-122.3866195678711 37.73246765136719)

In [53]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("cb_2022_us_bg_500k/cb_2022_us_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(242297, 12)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry
0,04,019,940800,2,1500000US040199408002,040199408002,2,Block Group 2,BG,2033911373,68536,"POLYGON ((-112.41 31.857, -112.38 31.859, -112..."
1,04,003,000901,4,1500000US040030009014,040030009014,4,Block Group 4,BG,486316,0,"POLYGON ((-109.55 31.334, -109.55 31.339, -109..."
2,06,073,018102,3,1500000US060730181023,060730181023,3,Block Group 3,BG,324091,3579,"POLYGON ((-117.37 33.182, -117.37 33.182, -117..."
3,06,073,007200,3,1500000US060730072003,060730072003,3,Block Group 3,BG,720442,709604,"POLYGON ((-117.26 32.725, -117.26 32.726, -117..."
4,06,073,017702,3,1500000US060730177023,060730177023,3,Block Group 3,BG,317237,0,"POLYGON ((-117.3 33.052, -117.3 33.053, -117.3..."

In [54]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident ID                geometry
284        1072776  POINT (-122.41 37.766)
430        1051846  POINT (-122.42 37.787)
694        1074553  POINT (-122.42 37.785)
3805       1257957  POINT (-122.48 37.754)
12822      1025437  POINT (-122.39 37.732)

In [55]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(5801, 14)

,Incident ID,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER
284,1072776,POINT (-122.41 37.766),36515,06,075,017700,1,1500000US060750177001,060750177001,1,Block Group 1,BG,451236,0
430,1051846,POINT (-122.42 37.787),239427,06,075,012002,2,1500000US060750120022,060750120022,2,Block Group 2,BG,31662,0
694,1074553,POINT (-122.42 37.785),144081,06,075,012202,2,1500000US060750122022,060750122022,2,Block Group 2,BG,71576,0
3805,1257957,POINT (-122.48 37.754),219016,06,075,032802,1,1500000US060750328021,060750328021,1,Block Group 1,BG,216600,97204
12822,1025437,POINT (-122.39 37.732),43286,06,075,023102,2,1500000US060750231022,060750231022,2,Block Group 2,BG,164309,0

In [56]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750176022    114
1500000US060750201021    102
1500000US060750117003     97
1500000US060759809001     85
1500000US060750615012     83
                        ...
1500000US060750476003      1
1500000US060750133002      1
1500000US060750211004      1
1500000US060750112003      1
1500000US060750216002      1
Name: count, Length: 550, dtype: int64

In [57]:
# export as a csv
crime.to_csv('SF_Violent_Crime_BG.csv')