In [25]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [27]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/PDI__Police_Data_Initiative__Crime_Incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(538814, 40)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_6043/1369205608.py:1: DtypeWarning: Columns (1,8,12,13,14,17,27,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/PDI__Police_Data_Initiative__Crime_Incidents_20250422.csv')

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
0,5D3A0BAF-7F75-4FCE-AD7D-454367AC1AC0,249014554,06/02/2024 11:19:00 PM,06/02/2024 11:15:00 PM,06/02/2024 11:19:00 PM,F--CLEARED BY ARREST - ADULT,862.0,3,4,DOMESTIC VIOLENCE,...,UNKNOWN,NaN,NaN,NaN,1.0,NaN,PART 2 MINOR,45225.0,ENGLISH WOODS,ENGLISH WOODS
1,927F0CDF-59DF-43EC-99EC-9055F749B169,249014567,06/02/2024 11:03:00 PM,06/02/2024 11:00:00 PM,06/02/2024 11:02:00 PM,F--CLEARED BY ARREST - ADULT,2709.0,1,2,VIOLATE PROTECTION ORDER/CONSENT AGREEMENT,...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,PART 2 MINOR,45202.0,OTR,OVER-THE-RHINE
2,3959F0C0-A992-4A19-B188-3469061241BF,249014562,06/02/2024 11:00:00 PM,06/02/2024 10:45:00 PM,06/02/2024 10:58:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,CORRYVILLE,CORRYVILLE
3,3959F0C0-A992-4A19-B188-3469061241BF,249014562,06/02/2024 11:00:00 PM,06/02/2024 10:45:00 PM,06/02/2024 10:58:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,CORRYVILLE,CORRYVILLE
4,14AF299C-3F8A-472C-926C-30A56733C5C0,249014548,06/02/2024 10:29:19 PM,06/02/2024 09:55:00 PM,06/02/2024 10:00:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,NaN,NaN

In [28]:
dfCrime['DATE_REPORTED'] = pd.to_datetime(dfCrime['DATE_REPORTED'])
dfCrime = dfCrime[(dfCrime['DATE_REPORTED'] >= '2019-01-01') & (dfCrime['DATE_REPORTED'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_6043/2666128640.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dfCrime['DATE_REPORTED'] = pd.to_datetime(dfCrime['DATE_REPORTED'])

(36198, 40)

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
152772,DD2F4318-6B3A-4469-998D-738136618CD9,199020651,2019-09-08 10:10:07,09/08/2019 10:00:00 AM,09/08/2019 10:03:43 AM,Z--EARLY CLOSED,600.0,4,5.0,THEFT,...,UNKNOWN,NaN,NOT OF HISPANIC ORIG,MALE,1.0,1.0,THEFT,45237.0,NaN,NaN
152773,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,1493.0,4,2.0,CRIMINAL DAMAGING/ENDANGERING,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,PART 2 MINOR,45206.0,WALNUT HILLS,WALNUT HILLS
152774,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,1493.0,4,2.0,CRIMINAL DAMAGING/ENDANGERING,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,PART 2 MINOR,45206.0,WALNUT HILLS,WALNUT HILLS
152775,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS
152776,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS

In [30]:
list(dfCrime['UCR_GROUP'].unique())

['THEFT',
 'PART 2 MINOR',
 'BURGLARY/BREAKING ENTERING',
 'AGGRAVATED ASSAULTS',
 'RAPE',
 'ROBBERY',
 'UNAUTHORIZED USE',
 'HOMICIDE',
 nan]

In [31]:
violentCrimes = ['ROBBERY', 'AGGRAVATED ASSAULTS', 'RAPE', 'HOMICIDE']
dfCrime = dfCrime[dfCrime['UCR_GROUP'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(3772, 40)

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
152779,D5263F26-5BDB-4016-B2E8-2B17EBC1C3C9,199020649,2019-09-08 07:50:00,09/08/2019 07:40:00 AM,09/08/2019 07:50:00 AM,J--CLOSED,401.0,2,3.0,FELONIOUS ASSAULT,...,UNKNOWN,NaN,UNKNOWN,UNKNOWN,2.0,1.0,AGGRAVATED ASSAULTS,45213.0,KENNEDY HEIGHTS,KENNEDY HEIGHTS
152780,D5263F26-5BDB-4016-B2E8-2B17EBC1C3C9,199020649,2019-09-08 07:50:00,09/08/2019 07:40:00 AM,09/08/2019 07:50:00 AM,J--CLOSED,401.0,2,3.0,FELONIOUS ASSAULT,...,UNKNOWN,NaN,UNKNOWN,UNKNOWN,2.0,1.0,AGGRAVATED ASSAULTS,45213.0,KENNEDY HEIGHTS,KENNEDY HEIGHTS
152781,41059EED-450D-4CD9-8350-C2F405593BA5,209002350,2019-09-08 07:30:00,09/08/2019 04:00:00 AM,09/08/2019 04:10:00 AM,J--CLOSED,201.0,1,3.0,RAPE,...,18-25,NaN,UNKNOWN,MALE,1.0,1.0,RAPE,45202.0,WEST END,WEST END
152789,5BD00382-2A42-41A5-A053-9E640259D5DD,199020645,2019-09-08 04:15:00,09/08/2019 04:15:00 AM,09/08/2019 04:10:00 AM,J--CLOSED,401.0,4,1.0,FELONIOUS ASSAULT,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,AGGRAVATED ASSAULTS,45219.0,NaN,NaN
152830,53B748B0-6F10-441F-B85F-D4FC05995F16,199020013,2019-09-01 12:56:11,09/01/2019 12:40:00 PM,09/01/2019 12:45:00 PM,D--VICTIM REFUSED TO COOPERATE,401.0,2,3.0,FELONIOUS ASSAULT,...,UNDER 18,NaN,NOT OF HISPANIC ORIG,MALE,1.0,2.0,AGGRAVATED ASSAULTS,45227.0,MADISONVILLE,MADISONVILLE

In [35]:
list(dfCrime.columns)

['INSTANCEID',
 'INCIDENT_NO',
 'DATE_REPORTED',
 'DATE_FROM',
 'DATE_TO',
 'CLSD',
 'UCR',
 'DST',
 'BEAT',
 'OFFENSE',
 'LOCATION',
 'THEFT_CODE',
 'FLOOR',
 'SIDE',
 'OPENING',
 'HATE_BIAS',
 'DAYOFWEEK',
 'RPT_AREA',
 'CPD_NEIGHBORHOOD',
 'WEAPONS',
 'DATE_OF_CLEARANCE',
 'HOUR_FROM',
 'HOUR_TO',
 'ADDRESS_X',
 'LONGITUDE_X',
 'LATITUDE_X',
 'VICTIM_AGE',
 'VICTIM_RACE',
 'VICTIM_ETHNICITY',
 'VICTIM_GENDER',
 'SUSPECT_AGE',
 'SUSPECT_RACE',
 'SUSPECT_ETHNICITY',
 'SUSPECT_GENDER',
 'TOTALNUMBERVICTIMS',
 'TOTALSUSPECTS',
 'UCR_GROUP',
 'ZIP',
 'COMMUNITY_COUNCIL_NEIGHBORHOOD',
 'SNA_NEIGHBORHOOD']

In [37]:
dfCrime = dfCrime[['UCR_GROUP',  'LONGITUDE_X', 'LATITUDE_X']]
dfCrime = dfCrime.dropna()
dfCrime.head()

                  UCR_GROUP  LONGITUDE_X  LATITUDE_X
152779  AGGRAVATED ASSAULTS   -84.411750   39.189419
152780  AGGRAVATED ASSAULTS   -84.411040   39.189169
152830  AGGRAVATED ASSAULTS   -84.389868   39.157509
152831  AGGRAVATED ASSAULTS   -84.390508   39.157609
152832              ROBBERY   -84.566661   39.190824

In [39]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['LONGITUDE_X'], row['LATITUDE_X']), axis=1)
dfCrime = dfCrime[['UCR_GROUP', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(2648, 2)

                  UCR_GROUP                                     geometry
152779  AGGRAVATED ASSAULTS  POINT (-84.41175029999999 39.1894192200597)
152780  AGGRAVATED ASSAULTS         POINT (-84.4110403 39.1891692200597)
152830  AGGRAVATED ASSAULTS        POINT (-84.38986765 39.1575088100598)
152831  AGGRAVATED ASSAULTS        POINT (-84.39050765 39.1576088100598)
152832              ROBBERY        POINT (-84.56666084 39.1908242700598)

In [43]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_39_bg_500k/cb_2018_39_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(9234, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,39,153,532706,1,1500000US391535327061,391535327061,1,BG,894129,3255,"POLYGON ((-81.576 41.316, -81.571 41.314, -81...."
1,39,049,006383,4,1500000US390490063834,390490063834,4,BG,594035,7177,"POLYGON ((-83.091 40.113, -83.086 40.112, -83...."
2,39,055,310100,1,1500000US390553101001,390553101001,1,BG,29788713,138730,"POLYGON ((-81.052 41.703, -81.051 41.714, -81...."
3,39,091,004500,1,1500000US390910045001,390910045001,1,BG,861909,0,"POLYGON ((-83.764 40.367, -83.763 40.375, -83...."
4,39,035,141100,2,1500000US390351411002,390351411002,2,BG,200434,0,"POLYGON ((-81.584 41.51, -81.578 41.513, -81.5..."

In [45]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                  UCR_GROUP                geometry
152779  AGGRAVATED ASSAULTS  POINT (-84.412 39.189)
152780  AGGRAVATED ASSAULTS  POINT (-84.411 39.189)
152830  AGGRAVATED ASSAULTS   POINT (-84.39 39.158)
152831  AGGRAVATED ASSAULTS  POINT (-84.391 39.158)
152832              ROBBERY  POINT (-84.567 39.191)

In [47]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(2648, 13)

,UCR_GROUP,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
152779,AGGRAVATED ASSAULTS,POINT (-84.412 39.189),6513,39,061,005800,4,1500000US390610058004,390610058004,4,BG,518594,0
152780,AGGRAVATED ASSAULTS,POINT (-84.411 39.189),6513,39,061,005800,4,1500000US390610058004,390610058004,4,BG,518594,0
152830,AGGRAVATED ASSAULTS,POINT (-84.39 39.158),2233,39,061,005600,4,1500000US390610056004,390610056004,4,BG,589913,0
152831,AGGRAVATED ASSAULTS,POINT (-84.391 39.158),2233,39,061,005600,4,1500000US390610056004,390610056004,4,BG,589913,0
152832,ROBBERY,POINT (-84.567 39.191),1022,39,061,008501,2,1500000US390610085012,390610085012,2,BG,1209610,0

In [49]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US390610080001    104
1500000US390610085021     61
1500000US390610017001     46
1500000US390610095003     45
1500000US390610094001     45
                        ...
1500000US390610213043      1
1500000US390610222002      1
1500000US390610057023      1
1500000US390610053023      1
1500000US390610063004      1
Name: count, Length: 258, dtype: int64

In [51]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cinci_Violent_Crime_BG.csv')