In [3]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [5]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/Crime_Responses_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(218443, 14)

,ID,Incident Type,Report Date,Offense Date,Report Hour of Day,Report Day of Week,Offense Hour of Day,Offense Day of Week,City,State,Address,Latitude,Longitude,Location
0,224011105,Domestic Disturbance,07/29/2024 04:03:32 PM,07/29/2024 01:31:00 PM,16,Monday,13,Monday,GAINESVILLE,FL,2600 BLK SW 31ST PL,29.622560,-82.362176,POINT (-82.362176449 29.622560033)
1,624031377,Theft Petit - Other,07/29/2024 12:00:00 AM,07/19/2024 12:00:00 AM,0,Monday,0,Friday,GAINESVILLE,FL,4800 BLK NW 43RD ST,29.698213,-82.388973,POINT (-82.388973096 29.698212938)
2,624031364,Lost Property,07/24/2024 12:00:00 AM,07/21/2024 12:00:00 AM,0,Wednesday,0,Sunday,GAINESVILLE,FL,2300 BLK SW ARCHER RD,29.634376,-82.357197,POINT (-82.35719669 29.634376389)
3,624031366,Theft Petit - Other,07/24/2024 12:00:00 AM,07/24/2024 12:00:00 AM,0,Wednesday,0,Wednesday,GAINESVILLE,FL,1800 BLK NE 12TH AVE,29.664166,-82.304632,POINT (-82.304632382 29.664165588)
4,224011111,Baker Act,07/29/2024 05:57:57 PM,07/29/2024 04:40:56 PM,17,Monday,16,Monday,GAINESVILLE,FL,2400 BLK NW 43RD ST,29.676146,-82.388958,POINT (-82.388957608 29.67614599)

In [9]:
dfCrime['Offense Date'] = pd.to_datetime(dfCrime['Offense Date'])
dfCrime = dfCrime[(dfCrime['Offense Date'] >= '2018-01-01') & (dfCrime['Offense Date'] < '2019-01-01')]
print(dfCrime.shape)
dfCrime.head()

(16337, 14)

,ID,Incident Type,Report Date,Offense Date,Report Hour of Day,Report Day of Week,Offense Hour of Day,Offense Day of Week,City,State,Address,Latitude,Longitude,Location
7084,224012723,Information,08/30/2024 01:00:00 PM,2018-06-05 17:00:00,13,Friday,17,Tuesday,GAINESVILLE,FL,300 BLK NE 3RD AVE,29.653986,-82.321987,POINT (-82.321986715 29.653986012)
7220,223018125,Identity Theft,11/13/2023 06:19:22 PM,2018-01-01 00:00:00,18,Monday,0,Monday,GAINESVILLE,FL,600 BLK NE 21ST ST,29.657599,-82.297586,POINT (-82.297585957 29.657599404)
8306,223018602,Sexual Battery,11/22/2023 11:43:12 AM,2018-01-01 00:00:00,11,Wednesday,0,Monday,GAINESVILLE,FL,3400 BLK NE 39TH AVE,29.677524,-82.274621,POINT (-82.274620676 29.677524327)
13034,224014351,Lewd/lasc. Act to a Child Under 16,09/27/2024 06:50:19 PM,2018-09-27 12:00:18,18,Friday,12,Thursday,GAINESVILLE,FL,1000 BLK NE 1ST AVE,29.652898,-82.312470,POINT (-82.31246984 29.652897618)
18794,224017558,Assist Other Agency,11/21/2024 03:12:02 PM,2018-11-21 15:40:01,15,Thursday,15,Wednesday,GAINESVILLE,FL,1000 BLK SE 12TH ST,29.642080,-82.310900,POINT (-82.3109 29.64208)

In [13]:
sorted(list(dfCrime['Incident Type'].unique()))

['Affray',
 'Aircraft Incident',
 'All Other Liquor Law Viol.',
 'Animal Attack',
 'Animal Cruelty',
 'Animal Problem',
 'Arson',
 'Assault (aggravated)',
 'Assault (police Officer Aggravated)',
 'Assault (simple)',
 'Assist Citizen',
 'Assist Other Agency',
 'Battery (aggravated)',
 'Battery (felony)',
 'Battery (police Officer Aggravated)',
 'Battery (police Officer)',
 'Battery (security Guard/officer Aggravated)',
 'Battery (security Guard/officer)',
 'Battery (simple – With Other Weapon)',
 'Battery (simple)',
 'Battery on Detention or Commitment Facility Staff (simple)',
 'Battery on a Emergency Medicalcare Provider',
 'Battery on a Person 65 Yoa or Older',
 'Battery on a School Board Employee',
 'Bomb Threat',
 'Burglary to Business',
 'Burglary to Conveyance',
 'Burglary to Residence',
 'Burglary to a Structure',
 'Career Offender Violation',
 'City Ordinance Violation',
 'Computer Crimes',
 'Counterfeiting',
 'Crimes Against the Elderly',
 'Criminal Mischief',
 'Criminal Mischief (felony)',
 'Criminal Mischief (misdemeanor)',
 'Cyber Stalking',
 'Damage to City Property',
 'Damage to Property',
 'Dating Violence Aggravated Assault',
 'Dating Violence Aggravated Battery',
 'Dating Violence Aggravated Battery by Strangulation',
 'Dating Violence Aggravated Stalking',
 'Dating Violence Felony Battery',
 'Dating Violence Simple Battery',
 'Dating Violence Simple Stalking',
 'Dcf Investigations',
 'Death Investigation',
 'Defrauding an Innkeeper/obtain Food/lodging by Defrauding',
 'Discharge Firearm in Public',
 'Disorderly Conduct',
 'Disorderly Intoxication',
 'Disruption of School Function',
 'Disturbance',
 'Disturbance Civil',
 'Domestic Aggravated Assualt',
 'Domestic Aggravated Battery',
 'Domestic Assault',
 'Domestic Battery by Strangulation',
 'Domestic Disturbance',
 'Domestic Felony Battery Repeat Offender',
 'Domestic Simple Battery',
 'Domestic Violence Injunction Violation',
 'Domestic Violence Violation of Pretrial Release-no Contact',
 'Driving Under the Influence',
 'Driving While License Suspended/revoked',
 'Driving With No License',
 'Drug Equip/paraphernalia',
 'Drug Poss. of Controlled Substance',
 'Drug Violation',
 'Drug Violation (buying)',
 'Drug Violation (selling)',
 'Drug Violation (sid)',
 'Drug Violation (using)',
 'Escaped Prisoner',
 'Exploitation of the Elderly/disabled',
 'Exposure of Sexual Organs / Indecent Exposure',
 'Extortion/threats',
 'False Imprisonment(kidnap)',
 'False Info on Pawn Transaction Form',
 'False Info to Leo',
 'Falsely Personating Officer',
 'Filing False Police Report',
 'Fire',
 'Flee/attempt to Elude Police Officer',
 'Found Contraband',
 'Found Property',
 'Fraud (all Other)',
 'Fraud (credit Card/atm)',
 'Fraud (forgery)',
 'Fraud (impersonation)',
 'Fraud (obtain Money/property by False Pretense)',
 'Fraud (welfare)',
 'Fraud (worthless Check)',
 'Gas Drive Off',
 'Harassing/ Obscene Calls',
 'Harassment',
 'Hinder, Delay, Prevent Communication to Law Enforcement',
 'Hit & Run',
 'Homicide',
 'Identity Theft',
 'Indecent Exposure',
 'Information',
 'Introduction of Contraband Into County Detention Facility',
 'Juvenile Problem / Disturbance',
 'Lewd or Lascivious Molestation Offender 18 or Older',
 'Lewd/lasc. Act to a Child Under 16',
 'Loitering and Prowling',
 'Lost Property',
 'Lost/stolen Vehicle Tag / Decal',
 'Making False 911 Call',
 'Missing Person',
 'Molestation of Vending Machine',
 'Money Laundering',
 'Noise Complaint',
 'Panhandling',
 'Poss. of Alcohol Under 21 Yoa',
 'Possess Firearm/concealed Weapon by Convicted Felon',
 'Possession of Child Pornography',
 'Possession of Less Than 20g of Cannabis',
 'Property Recovered',
 'Prostitution',
 'Reckless Driving',
 'Recovered Stolen Veh',
 'Resist Merchant Use Antishoplifting Cntrl Dvc Countermeasure',
 'Resist/obstructing With Violence',
 'Resist/obstructing Without Violence',
 'Resisting Merchant Detainment',
 'Robbery',
 'Robbery (armed)',
 'Robbery (carjacking)',
 'Robbery (home Invasion)',
 'Robbery (strong Arm)',
 'Robbery by Sudden Snatching',
 'Runaway',
 'Seize Tag',
 'Sex Offender/predator Violation <48 Hrs',
 'Sexual Battery',
 'Sexual Battery With an Object',
 'Shooting/throwing a Deadly Missile Into a Dwelling/vehicle',
 'Sick / Injured Person',
 'Stalking (aggravated)',
 'Stalking (simple)',
 'Stalking - Vio. of Court Order',
 'Stolen Property (possession/conceal)',
 'Stolen Property (selling/distributing)',
 'Stolen Vehicle (auto)',
 'Stolen Vehicle (motorcycle)',
 'Stolen Vehicle (other)',
 'Stolen Vehicle (truck)',
 'Suspicious Incident',
 'Tamper W/victim Witness',
 'Tampering With Evidence',
 'Theft Grand - Bicycle',
 'Theft Grand - From Building',
 'Theft Grand - From Vehicle (not Parts)',
 'Theft Grand - From Vehicle (vehicle Parts)',
 'Theft Grand - From Vending Machine',
 'Theft Grand - Other',
 'Theft Grand - Pocket-picking',
 'Theft Grand - Purse Snatching',
 'Theft Grand - Retail',
 'Theft Grand - Trailer',
 'Theft Petit - Bicycle',
 'Theft Petit - From Building',
 'Theft Petit - From Vehicle (vehicle Parts)',
 'Theft Petit - From Vehicle/not Parts',
 'Theft Petit - From Vending Machine',
 'Theft Petit - Other',
 'Theft Petit - Pocket-picking',
 'Theft Petit - Retail',
 'Theft Petit - Trailer',
 'Threatening Phone Calls',
 'Tow Report',
 'Traffic Offense (all Other)',
 'Trash Dumping',
 'Trespass',
 'Trespass Warning',
 'Unauthorized Poss Manuf Fl Dl',
 'Utter Forged/counterfeit Bill',
 'Uttering Forged Instruments',
 'Vehicle Not Registered',
 'Verbal Threats',
 'Violation of Permanent Injunction',
 'Violation of Pretrial Release',
 'Violation of Probation',
 'Violation of Probation - Juvenile',
 'Violation of Temporary Injunction',
 'Warrant Arrest',
 'Weapons Violation',
 'Weapons Violation (possessing/concealing)',
 'Written Threat to Kill or Injure']

In [15]:
violentCrimes = ['Assault (aggravated)', 'Dating Violence Aggravated Assault', 'Domestic Aggravated Assualt', 
                 'Homicide', 'Lewd or Lascivious Molestation Offender 18 or Older', 'Lewd/lasc. Act to a Child Under 16',
                'Robbery',
 'Robbery (armed)',
 'Robbery (carjacking)',
 'Robbery (home Invasion)',
 'Robbery (strong Arm)',
 'Robbery by Sudden Snatching',
                'Sexual Battery',
 'Sexual Battery With an Object']
dfCrime = dfCrime[dfCrime['Incident Type'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(346, 14)

,ID,Incident Type,Report Date,Offense Date,Report Hour of Day,Report Day of Week,Offense Hour of Day,Offense Day of Week,City,State,Address,Latitude,Longitude,Location
8306,223018602,Sexual Battery,11/22/2023 11:43:12 AM,2018-01-01 00:00:00,11,Wednesday,0,Monday,GAINESVILLE,FL,3400 BLK NE 39TH AVE,29.677524,-82.274621,POINT (-82.274620676 29.677524327)
13034,224014351,Lewd/lasc. Act to a Child Under 16,09/27/2024 06:50:19 PM,2018-09-27 12:00:18,18,Friday,12,Thursday,GAINESVILLE,FL,1000 BLK NE 1ST AVE,29.652898,-82.312470,POINT (-82.31246984 29.652897618)
22097,224019434,Lewd/lasc. Act to a Child Under 16,12/31/2024 04:49:02 PM,2018-01-01 00:00:00,16,Tuesday,0,Monday,GAINESVILLE,FL,3500 BLK SW 39TH BLVD,29.617420,-82.375390,POINT (-82.37539 29.61742)
22909,225000629,Lewd or Lascivious Molestation Offender 18 or ...,01/14/2025 08:27:00 AM,2018-04-01 00:00:00,8,Tuesday,0,Sunday,GAINESVILLE,FL,2500 BLK NW 58TH AVE,29.707930,-82.359710,POINT (-82.35971 29.70793)
24234,225003384,Sexual Battery With an Object,03/07/2025 05:47:36 PM,2018-05-19 18:00:00,17,Friday,18,Saturday,GAINESVILLE,FL,100 BLK N MAIN ST,29.652780,-82.325020,POINT (-82.32502 29.65278)

In [17]:
list(dfCrime.columns)

['ID',
 'Incident Type',
 'Report Date',
 'Offense Date',
 'Report Hour of Day',
 'Report Day of Week',
 'Offense Hour of Day',
 'Offense Day of Week',
 'City',
 'State',
 'Address',
 'Latitude',
 'Longitude',
 'Location']

In [19]:
dfCrime = dfCrime[['Address',  'Longitude', 'Latitude']]
dfCrime.head()

                     Address  Longitude   Latitude
8306    3400 BLK NE 39TH AVE -82.274621  29.677524
13034    1000 BLK NE 1ST AVE -82.312470  29.652898
22097  3500 BLK SW 39TH BLVD -82.375390  29.617420
22909   2500 BLK NW 58TH AVE -82.359710  29.707930
24234      100 BLK N MAIN ST -82.325020  29.652780

In [21]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Address', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(346, 2)

                     Address                                 geometry
8306    3400 BLK NE 39TH AVE       POINT (-82.274620676 29.677524327)
13034    1000 BLK NE 1ST AVE  POINT (-82.31246984000001 29.652897618)
22097  3500 BLK SW 39TH BLVD               POINT (-82.37539 29.61742)
22909   2500 BLK NW 58TH AVE      POINT (-82.35971000000001 29.70793)
24234      100 BLK N MAIN ST      POINT (-82.32501999999999 29.65278)

In [23]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Downloads/Rent-Walk-Local/cb_2018_12_bg_500k/cb_2018_12_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(11409, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,12,011,010104,1,1500000US120110101041,120110101041,1,BG,418681,571688,"POLYGON ((-80.081 26.321, -80.08 26.321, -80.0..."
1,12,005,002705,1,1500000US120050027051,120050027051,1,BG,1127491,2212287,"POLYGON ((-85.817 30.187, -85.817 30.188, -85...."
2,12,057,006400,1,1500000US120570064001,120570064001,1,BG,515469,99623,"POLYGON ((-82.535 27.922, -82.534 27.923, -82...."
3,12,011,031205,1,1500000US120110312051,120110312051,1,BG,165404,17385,"POLYGON ((-80.09 26.25, -80.089 26.253, -80.08..."
4,12,103,020209,1,1500000US121030202091,121030202091,1,BG,622112,298583,"POLYGON ((-82.663 27.708, -82.663 27.708, -82...."

In [25]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                     Address                geometry
8306    3400 BLK NE 39TH AVE  POINT (-82.275 29.678)
13034    1000 BLK NE 1ST AVE  POINT (-82.312 29.653)
22097  3500 BLK SW 39TH BLVD  POINT (-82.375 29.617)
22909   2500 BLK NW 58TH AVE   POINT (-82.36 29.708)
24234      100 BLK N MAIN ST  POINT (-82.325 29.653)

In [27]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(346, 13)

,Address,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
8306,3400 BLK NE 39TH AVE,POINT (-82.275 29.678),9433.0,12,001,001902,2,1500000US120010019022,120010019022,2,BG,11376807.0,36793.0
13034,1000 BLK NE 1ST AVE,POINT (-82.312 29.653),883.0,12,001,000500,4,1500000US120010005004,120010005004,4,BG,670674.0,0.0
22097,3500 BLK SW 39TH BLVD,POINT (-82.375 29.617),7177.0,12,001,001519,1,1500000US120010015191,120010015191,1,BG,1962044.0,7459.0
22909,2500 BLK NW 58TH AVE,POINT (-82.36 29.708),7179.0,12,001,001803,3,1500000US120010018033,120010018033,3,BG,1404378.0,0.0
24234,100 BLK N MAIN ST,POINT (-82.325 29.653),976.0,12,001,000500,1,1500000US120010005001,120010005001,1,BG,1379930.0,0.0

In [29]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US120010005001    20
1500000US120010006001    15
1500000US120010003012    15
1500000US120010018033    14
1500000US120010015191    14
                         ..
1500000US120010018032     1
1500000US120011108001     1
1500000US120010016043     1
1500000US120010012011     1
1500000US120010003021     1
Name: count, Length: 73, dtype: int64

In [31]:
# export as a csv
crime.to_csv('Gaines_Violent_Crime_BG.csv')