In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Police_Department_Incident_Reports__2018_to_Present_20250412.csv')
print(dfCrime.shape)
dfCrime.head()

(947910, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023,Wednesday,2023/03/11 04:55:00 PM,125378606372,1253786,236046123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/11 03:00:00 PM,2023/03/11,15:00,2023,Saturday,2023/03/13 08:29:00 AM,125420606244,1254206,236045937,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(896213, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
6,2022/06/27 12:00:00 PM,2022/06/27,12:00,2022,Monday,2023/03/15 05:20:00 PM,125439371000,1254393,230184129,230742480.0,...,-122.408227,POINT (-122.40822672700406 37.78735926098589),19.0,NaN,1.0,NaN,NaN,NaN,3.0,6.0
8,2023/03/16 05:30:00 PM,2023/03/16,17:30,2023,Thursday,2023/03/16 06:02:00 PM,125482604134,1254826,230187101,230752550.0,...,-122.401324,POINT (-122.40132418490647 37.76228996810526),54.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
26,2023/03/21 03:50:00 PM,2023/03/21,15:50,2023,Tuesday,2023/03/21 04:01:00 PM,125656351040,1256563,230199764,230802198.0,...,-122.418271,POINT (-122.41827098126804 37.787037946181535),50.0,NaN,NaN,NaN,NaN,NaN,10.0,6.0
144,2021/07/03 12:00:00 PM,2021/07/03,12:00,2021,Saturday,2021/07/03 12:37:00 PM,104624471000,1046244,210417332,211841413.0,...,-122.446610,POINT (-122.44660957715965 37.801787342426636),17.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
145,2021/07/22 07:16:00 PM,2021/07/22,19:16,2021,Thursday,2021/07/23 01:35:00 PM,105341571000,1053415,216098495,NaN,...,-122.394829,POINT (-122.39482876133759 37.76524759917852),54.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0

In [5]:
dfCrime = dfCrime[dfCrime['Incident Year'] == 2019]
print(dfCrime.shape)
dfCrime.head()

(138391, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019,Tuesday,2021/06/05 05:17:00 AM,103770002004,1037700,210348157,211560467.0,...,-122.408846,POINT (-122.40884575063417 37.775953228502786),32.0,NaN,NaN,1.0,1.0,NaN,10.0,1.0
790,2019/06/01 12:00:00 AM,2019/06/01,00:00,2019,Saturday,2022/03/29 10:45:00 AM,113536668030,1135366,220204947,220881074.0,...,-122.391434,POINT (-122.39143433652146 37.773466920607476),34.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0
3841,2019/04/01 12:00:00 AM,2019/04/01,00:00,2019,Monday,2023/02/06 12:36:00 PM,125811771000,1258117,236054370,NaN,...,-122.415291,POINT (-122.41529083617453 37.71350427378473),75.0,NaN,NaN,NaN,NaN,NaN,9.0,9.0
6261,2019/07/26 08:00:00 AM,2019/07/26,08:00,2019,Friday,2023/08/31 01:50:00 PM,131347507026,1313475,230622395,232430739.0,...,-122.404306,POINT (-122.40430629342 37.74252073319404),82.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
6428,2019/02/06 06:00:00 PM,2019/02/06,18:00,2019,Wednesday,2023/02/10 03:32:00 PM,125982406372,1259824,236024323,NaN,...,-122.416401,POINT (-122.41640107183976 37.777722750028566),21.0,NaN,1.0,1.0,1.0,NaN,10.0,5.0

In [6]:
violentCrimes = ['Aggravated Assault', 'Rape - Attempted', 'Robbery - Residential', 'Robbery - Street', 'Robbery - Carjacking',
                'Sex Offense', 'Robbery - Commercial', 'Rape', 'Homicide', 'Robbery - Other']
dfCrime = dfCrime[dfCrime['Incident Subcategory'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(6663, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019,Tuesday,2021/06/05 05:17:00 AM,103770002004,1037700,210348157,211560467.0,...,-122.408846,POINT (-122.40884575063417 37.775953228502786),32.0,NaN,NaN,1.0,1.0,NaN,10.0,1.0
21467,2019/05/05 12:00:00 AM,2019/05/05,00:00,2019,Sunday,2024/09/05 05:35:00 PM,142153502020,1421535,240559352,242492705.0,...,-122.481178,POINT (-122.4811782836914 37.74468231201172),40.0,NaN,NaN,NaN,NaN,NaN,7.0,10.0
38663,2019/06/01 11:00:00 PM,2019/06/01,23:00,2019,Saturday,2023/05/30 10:17:00 PM,128090103074,1280901,230374289,231503362.0,...,-122.408189,POINT (-122.40818896891844 37.75285240350464),53.0,NaN,NaN,NaN,3.0,NaN,2.0,3.0
59579,2019/11/21 01:20:00 AM,2019/11/21,01:20,2019,Thursday,2024/01/05 05:00:00 PM,135345804013,1353458,190880538,NaN,...,-122.414054,POINT (-122.41405376568504 37.78279444506034),20.0,NaN,1.0,1.0,1.0,NaN,10.0,5.0
96916,2019/12/21 12:00:00 AM,2019/12/21,00:00,2019,Saturday,2024/06/20 10:00:00 AM,140016814020,1400168,240384870,241720966.0,...,-122.403633,POINT (-122.40363311767578 37.77516174316406),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0

In [7]:
dfCrime = dfCrime[['Incident ID', 'Longitude', 'Latitude']]
dfCrime.head()

       Incident ID   Longitude   Latitude
200        1037700 -122.408846  37.775953
21467      1421535 -122.481178  37.744682
38663      1280901 -122.408189  37.752852
59579      1353458 -122.414054  37.782794
96916      1400168 -122.403633  37.775162

In [8]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident ID', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(6663, 2)

       Incident ID                                      geometry
200        1037700  POINT (-122.4088457506342 37.77595322850279)
21467      1421535  POINT (-122.4811782836914 37.74468231201172)
38663      1280901  POINT (-122.4081889689184 37.75285240350464)
59579      1353458   POINT (-122.414053765685 37.78279444506034)
96916      1400168  POINT (-122.4036331176758 37.77516174316406)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [10]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident ID                geometry
200        1037700  POINT (-122.41 37.776)
21467      1421535  POINT (-122.48 37.745)
38663      1280901  POINT (-122.41 37.753)
59579      1353458  POINT (-122.41 37.783)
96916      1400168   POINT (-122.4 37.775)

In [11]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(6663, 13)

,Incident ID,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
200,1037700,POINT (-122.41 37.776),11436,06,075,017802,1,1500000US060750178021,060750178021,1,BG,320288,0
21467,1421535,POINT (-122.48 37.745),6835,06,075,032801,3,1500000US060750328013,060750328013,3,BG,235236,0
38663,1280901,POINT (-122.41 37.753),14539,06,075,022903,1,1500000US060750229031,060750229031,1,BG,88035,0
59579,1353458,POINT (-122.41 37.783),21414,06,075,012502,2,1500000US060750125022,060750125022,2,BG,30632,0
96916,1400168,POINT (-122.4 37.775),10013,06,075,018000,2,1500000US060750180002,060750180002,2,BG,509339,0

In [12]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750117002    205
1500000US060750615001    200
1500000US060750176015    178
1500000US060750125012    138
1500000US060750176013    123
                        ...
1500000US060750478023      1
1500000US060750352013      1
1500000US060750328022      1
1500000US060750326012      1
1500000US060750168023      1
Name: count, Length: 486, dtype: int64

In [13]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_Violent_Crime_BG.csv')