In [19]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [21]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/PDI__Police_Data_Initiative__Crime_Incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17053/1369205608.py:1: DtypeWarning: Columns (1,8,12,13,14,17,27,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/PDI__Police_Data_Initiative__Crime_Incidents_20250422.csv')

(538814, 40)

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
0,5D3A0BAF-7F75-4FCE-AD7D-454367AC1AC0,249014554,06/02/2024 11:19:00 PM,06/02/2024 11:15:00 PM,06/02/2024 11:19:00 PM,F--CLEARED BY ARREST - ADULT,862.0,3,4,DOMESTIC VIOLENCE,...,UNKNOWN,NaN,NaN,NaN,1.0,NaN,PART 2 MINOR,45225.0,ENGLISH WOODS,ENGLISH WOODS
1,927F0CDF-59DF-43EC-99EC-9055F749B169,249014567,06/02/2024 11:03:00 PM,06/02/2024 11:00:00 PM,06/02/2024 11:02:00 PM,F--CLEARED BY ARREST - ADULT,2709.0,1,2,VIOLATE PROTECTION ORDER/CONSENT AGREEMENT,...,UNKNOWN,NaN,NaN,NaN,NaN,NaN,PART 2 MINOR,45202.0,OTR,OVER-THE-RHINE
2,3959F0C0-A992-4A19-B188-3469061241BF,249014562,06/02/2024 11:00:00 PM,06/02/2024 10:45:00 PM,06/02/2024 10:58:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,CORRYVILLE,CORRYVILLE
3,3959F0C0-A992-4A19-B188-3469061241BF,249014562,06/02/2024 11:00:00 PM,06/02/2024 10:45:00 PM,06/02/2024 10:58:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,CORRYVILLE,CORRYVILLE
4,14AF299C-3F8A-472C-926C-30A56733C5C0,249014548,06/02/2024 10:29:19 PM,06/02/2024 09:55:00 PM,06/02/2024 10:00:00 PM,H--WARRANT ISSUED,600.0,4,1,THEFT,...,UNDER 18,NaN,NaN,FEMALE,NaN,NaN,THEFT,45219.0,NaN,NaN

In [22]:
dfCrime['DATE_REPORTED'] = pd.to_datetime(dfCrime['DATE_REPORTED'])
dfCrime = dfCrime[(dfCrime['DATE_REPORTED'] >= '2019-01-01') & (dfCrime['DATE_REPORTED'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17053/2666128640.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dfCrime['DATE_REPORTED'] = pd.to_datetime(dfCrime['DATE_REPORTED'])

(36198, 40)

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
152772,DD2F4318-6B3A-4469-998D-738136618CD9,199020651,2019-09-08 10:10:07,09/08/2019 10:00:00 AM,09/08/2019 10:03:43 AM,Z--EARLY CLOSED,600.0,4,5.0,THEFT,...,UNKNOWN,NaN,NOT OF HISPANIC ORIG,MALE,1.0,1.0,THEFT,45237.0,NaN,NaN
152773,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,1493.0,4,2.0,CRIMINAL DAMAGING/ENDANGERING,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,PART 2 MINOR,45206.0,WALNUT HILLS,WALNUT HILLS
152774,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,1493.0,4,2.0,CRIMINAL DAMAGING/ENDANGERING,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,PART 2 MINOR,45206.0,WALNUT HILLS,WALNUT HILLS
152775,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS
152776,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS

In [23]:
list(dfCrime.columns)

['INSTANCEID',
 'INCIDENT_NO',
 'DATE_REPORTED',
 'DATE_FROM',
 'DATE_TO',
 'CLSD',
 'UCR',
 'DST',
 'BEAT',
 'OFFENSE',
 'LOCATION',
 'THEFT_CODE',
 'FLOOR',
 'SIDE',
 'OPENING',
 'HATE_BIAS',
 'DAYOFWEEK',
 'RPT_AREA',
 'CPD_NEIGHBORHOOD',
 'WEAPONS',
 'DATE_OF_CLEARANCE',
 'HOUR_FROM',
 'HOUR_TO',
 'ADDRESS_X',
 'LONGITUDE_X',
 'LATITUDE_X',
 'VICTIM_AGE',
 'VICTIM_RACE',
 'VICTIM_ETHNICITY',
 'VICTIM_GENDER',
 'SUSPECT_AGE',
 'SUSPECT_RACE',
 'SUSPECT_ETHNICITY',
 'SUSPECT_GENDER',
 'TOTALNUMBERVICTIMS',
 'TOTALSUSPECTS',
 'UCR_GROUP',
 'ZIP',
 'COMMUNITY_COUNCIL_NEIGHBORHOOD',
 'SNA_NEIGHBORHOOD']

In [24]:
list(dfCrime['THEFT_CODE'].unique())

['23C-SHOPLIFTING',
 nan,
 '23F-THEFT FROM MOTOR VEHICLE',
 '24O-MOTOR VEHICLE THEFT',
 '23H-ALL OTHER LARCENY',
 '23D-THEFT FROM BUILDING',
 '23E-THEFT FROM COIN-OPERATED MACHINE OR DEVICE',
 '23G-THEFT OF MOTOR VEHICLE PARTS OR ACCESSORIES',
 '24I-THEFT OF LICENSE PLATE',
 '23A-POCKET-PICKING',
 '23B-PURSE-SNATCHING']

In [25]:
list(dfCrime['OFFENSE'].unique())

['THEFT',
 'CRIMINAL DAMAGING/ENDANGERING',
 'BURGLARY',
 'FELONIOUS ASSAULT',
 'RAPE',
 'AGGRAVATED MENACING',
 'IMPROPERLY DISCHARGING FIREARM AT/INTO HABITATION/SCHOOL',
 'BREAKING AND ENTERING',
 'DOMESTIC VIOLENCE',
 'MENACING',
 'INTIMIDATION',
 'ASSAULT',
 'ROBBERY',
 'WIRE FRAUD',
 'VIOLATE PROTECTION ORDER/CONSENT AGREEMENT',
 'AGGRAVATED ROBBERY',
 'TELEPHONE HARASSMENT',
 'UNLAWFUL RESTRAINT',
 'TAKING THE IDENTITY OF ANOTHER',
 'MISUSE OF CREDIT CARD',
 'CRIMINAL MISCHIEF',
 'AGGRAVATED BURGLARY',
 'KIDNAPPING',
 'UNAUTHORIZED USE OF MOTOR VEHICLE',
 'MURDER',
 'TAMPERING WITH COIN MACHINES',
 'VANDALISM',
 'INTERFERENCE WITH CUSTODY',
 'NEGLIGENT ASSAULT',
 'MENACING BY STALKING',
 'FAIL COMPLY ORDER/SIGNAL OF PO-ELUDE/FLEE',
 'FORGERY',
 'PASSING BAD CHECKS',
 'MAKING FALSE ALARMS',
 'GROSS SEXUAL IMPOSITION',
 'TELECOMMUNICATIONS FRAUD',
 'INDUCING PANIC',
 'AGGRAVATED TRESPASS',
 'PERSONATING AN OFFICER',
 'PUBLIC INDECENCY',
 'EXTORTION',
 'AGGRAVATED ASSAULT',
 'SEXUAL BATTERY',
 'SEXUAL IMPOSITION',
 'ENDANGERING CHILDREN',
 'UNLAWFUL SEXUAL CONDUCT WITH A MINOR',
 'ABDUCTION',
 'UNAUTHORIZED USE OF PROPERTY',
 'EMBEZZLEMENT',
 'RUNAWAY',
 'PATIENT ABUSE; NEGLECT',
 'DISRUPTING PUBLIC SERVICE',
 'BRIBERY',
 'CRIMINAL CHILD ENTICEMENT',
 'INVOLUNTARY MANSLAUGHTER',
 'VEHICULAR VANDALISM',
 'VOYEURISM',
 'RETALIATION',
 'NEGLIGENT HOMICIDE',
 'IMPORTUNING',
 'AGGRAVATED VEHICULAR ASSAULT',
 nan,
 'SAFECRACKING',
 'INTIMIDATION-PUBLIC SERV/PARTY OFF',
 'AGGRAVATED MURDER',
 'AGG VEH HOM/VEH HOM/VEH MNSLGHTER',
 'ARSON',
 'DEFRAUDING A LIVERY OR HOSTELRY',
 'IMPERSONATING PEACE OFFICER/PRIVATE POLICEMAN']

In [26]:
violentCrimes = ['RAPE', 'ROBBERY', 'AGGRAVATED ROBBERY', 'MURDER', 'AGGRAVATED ASSAULT', 'AGGRAVATED VEHICULAR ASSAULT', 'AGGRAVATED MURDER', 'AGG VEH HOM/VEH HOM/VEH MNSLGHTER']
propertyCrimes = ['THEFT', 'BURGLARY', 'BREAKING AND ENTERING', 'AGGRAVATED ROBBERY']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['OFFENSE'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(17977, 40)

,INSTANCEID,INCIDENT_NO,DATE_REPORTED,DATE_FROM,DATE_TO,CLSD,UCR,DST,BEAT,OFFENSE,...,SUSPECT_AGE,SUSPECT_RACE,SUSPECT_ETHNICITY,SUSPECT_GENDER,TOTALNUMBERVICTIMS,TOTALSUSPECTS,UCR_GROUP,ZIP,COMMUNITY_COUNCIL_NEIGHBORHOOD,SNA_NEIGHBORHOOD
152772,DD2F4318-6B3A-4469-998D-738136618CD9,199020651,2019-09-08 10:10:07,09/08/2019 10:00:00 AM,09/08/2019 10:03:43 AM,Z--EARLY CLOSED,600.0,4,5.0,THEFT,...,UNKNOWN,NaN,NOT OF HISPANIC ORIG,MALE,1.0,1.0,THEFT,45237.0,NaN,NaN
152775,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS
152776,514BC901-48D0-419B-8B32-244F4B9B43F7,199020652,2019-09-08 09:50:00,09/08/2019 09:40:00 AM,09/08/2019 09:48:00 AM,F--CLEARED BY ARREST - ADULT,551.0,4,2.0,BURGLARY,...,UNKNOWN,NaN,NaN,NaN,2.0,NaN,BURGLARY/BREAKING ENTERING,45206.0,WALNUT HILLS,WALNUT HILLS
152777,5E9D88CD-87BA-4BFF-961D-23BE82345134,199020647,2019-09-08 09:04:00,09/08/2019 09:00:00 AM,09/08/2019 09:04:00 AM,Z--EARLY CLOSED,600.0,2,3.0,THEFT,...,UNKNOWN,NaN,NaN,NaN,1.0,NaN,THEFT,45227.0,MADISONVILLE,MADISONVILLE
152778,5952470B-64CC-4A39-BCE3-0970BB79C3B9,199020656,2019-09-08 08:00:00,09/07/2019 11:00:00 PM,09/08/2019 07:00:00 AM,Z--EARLY CLOSED,600.0,2,2.0,THEFT,...,UNKNOWN,NaN,NaN,NaN,1.0,NaN,THEFT,45208.0,HYDE PARK,EVANSTON

In [27]:
dfCrime = dfCrime[['OFFENSE', 'THEFT_CODE', 'LONGITUDE_X', 'LATITUDE_X']]
dfCrime = dfCrime[dfCrime['LONGITUDE_X'].isna() == False]
dfCrime = dfCrime[dfCrime['LATITUDE_X'].isna() == False]
dfCrime.head()

         OFFENSE                    THEFT_CODE  LONGITUDE_X  LATITUDE_X
152775  BURGLARY                           NaN   -84.485349   39.136794
152776  BURGLARY                           NaN   -84.485759   39.136424
152777     THEFT  23F-THEFT FROM MOTOR VEHICLE   -84.388952   39.162829
152778     THEFT  23F-THEFT FROM MOTOR VEHICLE   -84.458723   39.140455
152790     THEFT         23H-ALL OTHER LARCENY   -84.386450   39.091529

In [28]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['LONGITUDE_X'], row['LATITUDE_X']), axis=1)
dfCrime = dfCrime[['OFFENSE', 'THEFT_CODE', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(14760, 3)

,OFFENSE,THEFT_CODE,geometry
152775,BURGLARY,NaN,POINT (-84.48534890000001 39.1367938400598)
152776,BURGLARY,NaN,POINT (-84.48575889999999 39.1364238400598)
152777,THEFT,23F-THEFT FROM MOTOR VEHICLE,POINT (-84.38895248999999 39.1628291300598)
152778,THEFT,23F-THEFT FROM MOTOR VEHICLE,POINT (-84.45872275000001 39.1404548300598)
152790,THEFT,23H-ALL OTHER LARCENY,POINT (-84.38645008 39.0915290800598)

In [29]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_39_bg_500k/cb_2018_39_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(9234, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,39,153,532706,1,1500000US391535327061,391535327061,1,BG,894129,3255,"POLYGON ((-81.576 41.316, -81.571 41.314, -81...."
1,39,049,006383,4,1500000US390490063834,390490063834,4,BG,594035,7177,"POLYGON ((-83.091 40.113, -83.086 40.112, -83...."
2,39,055,310100,1,1500000US390553101001,390553101001,1,BG,29788713,138730,"POLYGON ((-81.052 41.703, -81.051 41.714, -81...."
3,39,091,004500,1,1500000US390910045001,390910045001,1,BG,861909,0,"POLYGON ((-83.764 40.367, -83.763 40.375, -83...."
4,39,035,141100,2,1500000US390351411002,390351411002,2,BG,200434,0,"POLYGON ((-81.584 41.51, -81.578 41.513, -81.5..."

In [30]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

         OFFENSE                    THEFT_CODE                geometry
152775  BURGLARY                           NaN  POINT (-84.485 39.137)
152776  BURGLARY                           NaN  POINT (-84.486 39.136)
152777     THEFT  23F-THEFT FROM MOTOR VEHICLE  POINT (-84.389 39.163)
152778     THEFT  23F-THEFT FROM MOTOR VEHICLE   POINT (-84.459 39.14)
152790     THEFT         23H-ALL OTHER LARCENY  POINT (-84.386 39.092)

In [31]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(14760, 14)

,OFFENSE,THEFT_CODE,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
152775,BURGLARY,NaN,POINT (-84.485 39.137),8763,39,061,003600,2,1500000US390610036002,390610036002,2,BG,321958,0
152776,BURGLARY,NaN,POINT (-84.486 39.136),8763,39,061,003600,2,1500000US390610036002,390610036002,2,BG,321958,0
152777,THEFT,23F-THEFT FROM MOTOR VEHICLE,POINT (-84.389 39.163),639,39,061,005500,1,1500000US390610055001,390610055001,1,BG,453232,0
152778,THEFT,23F-THEFT FROM MOTOR VEHICLE,POINT (-84.459 39.14),5561,39,061,004000,1,1500000US390610040001,390610040001,1,BG,585282,0
152790,THEFT,23H-ALL OTHER LARCENY,POINT (-84.386 39.092),2730,39,061,004602,1,1500000US390610046021,390610046021,1,BG,1540646,0

In [32]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US390610080001    319
1500000US390610102013    294
1500000US390610054001    285
1500000US390610100041    283
1500000US390610265002    241
                        ...
1500000US390610204015      1
1500000US390610252005      1
1500000US390610258002      1
1500000US390610238004      1
1500000US390610242002      1
Name: count, Length: 325, dtype: int64

In [34]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cinci_All_Crime_BG.csv')

In [35]:
result2 = result[result['OFFENSE'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US390610095003    36
1500000US390610082012    35
1500000US390610094001    35
1500000US390610080001    31
1500000US390610007002    28
                         ..
1500000US390610057022     1
1500000US390610056002     1
1500000US390610050004     1
1500000US390610272003     1
1500000US390610027001     1
Name: count, Length: 215, dtype: int64

In [36]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cinci_Violent_Crime_BG.csv')

In [37]:
result3 = result[result['OFFENSE'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US390610080001    303
1500000US390610102013    292
1500000US390610054001    284
1500000US390610100041    280
1500000US390610265002    231
                        ...
1500000US390610204015      1
1500000US390610252005      1
1500000US390610219001      1
1500000US390610242002      1
1500000US390610213043      1
Name: count, Length: 325, dtype: int64

In [38]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cinci_Property_Crime_BG.csv')

In [39]:
result4 = result[result['THEFT_CODE'].isin(['24O-MOTOR VEHICLE THEFT'])]
crime = result4['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US390610080001    33
1500000US390610265002    23
1500000US390610026001    19
1500000US390610025001    18
1500000US390610094001    17
                         ..
1500000US390610271001     1
1500000US390610056003     1
1500000US390610099013     1
1500000US390610060003     1
1500000US390610040001     1
Name: count, Length: 270, dtype: int64

In [40]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cinci_MV_Crime_BG.csv')