In [87]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [89]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(320928, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,06/14/2016 01:20:00 AM,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,12/13/2016 05:00:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,07/19/2020 03:09:00 AM,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,11/17/2014 08:08:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,04/20/2015 10:22:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [90]:
dfCrime['Incident Datetime'] = pd.to_datetime(dfCrime['Incident Datetime'])
dfCrime.head()

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,2016-06-14 01:20:00,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,2016-12-13 05:00:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,2020-07-19 03:09:00,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,2014-11-17 08:08:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,2015-04-20 10:22:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [91]:
dfCrime = dfCrime.loc[(dfCrime['Incident Datetime'] >= '2019-01-01') & (dfCrime['Incident Datetime'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(13672, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
7601,19-0140161,2019-01-13 22:30:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,22,Sunday,MAIN ST & CHURCH ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
7635,19-0230400,2019-01-23 00:00:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,0,Wednesday,200 Block LESLIE ST,Buffalo,...,1,1007,36,1,1010,District E,003600,36029003600,360290001101,360290025021007
10699,19-0420162,2019-02-11 07:19:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,7,Monday,MERCER AV & S PARK AV,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
13801,19-2580750,2019-09-15 17:10:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,17,Sunday,CHELTONHAM PW & DELAWARE AV,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
130455,19-2160973,2019-08-04 14:00:00,NaN,BURGLARY,Buffalo Police are investigating this report o...,Breaking & Entering,14,Sunday,1 Block KRAKOW ST,Buffalo,...,3,3021,167,3,3028,District A,016700,36029016700,360290001103,360290163003021

In [92]:
list(dfCrime.columns)

['Case Number',
 'Incident Datetime',
 'Incident ID',
 'Incident Type Primary',
 'Incident Description',
 'Parent Incident Type',
 'Hour of Day',
 'Day of Week',
 'Address',
 'City',
 'State',
 'Location',
 'Latitude',
 'Longitude',
 'Created At',
 'updated_at',
 'zip_code',
 'neighborhood',
 'Council District',
 'Council District 2011',
 'Census Tract',
 'Census Block Group',
 'Census Block',
 '2010 Census Tract ',
 '2010 Census Block Group',
 '2010 Census Block',
 'Police District',
 'TRACTCE20',
 'GEOID20_tract',
 'GEOID20_blockgroup',
 'GEOID20_block']

In [93]:
sorted(list(dfCrime['Parent Incident Type'].unique()))

['Assault',
 'Breaking & Entering',
 'Homicide',
 'Other Sexual Offense',
 'Robbery',
 'Sexual Assault',
 'Sexual Offense',
 'Theft',
 'Theft of Vehicle']

In [94]:
dfCrime = dfCrime[['Incident Type Primary', 'Parent Incident Type', 'Longitude', 'Latitude']]
dfCrime = dfCrime[dfCrime['Longitude'] != 'UNKNOWN']
dfCrime = dfCrime[dfCrime['Incident Type Primary'] != 'ASSAULT']
dfCrime.head()

       Incident Type Primary Parent Incident Type Longitude Latitude
7635           LARCENY/THEFT                Theft   -78.818   42.916
130455              BURGLARY  Breaking & Entering   -78.809   42.872
130474         LARCENY/THEFT                Theft   -78.901   42.949
130561              BURGLARY  Breaking & Entering   -78.901   42.938
130567         LARCENY/THEFT                Theft   -78.907   42.959

In [95]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Type Primary', 'Parent Incident Type', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(10443, 3)

       Incident Type Primary Parent Incident Type                geometry
7635           LARCENY/THEFT                Theft  POINT (-78.818 42.916)
130455              BURGLARY  Breaking & Entering  POINT (-78.809 42.872)
130474         LARCENY/THEFT                Theft  POINT (-78.901 42.949)
130561              BURGLARY  Breaking & Entering  POINT (-78.901 42.938)
130567         LARCENY/THEFT                Theft  POINT (-78.907 42.959)

In [97]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_36_bg_500k/cb_2018_36_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(15406, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,36,103,110401,1,1500000US361031104011,361031104011,1,BG,534139,0,"POLYGON ((-73.399 40.904, -73.394 40.904, -73...."
1,36,119,005600,1,1500000US361190056001,361190056001,1,BG,312476,180612,"POLYGON ((-73.773 40.885, -73.772 40.887, -73...."
2,36,067,011402,3,1500000US360670114023,360670114023,3,BG,45275086,887109,"POLYGON ((-76.479 43.228, -76.451 43.229, -76...."
3,36,069,051400,2,1500000US360690514002,360690514002,2,BG,46193661,0,"POLYGON ((-77.131 42.861, -77.121 42.861, -77...."
4,36,061,018600,2,1500000US360610186002,360610186002,2,BG,48762,0,"POLYGON ((-73.952 40.799, -73.95 40.799, -73.9..."

In [98]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident Type Primary Parent Incident Type                geometry
7635           LARCENY/THEFT                Theft  POINT (-78.818 42.916)
130455              BURGLARY  Breaking & Entering  POINT (-78.809 42.872)
130474         LARCENY/THEFT                Theft  POINT (-78.901 42.949)
130561              BURGLARY  Breaking & Entering  POINT (-78.901 42.938)
130567         LARCENY/THEFT                Theft  POINT (-78.907 42.959)

In [99]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(10443, 14)

,Incident Type Primary,Parent Incident Type,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
7635,LARCENY/THEFT,Theft,POINT (-78.818 42.916),12899.0,36,029,003600,1,1500000US360290036001,360290036001,1,BG,427669.0,0.0
130455,BURGLARY,Breaking & Entering,POINT (-78.809 42.872),5280.0,36,029,016700,3,1500000US360290167003,360290167003,3,BG,1544415.0,0.0
130474,LARCENY/THEFT,Theft,POINT (-78.901 42.949),382.0,36,029,005700,2,1500000US360290057002,360290057002,2,BG,251804.0,0.0
130561,BURGLARY,Breaking & Entering,POINT (-78.901 42.938),15040.0,36,029,005900,4,1500000US360290059004,360290059004,4,BG,122062.0,0.0
130567,LARCENY/THEFT,Theft,POINT (-78.907 42.959),2596.0,36,029,005801,3,1500000US360290058013,360290058013,3,BG,108804.0,0.0

In [105]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    460
1500000US360290050003    233
1500000US360290050001    138
1500000US360290164001    116
1500000US360290042001    106
                        ...
1500000US360290084002      1
1500000US360290088003      1
1500000US360290087002      1
1500000US360290084003      1
1500000US360290080033      1
Name: count, Length: 300, dtype: int64

In [109]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_All_Crime_BG.csv')

In [113]:
violentCrimes = ['AGGR ASSAULT', 'RAPE', 'MURDER', 'SEXUAL ABUSE', 'ROBBERY']
result2 = result[result['Incident Type Primary'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    51
1500000US360290034002    24
1500000US360290024001    17
1500000US360290038003    16
1500000US360290017001    15
                         ..
1500000US360290053002     1
1500000US360290088003     1
1500000US360290067013     1
1500000US360290033021     1
1500000US360290054002     1
Name: count, Length: 256, dtype: int64

In [115]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_Violent_Crime_BG.csv')

In [117]:
propCrimes = ['BURGLARY', 'LARCENY/THEFT', 'THEFT OF SERVICES', 'UUV']
result3 = result[result['Incident Type Primary'].isin(propCrimes)]
crime = result3['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    408
1500000US360290050003    224
1500000US360290050001    128
1500000US360290164001    109
1500000US360290042001     99
                        ...
1500000US360290102022      1
1500000US360290084002      1
1500000US360290087002      1
1500000US360290084003      1
1500000US360290080033      1
Name: count, Length: 299, dtype: int64

In [119]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_Property_Crime_BG.csv')

In [121]:
propCrimes = ['Theft of Vehicle']
result4 = result[result['Parent Incident Type'].isin(propCrimes)]
crime = result4['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    30
1500000US360290028003    14
1500000US360290171005    13
1500000US360290068002    13
1500000US360290030002    12
                         ..
1500000US360290052013     1
1500000US360290055001     1
1500000US360290053001     1
1500000US360290014023     1
1500000US360290030001     1
Name: count, Length: 256, dtype: int64

In [123]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_MV_Crime_BG.csv')