In [31]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [33]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Police_Department_Incident_Reports__2018_to_Present_20250412.csv')
print(dfCrime.shape)
dfCrime.head()

(947910, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023,Wednesday,2023/03/11 04:55:00 PM,125378606372,1253786,236046123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/11 03:00:00 PM,2023/03/11,15:00,2023,Saturday,2023/03/13 08:29:00 AM,125420606244,1254206,236045937,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(896213, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
6,2022/06/27 12:00:00 PM,2022/06/27,12:00,2022,Monday,2023/03/15 05:20:00 PM,125439371000,1254393,230184129,230742480.0,...,-122.408227,POINT (-122.40822672700406 37.78735926098589),19.0,NaN,1.0,NaN,NaN,NaN,3.0,6.0
8,2023/03/16 05:30:00 PM,2023/03/16,17:30,2023,Thursday,2023/03/16 06:02:00 PM,125482604134,1254826,230187101,230752550.0,...,-122.401324,POINT (-122.40132418490647 37.76228996810526),54.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
26,2023/03/21 03:50:00 PM,2023/03/21,15:50,2023,Tuesday,2023/03/21 04:01:00 PM,125656351040,1256563,230199764,230802198.0,...,-122.418271,POINT (-122.41827098126804 37.787037946181535),50.0,NaN,NaN,NaN,NaN,NaN,10.0,6.0
144,2021/07/03 12:00:00 PM,2021/07/03,12:00,2021,Saturday,2021/07/03 12:37:00 PM,104624471000,1046244,210417332,211841413.0,...,-122.446610,POINT (-122.44660957715965 37.801787342426636),17.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
145,2021/07/22 07:16:00 PM,2021/07/22,19:16,2021,Thursday,2021/07/23 01:35:00 PM,105341571000,1053415,216098495,NaN,...,-122.394829,POINT (-122.39482876133759 37.76524759917852),54.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0

In [35]:
dfCrime = dfCrime[dfCrime['Incident Year'] == 2019]
print(dfCrime.shape)
dfCrime.head()

(138391, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019,Tuesday,2021/06/05 05:17:00 AM,103770002004,1037700,210348157,211560467.0,...,-122.408846,POINT (-122.40884575063417 37.775953228502786),32.0,NaN,NaN,1.0,1.0,NaN,10.0,1.0
790,2019/06/01 12:00:00 AM,2019/06/01,00:00,2019,Saturday,2022/03/29 10:45:00 AM,113536668030,1135366,220204947,220881074.0,...,-122.391434,POINT (-122.39143433652146 37.773466920607476),34.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0
3841,2019/04/01 12:00:00 AM,2019/04/01,00:00,2019,Monday,2023/02/06 12:36:00 PM,125811771000,1258117,236054370,NaN,...,-122.415291,POINT (-122.41529083617453 37.71350427378473),75.0,NaN,NaN,NaN,NaN,NaN,9.0,9.0
6261,2019/07/26 08:00:00 AM,2019/07/26,08:00,2019,Friday,2023/08/31 01:50:00 PM,131347507026,1313475,230622395,232430739.0,...,-122.404306,POINT (-122.40430629342 37.74252073319404),82.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
6428,2019/02/06 06:00:00 PM,2019/02/06,18:00,2019,Wednesday,2023/02/10 03:32:00 PM,125982406372,1259824,236024323,NaN,...,-122.416401,POINT (-122.41640107183976 37.777722750028566),21.0,NaN,1.0,1.0,1.0,NaN,10.0,5.0

In [36]:
list(dfCrime['Incident Subcategory'].unique())

['Rape',
 'Courtesy Report',
 'Lost Property',
 'Motor Vehicle Theft',
 'Larceny Theft - Other',
 'Missing Adult',
 'Miscellaneous Investigation',
 'Simple Assault',
 'Case Closure',
 'Fraud',
 'Non-Criminal',
 'Suspicious Occ',
 'Other',
 'Larceny - From Vehicle',
 'Larceny Theft - Shoplifting',
 'Embezzlement',
 'Forgery And Counterfeiting',
 'Stolen Property',
 'Robbery - Other',
 'Larceny Theft - From Building',
 'Aggravated Assault',
 'Vandalism',
 'Sex Offense',
 'Recovered Vehicle',
 nan,
 'Disorderly Conduct',
 'Arson',
 'Trespass',
 'Drug Violation',
 'Intimidation',
 'Missing Person',
 'Theft From Vehicle',
 'Suicide',
 'Burglary - Commercial',
 'Weapons Offense',
 'Stalking',
 'Burglary - Residential',
 'Robbery - Commercial',
 'Burglary - Other',
 'Traffic Collision',
 'Warrant',
 'Traffic Collision - Hit & Run',
 'Traffic Violation Arrest',
 'Larceny Theft - Pickpocket',
 'Robbery - Carjacking',
 'Other Offenses',
 'Prostitution',
 'Burglary - Hot Prowl',
 'Loitering',
 'Extortion-Blackmail',
 'Bribery',
 'Robbery - Street',
 'Larceny Theft - Bicycle',
 'Drunkenness',
 'Vehicle Misplaced',
 'Larceny - Auto Parts',
 'Kidnapping',
 'Vehicle Impounded',
 'Larceny Theft - Purse Snatch',
 'Fire Report',
 'Rape - Attempted',
 'Human Trafficking, Commercial Sex Acts',
 'Liquor Law Violation',
 'Motor Vehicle Theft (Attempted)',
 'Gambling',
 'Bad Checks',
 'Suspicious Package',
 'Manslaughter',
 'Robbery - Residential',
 'Arrest',
 'Homicide']

In [37]:
violentCrimes = ['Aggravated Assault', 'Rape - Attempted', 'Robbery - Residential', 'Robbery - Street', 'Robbery - Carjacking',
                'Sex Offense', 'Robbery - Commercial', 'Rape', 'Homicide', 'Robbery - Other']
propertyCrimes = ['Motor Vehicle Theft', 'Larceny Theft - Other', 'Larceny - From Vehicle', 'Larceny Theft - Shoplifting',
                  'Larceny Theft - From Building', 'Theft From Vehicle', 'Burglary - Commercial', 'Burglary - Residential',
                  'Burglary - Other', 'Larceny Theft - Pickpocket', 'Burglary - Hot Prowl', 'Larceny Theft - Bicycle', 
                  'Larceny - Auto Parts', 'Larceny Theft - Purse Snatch', 'Motor Vehicle Theft (Attempted)']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['Incident Subcategory'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(61940, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019,Tuesday,2021/06/05 05:17:00 AM,103770002004,1037700,210348157,211560467.0,...,-122.408846,POINT (-122.40884575063417 37.775953228502786),32.0,NaN,NaN,1.0,1.0,NaN,10.0,1.0
6261,2019/07/26 08:00:00 AM,2019/07/26,08:00,2019,Friday,2023/08/31 01:50:00 PM,131347507026,1313475,230622395,232430739.0,...,-122.404306,POINT (-122.40430629342 37.74252073319404),82.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
6428,2019/02/06 06:00:00 PM,2019/02/06,18:00,2019,Wednesday,2023/02/10 03:32:00 PM,125982406372,1259824,236024323,NaN,...,-122.416401,POINT (-122.41640107183976 37.777722750028566),21.0,NaN,1.0,1.0,1.0,NaN,10.0,5.0
21467,2019/05/05 12:00:00 AM,2019/05/05,00:00,2019,Sunday,2024/09/05 05:35:00 PM,142153502020,1421535,240559352,242492705.0,...,-122.481178,POINT (-122.4811782836914 37.74468231201172),40.0,NaN,NaN,NaN,NaN,NaN,7.0,10.0
22674,2019/07/14 04:00:00 PM,2019/07/14,16:00,2019,Sunday,2023/09/12 03:08:00 PM,131767806241,1317678,230654172,232552082.0,...,-122.408709,POINT (-122.4087086749172 37.780971182329765),32.0,NaN,1.0,1.0,1.0,NaN,10.0,1.0

In [38]:
dfCrime = dfCrime[['Incident Subcategory', 'Longitude', 'Latitude']]
dfCrime.head()

         Incident Subcategory   Longitude   Latitude
200                      Rape -122.408846  37.775953
6261      Motor Vehicle Theft -122.404306  37.742521
6428    Larceny Theft - Other -122.416401  37.777723
21467                    Rape -122.481178  37.744682
22674  Larceny - From Vehicle -122.408709  37.780971

In [39]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Subcategory', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(61940, 2)

         Incident Subcategory                                      geometry
200                      Rape  POINT (-122.4088457506342 37.77595322850279)
6261      Motor Vehicle Theft    POINT (-122.40430629342 37.74252073319404)
6428    Larceny Theft - Other  POINT (-122.4164010718398 37.77772275002857)
21467                    Rape  POINT (-122.4811782836914 37.74468231201172)
22674  Larceny - From Vehicle  POINT (-122.4087086749172 37.78097118232976)

In [40]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [41]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

         Incident Subcategory                geometry
200                      Rape  POINT (-122.41 37.776)
6261      Motor Vehicle Theft   POINT (-122.4 37.743)
6428    Larceny Theft - Other  POINT (-122.42 37.778)
21467                    Rape  POINT (-122.48 37.745)
22674  Larceny - From Vehicle  POINT (-122.41 37.781)

In [42]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(61940, 13)

,Incident Subcategory,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
200,Rape,POINT (-122.41 37.776),11436,06,075,017802,1,1500000US060750178021,060750178021,1,BG,320288,0
6261,Motor Vehicle Theft,POINT (-122.4 37.743),15447,06,075,980900,1,1500000US060759809001,060759809001,1,BG,3585240,260707
6428,Larceny Theft - Other,POINT (-122.42 37.778),19117,06,075,012402,2,1500000US060750124022,060750124022,2,BG,196307,0
21467,Rape,POINT (-122.48 37.745),6835,06,075,032801,3,1500000US060750328013,060750328013,3,BG,235236,0
22674,Larceny - From Vehicle,POINT (-122.41 37.781),22418,06,075,017601,5,1500000US060750176015,060750176015,5,BG,83211,0

In [43]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750117002    2394
1500000US060750615001    1673
1500000US060750101001    1300
1500000US060750102001     925
1500000US060759803001     894
                         ...
1500000US060750478021       5
1500000US060816004012       4
1500000US060750477023       3
1500000US060816009001       2
1500000US060816007001       1
Name: count, Length: 582, dtype: int64

In [44]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_All_Crime_BG.csv')

In [45]:
result2 = result[result['Incident Subcategory'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750117002    205
1500000US060750615001    200
1500000US060750176015    178
1500000US060750125012    138
1500000US060750176013    123
                        ...
1500000US060750478023      1
1500000US060750352013      1
1500000US060750328022      1
1500000US060750326012      1
1500000US060750168023      1
Name: count, Length: 486, dtype: int64

In [46]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_Violent_Crime_BG.csv')

In [47]:
result3 = result[result['Incident Subcategory'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750117002    2189
1500000US060750615001    1473
1500000US060750101001    1247
1500000US060750102001     895
1500000US060759803001     859
                         ...
1500000US060816002001       4
1500000US060816004012       4
1500000US060750477023       3
1500000US060816009001       2
1500000US060816007001       1
Name: count, Length: 582, dtype: int64

In [48]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_Property_Crime_BG.csv')

In [49]:
result4 = result[result['Incident Subcategory'].isin(['Motor Vehicle Theft', 'Motor Vehicle Theft (Attempted)'])]
crime = result4['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060759809001    121
1500000US060750180002     89
1500000US060750615001     61
1500000US060750607001     59
1500000US060750230011     58
                        ...
1500000US060750326013      1
1500000US060750129012      1
1500000US060750306003      1
1500000US060750328021      1
1500000US060750479013      1
Name: count, Length: 562, dtype: int64

In [50]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_MV_Crime_BG.csv')