In [52]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [54]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/tmp6w6ts2d7.csv')
print(dfCrime.shape)
dfCrime.head()

(87184, 17)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_14218/2964803215.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/tmp6w6ts2d7.csv')

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,192017144,3201,NaN,PROPERTY - LOST,D4,167,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,HARRISON AVE,42.334961,-71.075126,"(42.33496089, -71.07512604)"
1,192001553,3201,NaN,PROPERTY - LOST,D4,128,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,STANHOPE ST,42.348689,-71.072580,"(42.34868906, -71.07257996)"
2,192000804,2629,NaN,HARASSMENT,B3,417,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,MORA ST,42.282082,-71.073649,"(42.28208187, -71.07364878)"
3,192065160,619,NaN,LARCENY ALL OTHERS,NaN,,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,BSTN MA,NaN,NaN,NaN
4,192007583,2647,NaN,THREATS TO DO BODILY HARM,C11,393,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,FLORIDA ST,42.287877,-71.058397,"(42.28787659, -71.05839667)"

In [56]:
sorted(list(dfCrime['OFFENSE_DESCRIPTION'].unique()))

['AFFRAY',
 'AIRCRAFT INCIDENTS',
 'ANIMAL ABUSE',
 'ANIMAL CONTROL - DOG BITES - ETC.',
 'ANIMAL INCIDENTS',
 'ANIMAL INCIDENTS (DOG BITES, LOST DOG, ETC)',
 'ANNOYING AND ACCOSTING',
 'ARSON',
 'ASSAULT - AGGRAVATED',
 'ASSAULT - AGGRAVATED - BATTERY',
 'ASSAULT - SIMPLE',
 'ASSAULT SIMPLE - BATTERY',
 'AUTO THEFT',
 'AUTO THEFT - LEASED/RENTED VEHICLE',
 'AUTO THEFT - MOTORCYCLE / SCOOTER',
 'BALLISTICS EVIDENCE/FOUND',
 'BIOLOGICAL THREATS',
 'BOMB THREAT',
 'BREAKING AND ENTERING (B&E) MOTOR VEHICLE',
 'BREAKING AND ENTERING (B&E) MOTOR VEHICLE (NO PROPERTY STOLEN)',
 'BURGLARY - COMMERICAL',
 'BURGLARY - COMMERICAL - ATTEMPT',
 'BURGLARY - COMMERICAL - FORCE',
 'BURGLARY - COMMERICAL - NO FORCE',
 'BURGLARY - OTHER - ATTEMPT',
 'BURGLARY - OTHER - FORCE',
 'BURGLARY - OTHER - NO FORCE',
 'BURGLARY - RESIDENTIAL',
 'BURGLARY - RESIDENTIAL - ATTEMPT',
 'BURGLARY - RESIDENTIAL - FORCE',
 'BURGLARY - RESIDENTIAL - NO FORCE',
 'CHILD REQUIRING ASSISTANCE (FOMERLY CHINS)',
 'CHINS',
 'CONSPIRACY EXCEPT DRUG LAW',
 'CRIMINAL HARASSMENT',
 'DANGEROUS OR HAZARDOUS CONDITION',
 'DEATH INVESTIGATION',
 'DEMONSTRATIONS/RIOT',
 'DISORDERLY CONDUCT',
 'DISTURBING THE PEACE',
 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
 'DRUGS - CLASS A TRAFFICKING OVER 18 GRAMS',
 'DRUGS - CLASS B TRAFFICKING OVER 18 GRAMS',
 'DRUGS - CLASS D TRAFFICKING OVER 50 GRAMS',
 'DRUGS - CONSP TO VIOL CONTROLLED SUBSTANCE',
 'DRUGS - OTHER',
 'DRUGS - POSS CLASS A - HEROIN, ETC. ',
 'DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP',
 'DRUGS - POSS CLASS B - COCAINE, ETC.',
 'DRUGS - POSS CLASS B - INTENT TO MFR DIST DISP',
 'DRUGS - POSS CLASS C',
 'DRUGS - POSS CLASS C - INTENT TO MFR DIST DISP',
 'DRUGS - POSS CLASS D',
 'DRUGS - POSS CLASS D - INTENT TO MFR DIST DISP',
 'DRUGS - POSS CLASS E',
 'DRUGS - POSS CLASS E - INTENT TO MFR DIST DISP',
 'DRUGS - POSSESSION',
 'DRUGS - POSSESSION OF DRUG PARAPHANALIA',
 'DRUGS - POSSESSION/ SALE/ MANUFACTURING/ USE',
 'DRUGS - SALE / MANUFACTURING',
 'DRUGS - SICK ASSIST - HEROIN',
 'DRUGS - SICK ASSIST - OTHER HARMFUL DRUG',
 'DRUGS - SICK ASSIST - OTHER NARCOTIC',
 'DRUNKENNESS',
 'EMBEZZLEMENT',
 'EVADING FARE',
 'EXPLOSIVES - POSSESSION OR USE',
 'EXPLOSIVES - TURNED IN OR FOUND',
 'EXTORTION OR BLACKMAIL',
 'FIRE REPORT',
 'FIRE REPORT - CAR, BRUSH, ETC.',
 'FIRE REPORT - HOUSE, BUILDING, ETC.',
 'FIRE REPORT/ALARM - FALSE',
 'FIREARM/WEAPON - ACCIDENTAL INJURY / DEATH',
 'FIREARM/WEAPON - FOUND OR CONFISCATED',
 'FIREARM/WEAPON - LOST',
 'FORGERY / COUNTERFEITING',
 'FRAUD - CREDIT CARD / ATM FRAUD',
 'FRAUD - FALSE PRETENSE / SCHEME',
 'FRAUD - IMPERSONATION',
 'FRAUD - WELFARE',
 'FRAUD - WIRE',
 'FUGITIVE FROM JUSTICE',
 'GRAFFITI',
 'HARASSMENT',
 'HARASSMENT/ CRIMINAL HARASSMENT',
 'HARBOR INCIDENT / VIOLATION',
 'HOME INVASION',
 'INJURY BICYCLE NO M/V INVOLVED',
 'INTIMIDATING WITNESS',
 'INVESTIGATE PERSON',
 'INVESTIGATE PROPERTY',
 'INVESTIGATION FOR ANOTHER AGENCY',
 'KIDNAPPING - ENTICING OR ATTEMPTED',
 'KIDNAPPING/CUSTODIAL KIDNAPPING',
 'KIDNAPPING/CUSTODIAL KIDNAPPING/ ABDUCTION',
 'LANDLORD - TENANT',
 'LANDLORD - TENANT SERVICE',
 'LARCENY ALL OTHERS',
 'LARCENY PICK-POCKET',
 'LARCENY PURSE SNATCH - NO FORCE',
 'LARCENY PURSE SNATCH - NO FORCE ',
 'LARCENY SHOPLIFTING',
 'LARCENY THEFT FROM BUILDING',
 'LARCENY THEFT FROM COIN-OP MACHINE',
 'LARCENY THEFT FROM MV - NON-ACCESSORY',
 'LARCENY THEFT OF BICYCLE',
 'LARCENY THEFT OF MV PARTS & ACCESSORIES',
 'LICENSE PREMISE VIOLATION',
 'LIQUOR - DRINKING IN PUBLIC',
 'LIQUOR LAW VIOLATION',
 'LIQUOR/ALCOHOL - DRINKING IN PUBLIC',
 'M/V - LEAVING SCENE - PERSONAL INJURY',
 'M/V - LEAVING SCENE - PROPERTY DAMAGE',
 'M/V ACCIDENT - INVOLVING BICYCLE - INJURY',
 'M/V ACCIDENT - INVOLVING BICYCLE - NO INJURY',
 'M/V ACCIDENT - INVOLVING PEDESTRIAN - INJURY',
 'M/V ACCIDENT - INVOLVING PEDESTRIAN - NO INJURY',
 'M/V ACCIDENT - INVOLVING \xa0BICYCLE - INJURY',
 'M/V ACCIDENT - OTHER',
 'M/V ACCIDENT - OTHER CITY VEHICLE',
 'M/V ACCIDENT - PERSONAL INJURY',
 'M/V ACCIDENT - POLICE VEHICLE',
 'M/V ACCIDENT - PROPERTY DAMAGE',
 'M/V ACCIDENT - PROPERTY \xa0DAMAGE',
 'M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY',
 'M/V PLATES - LOST',
 'MANSLAUGHTER - VEHICLE - NEGLIGENCE',
 'MISSING PERSON',
 'MISSING PERSON - LOCATED',
 'MISSING PERSON - NOT REPORTED - LOCATED',
 'MURDER, NON-NEGLIGIENT MANSLAUGHTER',
 'Migrated Report - Affray/Disturbing the Peace/Disorderly Conduct',
 'Migrated Report - Aggravated Assault/Aggravated Assault & Battery',
 'Migrated Report - Assault/Assault & Battery',
 'Migrated Report - Auto Law Violation',
 'Migrated Report - Auto Theft',
 'Migrated Report - Burglary/Breaking and Entering',
 'Migrated Report - Counterfeiting/Forgery',
 'Migrated Report - Criminal Homicide',
 'Migrated Report - Death Investigation',
 'Migrated Report - Drugs - Possession/Manufacturing/Distribute',
 'Migrated Report - Embezzlement',
 'Migrated Report - Fraud',
 'Migrated Report - Injured/Medical/Sick Assist',
 'Migrated Report - Investigate Person',
 'Migrated Report - Investigate Property',
 'Migrated Report - Kidnapping',
 'Migrated Report - Larceny From MV',
 'Migrated Report - Motor Vehicle Crash',
 'Migrated Report - Other Larceny',
 'Migrated Report - Other Part II',
 'Migrated Report - Other Part III',
 'Migrated Report - Robbery',
 'Migrated Report - Stolen Property',
 'Migrated Report - Vandalism/Destruction of Property',
 'Migrated Report - Weapons Violation',
 'NOISY PARTY/RADIO-ARREST',
 'NOISY PARTY/RADIO-NO ARREST',
 'OBSCENE PHONE CALLS',
 'OPERATING UNDER THE INFLUENCE (OUI) ALCOHOL',
 'OPERATING UNDER THE INFLUENCE (OUI) DRUGS',
 'OPERATING UNDER THE INFLUENCE ALCOHOL',
 'OPERATING UNDER THE INFLUENCE DRUGS',
 'OTHER OFFENSE',
 'POSSESSION OF BURGLARIOUS TOOLS',
 'PRISONER - SUICIDE / SUICIDE ATTEMPT',
 'PROPERTY - ACCIDENTAL DAMAGE',
 'PROPERTY - CONCEALING LEASED',
 'PROPERTY - FOUND',
 'PROPERTY - LOST',
 'PROPERTY - LOST THEN LOCATED',
 'PROPERTY - LOST/ MISSING',
 'PROPERTY - MISSING',
 'PROPERTY - STOLEN THEN RECOVERED',
 'PROSTITUTION',
 'PROSTITUTION - ASSISTING OR PROMOTING',
 'PROSTITUTION - SOLICITING',
 'PROTECTIVE CUSTODY / SAFEKEEPING',
 'RECOVERED - MV RECOVERED IN BOSTON (STOLEN IN BOSTON) MUST BE SUPPLEMENTAL',
 'RECOVERED - MV RECOVERED IN BOSTON (STOLEN OUTSIDE BOSTON)',
 'RECOVERED STOLEN PLATE',
 'REPORT AFFECTING OTHER DEPTS.',
 'ROBBERY',
 'ROBBERY - BANK',
 'ROBBERY - CAR JACKING',
 'ROBBERY - COMMERCIAL',
 'ROBBERY - HOME INVASION',
 'ROBBERY - OTHER',
 'ROBBERY - STREET',
 'SEARCH WARRANT',
 'SERVICE TO OTHER AGENCY',
 'SERVICE TO OTHER PD INSIDE OF MA.',
 'SERVICE TO OTHER PD OUTSIDE OF MA.',
 'SICK ASSIST',
 'SICK ASSIST - DRUG RELATED ILLNESS',
 'SICK/INJURED/MEDICAL - PERSON',
 'SICK/INJURED/MEDICAL - POLICE',
 'STOLEN PROPERTY - BUYING / RECEIVING / POSSESSING',
 'SUDDEN DEATH',
 'SUICIDE / SUICIDE ATTEMPT',
 'THREATS TO DO BODILY HARM',
 'TOWED MOTOR VEHICLE',
 'TRESPASSING',
 'TRUANCY / RUNAWAY',
 'VAL - OPERATING AFTER REV/SUSP.',
 'VAL - OPERATING UNREG/UNINS \xa0CAR',
 'VAL - OPERATING W/O AUTHORIZATION LAWFUL',
 'VAL - OPERATING WITHOUT LICENSE',
 'VAL - VIOLATION OF AUTO LAW',
 'VAL - VIOLATION OF AUTO LAW - OTHER',
 'VANDALISM',
 'VERBAL DISPUTE',
 'VIOLATION - CITY ORDINANCE',
 'VIOLATION - HAWKER AND PEDDLER',
 'WARRANT ARREST',
 'WARRANT ARREST - BOSTON WARRANT (MUST BE SUPPLEMENTAL)',
 'WARRANT ARREST - OUTSIDE OF BOSTON WARRANT',
 'WEAPON - FIREARM - CARRYING / POSSESSING, ETC',
 'WEAPON - FIREARM - OTHER VIOLATION',
 'WEAPON - FIREARM - SALE / TRAFFICKING',
 'WEAPON - OTHER - CARRYING / POSSESSING, ETC',
 'WEAPON - OTHER - OTHER VIOLATION',
 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER']

In [58]:
violentCrimes = ['ASSAULT - AGGRAVATED', 'ASSAULT - AGGRAVATED - BATTERY', 'MURDER, NON-NEGLIGIENT MANSLAUGHTER',
                'ROBBERY - BANK', 'ROBBERY - CAR JACKING', 'ROBBERY - COMMERCIAL', 'ROBBERY - HOME INVASION', 'ROBBERY - OTHER',
                'ROBBERY - STREET', 'ROBBERY - UNARMED - CHAIN STORE']
propertyCrimes = ['AUTO THEFT', 'AUTO THEFT - LEASED/RENTED VEHICLE', 'AUTO THEFT - MOTORCYCLE / SCOOTER', 'BURGLARY - COMMERICAL',
                  'BURGLARY - COMMERICAL - ATTEMPT', 'BURGLARY - COMMERICAL - FORCE', 'BURGLARY - COMMERICAL - NO FORCE',
                  'BURGLARY - OTHER - ATTEMPT', 'BURGLARY - OTHER - FORCE', 'BURGLARY - OTHER - NO FORCE', 'BURGLARY - RESIDENTIAL',
                  'BURGLARY - RESIDENTIAL - ATTEMPT', 'BURGLARY - RESIDENTIAL - FORCE', 'BURGLARY - RESIDENTIAL - NO FORCE', 'LARCENY ALL OTHERS',
                  'LARCENY PICK-POCKET', 'LARCENY PURSE SNATCH - NO FORCE', 'LARCENY PURSE SNATCH - NO FORCE ', 'LARCENY SHOPLIFTING',
                  'LARCENY THEFT FROM BUILDING', 'LARCENY THEFT FROM COIN-OP MACHINE', 'LARCENY THEFT FROM MV - NON-ACCESSORY',
                  'LARCENY THEFT OF BICYCLE', 'LARCENY THEFT OF MV PARTS & ACCESSORIES']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['OFFENSE_DESCRIPTION'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(16174, 17)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
3,192065160,619,NaN,LARCENY ALL OTHERS,NaN,,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,BSTN MA,NaN,NaN,NaN
22,192000329,614,NaN,LARCENY THEFT FROM MV - NON-ACCESSORY,C11,345,0,2019-01-01 00:00:00,2019,1,Tuesday,0,NaN,HOMES AVE,42.303441,-71.066746,"(42.30344062, -71.06674611)"
26,192010803,617,NaN,LARCENY THEFT FROM BUILDING,D4,152,0,2019-01-01 00:01:00,2019,1,Tuesday,0,NaN,TREMONT ST,42.344959,-71.070115,"(42.34495856, -71.0701147)"
35,192000660,301,NaN,ROBBERY - STREET,C11,823,0,2019-01-01 00:30:00,2019,1,Tuesday,0,NaN,PLEASANT ST,42.311905,-71.059105,"(42.31190464, -71.05910535)"
43,192000171,614,NaN,LARCENY THEFT FROM MV - NON-ACCESSORY,C6,203,0,2019-01-01 01:00:00,2019,1,Tuesday,1,NaN,SUMMER ST,42.346548,-71.042841,"(42.34654759, -71.04284097)"

In [60]:
dfCrime = dfCrime[['OFFENSE_DESCRIPTION', 'Lat', 'Long']]
dfCrime = dfCrime[dfCrime['Lat'].isna() == False]
dfCrime = dfCrime[dfCrime['Long'].isna() == False]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Long'], row['Lat']), axis=1)
dfCrime = dfCrime[['OFFENSE_DESCRIPTION', 'geometry']]
dfCrime.head()

                      OFFENSE_DESCRIPTION                          geometry
22  LARCENY THEFT FROM MV - NON-ACCESSORY  POINT (-71.06674611 42.30344062)
26            LARCENY THEFT FROM BUILDING   POINT (-71.0701147 42.34495856)
35                       ROBBERY - STREET  POINT (-71.05910535 42.31190464)
43  LARCENY THEFT FROM MV - NON-ACCESSORY  POINT (-71.04284097 42.34654759)
44         ASSAULT - AGGRAVATED - BATTERY  POINT (-71.04499636 42.34373917)

In [61]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_25_bg_500k/cb_2018_25_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(4982, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,25,025,090901,2,1500000US250250909012,250250909012,2,BG,900600,293189,"POLYGON ((-71.051 42.321, -71.049 42.32, -71.0..."
1,25,009,203200,5,1500000US250092032005,250092032005,5,BG,814616,419184,"POLYGON ((-70.887 42.498, -70.882 42.503, -70...."
2,25,025,090700,3,1500000US250250907003,250250907003,3,BG,117677,0,"POLYGON ((-71.061 42.322, -71.061 42.322, -71...."
3,25,009,217202,3,1500000US250092172023,250092172023,3,BG,263736,59670,"POLYGON ((-70.898 42.544, -70.894 42.547, -70...."
4,25,017,339600,3,1500000US250173396003,250173396003,3,BG,134287,0,"POLYGON ((-71.115 42.402, -71.113 42.403, -71...."

In [64]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                      OFFENSE_DESCRIPTION                geometry
22  LARCENY THEFT FROM MV - NON-ACCESSORY  POINT (-71.067 42.303)
26            LARCENY THEFT FROM BUILDING   POINT (-71.07 42.345)
35                       ROBBERY - STREET  POINT (-71.059 42.312)
43  LARCENY THEFT FROM MV - NON-ACCESSORY  POINT (-71.043 42.347)
44         ASSAULT - AGGRAVATED - BATTERY  POINT (-71.045 42.344)

In [66]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(15738, 13)

,OFFENSE_DESCRIPTION,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
22,LARCENY THEFT FROM MV - NON-ACCESSORY,POINT (-71.067 42.303),785,25,025,091700,1,1500000US250250917001,250250917001,1,BG,156233,0
26,LARCENY THEFT FROM BUILDING,POINT (-71.07 42.345),1170,25,025,070500,1,1500000US250250705001,250250705001,1,BG,96256,0
35,ROBBERY - STREET,POINT (-71.059 42.312),4865,25,025,091001,1,1500000US250250910011,250250910011,1,BG,96905,0
43,LARCENY THEFT FROM MV - NON-ACCESSORY,POINT (-71.043 42.347),4015,25,025,060600,1,1500000US250250606001,250250606001,1,BG,1249224,629367
44,ASSAULT - AGGRAVATED - BATTERY,POINT (-71.045 42.344),4015,25,025,060600,1,1500000US250250606001,250250606001,1,BG,1249224,629367

In [68]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US250250106001    397
1500000US250250303003    335
1500000US250250801001    286
1500000US250250701012    260
1500000US250250303002    237
                        ...
1500000US250259816001      1
1500000US250250607002      1
1500000US250214001004      1
1500000US250250008031      1
1500000US250259811001      1
Name: count, Length: 560, dtype: int64

In [70]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Boston_All_Crime_BG.csv')

In [72]:
result2 = result[result['OFFENSE_DESCRIPTION'].isin(violentCrimes)]
print(result2.shape)
result2.head()

(2841, 13)

,OFFENSE_DESCRIPTION,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
35,ROBBERY - STREET,POINT (-71.059 42.312),4865,25,025,091001,1,1500000US250250910011,250250910011,1,BG,96905,0
44,ASSAULT - AGGRAVATED - BATTERY,POINT (-71.045 42.344),4015,25,025,060600,1,1500000US250250606001,250250606001,1,BG,1249224,629367
74,ASSAULT - AGGRAVATED - BATTERY,POINT (-71.057 42.361),3918,25,025,030300,3,1500000US250250303003,250250303003,3,BG,303247,0
83,ASSAULT - AGGRAVATED - BATTERY,POINT (-71.089 42.281),4427,25,025,101102,2,1500000US250251011022,250251011022,2,BG,160976,0
92,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",POINT (-71.092 42.288),3473,25,025,100100,5,1500000US250251001005,250251001005,5,BG,62363,0

In [74]:
crime = result2['AFFGEOID'].value_counts()

# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Boston_Violent_Crime_BG.csv')

In [76]:
result3 = result[result['OFFENSE_DESCRIPTION'].isin(propertyCrimes)]
print(result3.shape)
result3.head()

(12897, 13)

,OFFENSE_DESCRIPTION,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
22,LARCENY THEFT FROM MV - NON-ACCESSORY,POINT (-71.067 42.303),785,25,025,091700,1,1500000US250250917001,250250917001,1,BG,156233,0
26,LARCENY THEFT FROM BUILDING,POINT (-71.07 42.345),1170,25,025,070500,1,1500000US250250705001,250250705001,1,BG,96256,0
43,LARCENY THEFT FROM MV - NON-ACCESSORY,POINT (-71.043 42.347),4015,25,025,060600,1,1500000US250250606001,250250606001,1,BG,1249224,629367
88,LARCENY THEFT FROM BUILDING,POINT (-71.078 42.349),4217,25,025,010600,1,1500000US250250106001,250250106001,1,BG,250325,0
100,LARCENY THEFT FROM BUILDING,POINT (-71.041 42.374),3962,25,025,050300,1,1500000US250250503001,250250503001,1,BG,230251,271374

In [78]:
crime = result3['AFFGEOID'].value_counts()

# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Boston_Property_Crime_BG.csv')

In [80]:
result4 = result[result['OFFENSE_DESCRIPTION'].isin(['AUTO THEFT', 'AUTO THEFT - LEASED/RENTED VEHICLE', 'AUTO THEFT - MOTORCYCLE / SCOOTER'])]
print(result4.shape)
result4.head()

(1153, 13)

,OFFENSE_DESCRIPTION,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
181,AUTO THEFT - MOTORCYCLE / SCOOTER,POINT (-71.089 42.317),4980,25,025,081900,2,1500000US250250819002,250250819002,2,BG,79141,0
385,AUTO THEFT,POINT (-71.088 42.281),4034,25,025,101102,3,1500000US250251011023,250251011023,3,BG,164614,0
455,AUTO THEFT,POINT (-71.046 42.352),4015,25,025,060600,1,1500000US250250606001,250250606001,1,BG,1249224,629367
457,AUTO THEFT,POINT (-71.059 42.372),3292,25,025,040100,1,1500000US250250401001,250250401001,1,BG,137890,64873
499,AUTO THEFT,POINT (-71.068 42.31),1156,25,025,091800,1,1500000US250250918001,250250918001,1,BG,154578,0

In [82]:
crime = result4['AFFGEOID'].value_counts()

# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Boston_MV_Crime_BG.csv')