In [93]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [95]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crimes_-_2001_to_Present.csv')
print(dfCrime.shape)
dfCrime.head()

(8285876, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
4,13204489,JG416325,09/06/2023 11:00:00 AM,0000X E 8TH ST,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,4.0,32.0,06,1176857.0,1896680.0,2023,11/04/2023 03:40:18 PM,41.871835,-87.626151,"(41.871834768, -87.62615082)"

In [96]:
dfCrime.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [97]:
dfCrime = dfCrime[dfCrime['Year'] == 2019]
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(259172, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
5,11695116,JC272771,05/21/2019 08:20:00 AM,018XX S CALIFORNIA AVE,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE,False,False,...,25.0,29.0,05,1157982.0,1890961.0,2019,01/19/2024 03:40:50 PM,41.856547,-87.695605,"(41.856547057, -87.695604526)"
18,11662417,JC232642,04/21/2019 12:30:00 PM,009XX E 80TH ST,031A,ROBBERY,ARMED - HANDGUN,RESIDENCE,False,False,...,8.0,44.0,03,1184044.0,1852159.0,2019,09/14/2023 03:41:59 PM,41.749500,-87.601157,"(41.749500329, -87.6011574)"
32,12990873,JG161829,08/17/2019 01:14:00 PM,008XX N KARLOV AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,True,True,...,37.0,23.0,17,1148899.0,1905351.0,2019,09/14/2023 03:41:59 PM,41.896215,-87.728572,"(41.89621515, -87.728572048)"
847,11757563,JC348652,07/13/2019 11:30:00 PM,084XX S MACKINAW AVE,0320,ROBBERY,STRONG ARM - NO WEAPON,ALLEY,False,False,...,10.0,46.0,03,1199935.0,1849732.0,2019,04/18/2024 03:40:20 PM,41.742455,-87.543009,"(41.742454647, -87.543009205)"
879,11653698,JC222674,04/13/2019 01:30:00 AM,010XX W DIVISION ST,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,...,27.0,8.0,07,1169399.0,1908184.0,2019,12/22/2024 03:41:04 PM,41.903568,-87.653197,"(41.903567876, -87.653197209)"

In [98]:
list(dfCrime['FBI Code'].unique())

['05',
 '03',
 '17',
 '07',
 '06',
 '01A',
 '02',
 '04B',
 '15',
 '26',
 '04A',
 '08B',
 '14',
 '08A',
 '18',
 '11',
 '20',
 '10',
 '24',
 '16',
 '22',
 '09',
 '19',
 '13',
 '27',
 '12',
 '01B']

In [99]:
dfCrime[dfCrime['FBI Code'] == '07']

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
879,11653698,JC222674,04/13/2019 01:30:00 AM,010XX W DIVISION ST,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,...,27.0,8.0,07,1169399.0,1908184.0,2019,12/22/2024 03:41:04 PM,41.903568,-87.653197,"(41.903567876, -87.653197209)"
880,11778550,JC372761,07/31/2019 04:11:09 PM,077XX S SOUTH CHICAGO AVE,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,8.0,45.0,07,1187313.0,1853846.0,2019,12/22/2024 03:41:04 PM,41.754053,-87.589125,"(41.754052659, -87.58912514)"
14091,11930298,JC557661,12/21/2019 01:00:00 PM,091XX S WALLACE ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,RESIDENCE - GARAGE,False,False,...,9.0,73.0,07,1173908.0,1844269.0,2019,09/27/2023 03:42:22 PM,41.728080,-87.638533,"(41.728079819, -87.638533054)"
104755,11773785,JC368086,07/27/2019 10:00:00 AM,019XX S FAIRFIELD AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,25.0,30.0,07,1158339.0,1890385.0,2019,04/05/2024 03:40:21 PM,41.854959,-87.694310,"(41.854959168, -87.694309878)"
112804,11711806,JC291578,06/01/2019 01:00:00 AM,013XX N AUSTIN BLVD,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,RESIDENCE,True,False,...,29.0,25.0,07,1136115.0,1908366.0,2019,07/04/2019 03:41:01 PM,41.904726,-87.775454,"(41.904726365, -87.775453858)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281920,12038308,JD218196,07/22/2019 08:00:00 AM,052XX S ARCHER AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,23.0,57.0,07,1146707.0,1870103.0,2019,04/30/2020 03:40:30 PM,41.799532,-87.737521,"(41.799532089, -87.737521099)"
7309490,12100194,JD290581,10/18/2019 12:00:00 PM,066XX N WESTERN AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,50.0,2.0,07,1159115.0,1943911.0,2019,07/11/2020 03:40:30 PM,42.001822,-87.689987,"(42.001822361, -87.689987495)"
7311807,12126384,JD321375,09/09/2019 12:00:00 AM,001XX N LEAMINGTON AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,28.0,25.0,07,1142020.0,1900624.0,2019,08/08/2020 03:39:57 PM,41.883374,-87.753955,"(41.88337397, -87.753954797)"
7315760,12063076,JD246931,05/09/2019 12:00:00 AM,032XX W WABANSIA AVE,0937,MOTOR VEHICLE THEFT,"THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN",STREET,True,False,...,26.0,23.0,07,1154129.0,1911108.0,2019,06/03/2020 03:41:10 PM,41.911910,-87.709209,"(41.911910115, -87.709209328)"
7326710,12014948,JD192330,10/14/2019 03:00:00 PM,010XX N LOCKWOOD AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,37.0,25.0,07,1140837.0,1906319.0,2019,03/25/2020 03:53:41 PM,41.899024,-87.758159,"(41.899023579, -87.758158731)"

In [100]:
violentCrimeCodes = ['03', '01A', '02', '04A', '01B']
propertyCrime = ['05', '07', '06']
both = violentCrimeCodes + propertyCrime
dfCrime = dfCrime[dfCrime['FBI Code'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(96403, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
5,11695116,JC272771,05/21/2019 08:20:00 AM,018XX S CALIFORNIA AVE,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE,False,False,...,25.0,29.0,05,1157982.0,1890961.0,2019,01/19/2024 03:40:50 PM,41.856547,-87.695605,"(41.856547057, -87.695604526)"
18,11662417,JC232642,04/21/2019 12:30:00 PM,009XX E 80TH ST,031A,ROBBERY,ARMED - HANDGUN,RESIDENCE,False,False,...,8.0,44.0,03,1184044.0,1852159.0,2019,09/14/2023 03:41:59 PM,41.749500,-87.601157,"(41.749500329, -87.6011574)"
847,11757563,JC348652,07/13/2019 11:30:00 PM,084XX S MACKINAW AVE,0320,ROBBERY,STRONG ARM - NO WEAPON,ALLEY,False,False,...,10.0,46.0,03,1199935.0,1849732.0,2019,04/18/2024 03:40:20 PM,41.742455,-87.543009,"(41.742454647, -87.543009205)"
879,11653698,JC222674,04/13/2019 01:30:00 AM,010XX W DIVISION ST,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,...,27.0,8.0,07,1169399.0,1908184.0,2019,12/22/2024 03:41:04 PM,41.903568,-87.653197,"(41.903567876, -87.653197209)"
880,11778550,JC372761,07/31/2019 04:11:09 PM,077XX S SOUTH CHICAGO AVE,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,8.0,45.0,07,1187313.0,1853846.0,2019,12/22/2024 03:41:04 PM,41.754053,-87.589125,"(41.754052659, -87.58912514)"

In [101]:
dfCrime = dfCrime[['FBI Code', 'Latitude', 'Longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['FBI Code', 'geometry']]
dfCrime.head()

    FBI Code                                 geometry
5         05       POINT (-87.695604526 41.856547057)
18        03  POINT (-87.60115740000001 41.749500329)
847       03       POINT (-87.543009205 41.742454647)
879       07       POINT (-87.653197209 41.903567876)
880       07  POINT (-87.58912513999999 41.754052659)

In [102]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_17_bg_500k/cb_2018_17_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(9689, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,17,031,081202,1,1500000US170310812021,170310812021,1,BG,119267,530065,"POLYGON ((-87.624 41.902, -87.623 41.902, -87...."
1,17,031,300900,3,1500000US170313009003,170313009003,3,BG,58576,0,"POLYGON ((-87.703 41.852, -87.702 41.852, -87...."
2,17,031,806700,3,1500000US170318067003,170318067003,3,BG,402672,0,"POLYGON ((-87.732 42.055, -87.727 42.055, -87...."
3,17,031,711400,3,1500000US170317114003,170317114003,3,BG,158934,0,"POLYGON ((-87.657 41.736, -87.653 41.736, -87...."
4,17,031,040700,3,1500000US170310407003,170310407003,3,BG,99758,0,"POLYGON ((-87.698 41.967, -87.696 41.967, -87...."

In [103]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

    FBI Code                geometry
5         05  POINT (-87.696 41.857)
18        03   POINT (-87.601 41.75)
847       03  POINT (-87.543 41.742)
879       07  POINT (-87.653 41.904)
880       07  POINT (-87.589 41.754)

In [104]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(96403, 13)

,FBI Code,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
5,05,POINT (-87.696 41.857),803.0,17,031,843100,2,1500000US170318431002,170318431002,2,BG,352338.0,0.0
18,03,POINT (-87.601 41.75),51.0,17,031,440101,1,1500000US170314401011,170314401011,1,BG,145946.0,0.0
847,03,POINT (-87.543 41.742),951.0,17,031,460200,1,1500000US170314602001,170314602001,1,BG,183147.0,0.0
879,07,POINT (-87.653 41.904),3352.0,17,031,842200,1,1500000US170318422001,170318422001,1,BG,1407941.0,136789.0
880,07,POINT (-87.589 41.754),8374.0,17,031,834200,4,1500000US170318342004,170318342004,4,BG,309944.0,0.0

In [105]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US170318391001    2418
1500000US170313204001    1035
1500000US170313201002     784
1500000US170318422001     732
1500000US170313201001     721
                         ...
1500000US170318122001       1
1500000US170318076003       1
1500000US170318216005       1
1500000US170318103013       1
1500000US170318264012       1
Name: count, Length: 2243, dtype: int64

In [106]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Chicago_All_Crime_BG.csv')

In [107]:
result2 = result[result['FBI Code'].isin(violentCrimeCodes)]
crime = result2['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US170318391001    120
1500000US170318424002     89
1500000US170313204001     63
1500000US170310817002     58
1500000US170312607002     56
                        ...
1500000US170310302003      1
1500000US170311005005      1
1500000US170310207024      1
1500000US170312426004      1
1500000US170310901001      1
Name: count, Length: 2011, dtype: int64

In [108]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Chicago_Violent_Crime_BG.csv')

In [109]:
result3 = result[result['FBI Code'].isin(propertyCrime)]
crime = result3['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US170318391001    2298
1500000US170313204001     972
1500000US170313201002     737
1500000US170313201001     690
1500000US170318422001     687
                         ...
1500000US170318122001       1
1500000US170318107013       1
1500000US170310315011       1
1500000US170311703003       1
1500000US170318264012       1
Name: count, Length: 2233, dtype: int64

In [110]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Chicago_Property_Crime_BG.csv')

In [111]:
result4 = result[result['FBI Code'].isin(['07'])]
crime = result4['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US170318391001    49
1500000US170319800001    45
1500000US170310817002    42
1500000US170318424002    33
1500000US170312517001    27
                         ..
1500000US170310309004     1
1500000US170310505004     1
1500000US170316503014     1
1500000US170310404024     1
1500000US170311508005     1
Name: count, Length: 1954, dtype: int64

In [112]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Chicago_MV_Crime_BG.csv')