In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')
print(dfCrime.shape)
dfCrime.head()

(337854, 28)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_20491/3360715205.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
0,109892033,TE2013102138,8/16/2013 12:45:00 PM,2013.0,8.0,12.0,33.0,16.0,Friday,9XX E BROADWAY RD,...,C,Alameda,S,20,85282.0,4.013320e+09,NaN,NaN,697343.0,875784.0
1,109892034,TE2013104042,8/19/2013 3:44:00 PM,2013.0,8.0,15.0,34.0,19.0,Monday,HARDY DR / W UNIVERSITY DR,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,NaN,689158.0,881039.0
2,109892035,TE2013104050,8/16/2013 6:00:00 PM,2013.0,8.0,18.0,33.0,16.0,Friday,6XXX S RURAL RD,...,C,Kiwanis/The Lakes,S,21,85283.0,4.013320e+09,NaN,NaN,696260.0,861054.0
3,109892036,TE2013104316,8/20/2013 7:59:00 AM,2013.0,8.0,7.0,34.0,20.0,Tuesday,1XXX N SCOTTSDALE RD,...,C,Papago/North Tempe,N,11,85288.0,4.013318e+09,NaN,Indian Bend,697930.0,890057.0
4,109892037,TE2013105261,8/22/2013 9:37:00 AM,2013.0,8.0,9.0,34.0,22.0,Thursday,2XXX E APACHE BLVD,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,NaN,705067.0,878463.0

In [3]:
dfCrime = dfCrime[dfCrime['OccurrenceYear'] == 2019]
print(dfCrime.shape)
dfCrime.head()

(28130, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
115327,110007360,TE201991655,8/5/2019 6:00:00 PM,2019.0,8.0,18.0,32.0,5.0,Monday,1XXX S MILL AVE,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,NaN,692778.0,877476.0
115787,110007820,TE201991748,8/5/2019 11:20:00 PM,2019.0,8.0,23.0,32.0,5.0,Monday,3XXX S PRIEST DR,...,C,Alameda,S,19,85282.0,4.013320e+09,NaN,NaN,686612.0,869148.0
116161,110008194,TE201989347,7/31/2019 12:15:00 PM,2019.0,7.0,12.0,31.0,31.0,Wednesday,1XXX E BROADWAY RD,...,C,Alameda,N,14,85282.0,4.013319e+09,NaN,NaN,700368.0,875802.0
116605,110008638,TE201991630,8/5/2019 4:54:00 PM,2019.0,8.0,16.0,32.0,5.0,Monday,2XXX E APACHE BLVD,...,C,Apache,N,15,85288.0,4.013319e+09,NaN,NaN,707826.0,878450.0
117854,110009887,TE201991668,8/5/2019 7:28:00 PM,2019.0,8.0,19.0,32.0,5.0,Monday,8XX E SOUTHERN AVE,...,C,Alameda,S,19,85282.0,4.013320e+09,NaN,NaN,696396.0,870495.0

In [4]:
list(dfCrime.columns)

['OBJECTID',
 'PrimaryKey',
 'OccurrenceDatetime',
 'OccurrenceYear',
 'OccurrenceMonth',
 'OccurrenceHour',
 'OccurrenceWeek',
 'OccurrenceDatePart',
 'OccurrenceWeekday',
 'ObfuscatedAddress',
 'XCoordinate',
 'YCoordinate',
 'Disclaimer',
 'PlaceName',
 'OffenseCustom',
 'LocationTranslation',
 'Latitude',
 'Longitude',
 'RucrComp',
 'CharacterArea',
 'ReportDistrict',
 'ReportBeat',
 'PostalCode',
 'CensusTractID',
 'ParkName',
 'NeighborhoodName',
 'x',
 'y']

In [6]:
list(dfCrime['OffenseCustom'].unique())

['AGGRAVATED ASSAULT                                                              ',
 'ROBBERY-STRONG ARM                                                              ',
 'ACCIDENT-HIT AND RUN                                                            ',
 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
 'SHOPLIFTING                                                                     ',
 'ACCIDENT-NO INJURY                                                              ',
 'BURGLARY NO FORCE                                                               ',
 'BURGLARY FROM VEHICLE                                                           ',
 'BURGLARY FROM YARD                                                              ',
 'THREAT/INTIMIDATE PERSON                                                        ',
 'ASSAULT                                                                         ',
 'THEFT OF BICYCLE                                                                ',
 'VIOLATE ORDER OF PROTECTION                                                     ',
 'THEFT OTHER                                                                     ',
 'TRESPASSING                                                                     ',
 'DUI-DRUGS                                                                       ',
 'SEXUAL ASSAULT                                                                  ',
 'CRIMINAL DAMAGE VEHICLE                                                         ',
 'CRIMINAL DAMAGE                                                                 ',
 'COUNTERFEIT MONEY                                                               ',
 'DUI-LIQUOR                                                                      ',
 'NARCOTIC DRUG-SELL/MANUFACTURE                                                  ',
 'ASSIST OTHER AGENCY                                                             ',
 'STOLEN PROPERTY-TRAFFICKING                                                     ',
 'MOTOR VEHICLE THEFT                                                             ',
 'FRAUD SCHEMES                                                                   ',
 'COMMERCIAL VEHICLE INSPECTION                                                   ',
 'OTHER CRIMINAL OFFENSE                                                          ',
 'THEFT OF LICENSE PLATE                                                          ',
 'INDECENT EXPOSURE                                                               ',
 'DRUG PARAPHERNALIA                                                              ',
 'DISORDERLY CONDUCT                                                              ',
 'BURGLARY FORCE                                                                  ',
 'THEFT FROM MOTOR VEHICLE                                                        ',
 'VEHICLE IMPOUND                                                                 ',
 'MISSING ADULT                                                                   ',
 'DANGEROUS DRUG-POSSESSION                                                       ',
 'CHILD CRIMES INFORMATION                                                        ',
 'FRAUD                                                                           ',
 'THEFT FROM BUILDING                                                             ',
 'IDENTITY THEFT                                                                  ',
 'ACCIDENT-INJURY                                                                 ',
 'NARCOTIC DRUG-POSSESSION                                                        ',
 'OTHER TRAFFIC OFFENSE                                                           ',
 'RUNAWAY JUVENILE                                                                ',
 'FALSE REPORTING                                                                 ',
 'ROBBERY-ARMED                                                                   ',
 'THEFT OF A CREDIT CARD                                                          ',
 'CITY CODE VIOLATION                                                             ',
 'MARIJUANA-POSSESSION                                                            ',
 'FIRE INFORMATION                                                                ',
 'AGGRAVATED ASSAULT DV                                                           ',
 'MARIJUANA-SELL/MANUFACTURE                                                      ',
 'DUI-AGGRAVATED                                                                  ',
 'MOTOR VEH THEFT-RECOVERED FOJ                                                   ',
 'CHILD NEGLECT                                                                   ',
 'HOMICIDE                                                                        ',
 'INTERFERE JUDICIAL PROCEEDINGS                                                  ',
 'ENDANGERMENT                                                                    ',
 'MISSING PERSON-RECOVERED FOJ                                                    ',
 'UNLAWFUL USE OF TRANSPORTATION                                                  ',
 'OTHER SEXUAL OFFENSE                                                            ',
 'DEATH                                                                           ',
 'THEFT OF SERVICES                                                               ',
 'THEFT OF MOTOR VEHICLE PARTS                                                    ',
 'SUSP/CANC/REV DRIVERS LICENSE                                                   ',
 'CUSTODIAL INTERFERENCE                                                          ',
 'DANGEROUS DRUG-SELL/MANUFACTUR                                                  ',
 'LIQUOR LAW VIOLATION                                                            ',
 'FRAUD-USE OF CREDIT CARD                                                        ',
 'STOLEN PROPERTY-RECOVERED FOJ                                                   ',
 'THREAT/INTIMIDATE PROPERTY                                                      ',
 'MOTOR VEHICLE THEFT TRAILER                                                     ',
 'INJURY                                                                          ',
 'WEAPON OFFENSE                                                                  ',
 'FAILURE TO RETURN RENTAL PROP                                                   ',
 'FOUND FIREARM                                                                   ',
 'FORGERY                                                                         ',
 'CRIMINAL LITTERING/POLLUTING                                                    ',
 'UNLAWFUL FLIGHT                                                                 ',
 'URINATING/DEFACATING IN PUBLIC                                                  ',
 'SEXUAL CONDUCT WITH MINOR                                                       ',
 'OTHER DRUG OFFENSE                                                              ',
 'ANIMAL CRUELTY                                                                  ',
 'STALKING                                                                        ',
 'TOWING VIOLATION/SIGNAGE                                                        ',
 'HARASSMENT                                                                      ',
 'DELAY/OBSTRUCT POLICE OFFICER                                                   ',
 'TRAFFIC MANSLAUGHTER                                                            ',
 'FUGITIVE FROM JUSTICE                                                           ',
 'SEX OFFENDER-FAIL REG/CHNG ADD                                                  ',
 'RESISTING ARREST                                                                ',
 'PRESCRIPTION DRUG-POSS/MANUFA                                                   ',
 'LURING MINOR SEX EXPLOITATION                                                   ',
 'THEFT BY PURSE SNATCHING                                                        ',
 'PROSTITUTION                                                                    ',
 'OFCR INVOLVED SHOOTING                                                          ',
 'THREAT/INTIMIDATE PERSON W/GUN                                                  ',
 'CHILD ABUSE                                                                     ',
 'THEFT BY PICK POCKETING                                                         ',
 'THEFT BY EMBEZZLEMENT                                                           ',
 'VIOLATE HARASSMENT INJUNCTION                                                   ',
 'FAILURE TO RETURN RENTAL CAR                                                    ',
 'THEFT BY EXTORTION                                                              ',
 'DRIVE BY SHOOTING                                                               ',
 'MISSING JUVENILE                                                                ',
 'FRAUD-IMPERSONATION                                                             ',
 'SURREPTITIOUS VIEWING                                                           ',
 'INTERFERE EDUCATIONAL INST                                                      ',
 'CHILD PROSTITUTION                                                              ',
 'STOLEN PROPERTY-POSSESSION                                                      ',
 'SEXUAL ABUSE                                                                    ',
 'SUICIDE                                                                         ',
 'MANSLAUGHTER                                                                    ',
 'ARSON-STRUCTURE                                                                 ',
 'SEXUAL EXPLOITATION OF A MINOR                                                  ',
 'ARSON-MOBILE                                                                    ',
 'RECKLESS BURNING                                                                ',
 'AGGRAVATED CRIMINAL DAMAGE                                                      ',
 'ARSON-OTHER PROPERTY                                                            ',
 'THEFT FROM COIN OPERT MACHINE                                                   ',
 'FORGERY-PRESCRIPTION                                                            ',
 'POSSESS BURGLARY TOOLS                                                          ',
 'ACCIDENT-FATALITY                                                               ',
 'BESTIALITY                                                                      ',
 'PUBLIC SEXUAL INDECENCY                                                         ',
 'VOYEURISM/PEEPING TOM                                                           ',
 'ESCAPE                                                                          ',
 'TERRORISM                                                                       ',
 'ACCESS INTERFERENCE                                                             ',
 'REMOVE/ALTER/DAMAGE VIN                                                         ',
 'KIDNAPPING                                                                      ',
 'COCAINE-POSSESSION                                                              ',
 'MOLESTATION OF A CHILD                                                          ',
 'SOLICITATION OF A CRIME                                                         ',
 'COMPUTER TAMPERING                                                              ',
 'PORNOGRAPHY-OBSCENE MATERIAL                                                    ',
 'FOUND FIREARM / AMMUNITION                                                      ',
 'SEXUAL ABUSE/FONDLING                                                           ',
 nan]

In [7]:
violentCrimes = ['AGGRAVATED ASSAULT                                                              ',
                 'AGGRAVATED ASSAULT DV                                                           ',
                 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
                 'HOMICIDE                                                                        ',
                 'MANSLAUGHTER                                                                    ',
                 'MOLESTATION OF A CHILD                                                          ',
                 'ROBBERY-ARMED                                                                   ',
                 'ROBBERY-STRONG ARM                                                              ',
                 'SEXUAL ABUSE                                                                    ',
                 'SEXUAL ABUSE/FONDLING                                                           ',
                 'SEXUAL ASSAULT                                                                  ']
propertyCrimes = ['BURGLARY NO FORCE                                                               ',
                  'BURGLARY FROM VEHICLE                                                           ',
                  'BURGLARY FROM YARD                                                              ',
                  'THEFT OF BICYCLE                                                                ',
                  'THEFT OTHER                                                                     ',
                  'MOTOR VEHICLE THEFT                                                             ',
                  'BURGLARY FORCE                                                                  ',
                  'THEFT FROM MOTOR VEHICLE                                                        ',
                  'THEFT FROM BUILDING                                                             ',
                  'THEFT OF A CREDIT CARD                                                          ',
                  'MOTOR VEHICLE THEFT TRAILER                                                     ',
                  'THEFT BY PICK POCKETING                                                         ',
                  'THEFT BY EXTORTION                                                              ',]
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['OffenseCustom'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(6728, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
115327,110007360,TE201991655,8/5/2019 6:00:00 PM,2019.0,8.0,18.0,32.0,5.0,Monday,1XXX S MILL AVE,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,NaN,692778.0,877476.0
115787,110007820,TE201991748,8/5/2019 11:20:00 PM,2019.0,8.0,23.0,32.0,5.0,Monday,3XXX S PRIEST DR,...,C,Alameda,S,19,85282.0,4.013320e+09,NaN,NaN,686612.0,869148.0
116605,110008638,TE201991630,8/5/2019 4:54:00 PM,2019.0,8.0,16.0,32.0,5.0,Monday,2XXX E APACHE BLVD,...,C,Apache,N,15,85288.0,4.013319e+09,NaN,NaN,707826.0,878450.0
123826,110015859,TE201988250,7/28/2019 3:20:00 PM,2019.0,7.0,15.0,31.0,28.0,Sunday,1XXX E LILAC DR,...,A,Papago/North Tempe,N,11,85288.0,4.013318e+09,NaN,Indian Bend,698005.0,890815.0
124303,110016336,TE201990551,8/2/2019 11:00:00 PM,2019.0,8.0,23.0,31.0,2.0,Friday,2X E UNIVERSITY DR,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,DT,85281.0,4.013319e+09,NaN,NaN,693159.0,881049.0

In [8]:
dfCrime = dfCrime[['OffenseCustom', 'Latitude', 'Longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['OffenseCustom', 'geometry']]
dfCrime.head()

,OffenseCustom,geometry
115327,AGGRAVATED ASSAULT ...,POINT (-111.940334 33.41212)
115787,ROBBERY-STRONG ARM ...,POINT (-111.96053 33.389226)
116605,AGGRAVATED ASSAULT-POLICE OFC ...,POINT (-111.891019 33.414797)
123826,BURGLARY NO FORCE ...,POINT (-111.923207 33.448783)
124303,BURGLARY FROM VEHICLE ...,POINT (-111.939088 33.42194)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_04_bg_500k/cb_2018_04_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(4178, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,04,013,071600,2,1500000US040130716002,040130716002,2,BG,792496,13210,"POLYGON ((-112.3 33.594, -112.3 33.594, -112.3..."
1,04,013,071910,3,1500000US040130719103,040130719103,3,BG,355984,0,"POLYGON ((-112.23 33.593, -112.23 33.593, -112..."
2,04,013,082209,2,1500000US040130822092,040130822092,2,BG,682319,0,"POLYGON ((-112.3 33.434, -112.3 33.435, -112.2..."
3,04,019,004025,4,1500000US040190040254,040190040254,4,BG,3950996,0,"POLYGON ((-110.82 32.281, -110.82 32.28, -110...."
4,04,013,319903,3,1500000US040133199033,040133199033,3,BG,683166,0,"POLYGON ((-111.93 33.372, -111.93 33.371, -111..."

In [10]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

,OffenseCustom,geometry
115327,AGGRAVATED ASSAULT ...,POINT (-111.94 33.412)
115787,ROBBERY-STRONG ARM ...,POINT (-111.96 33.389)
116605,AGGRAVATED ASSAULT-POLICE OFC ...,POINT (-111.89 33.415)
123826,BURGLARY NO FORCE ...,POINT (-111.92 33.449)
124303,BURGLARY FROM VEHICLE ...,POINT (-111.94 33.422)

In [11]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(6728, 13)

,OffenseCustom,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
115327,AGGRAVATED ASSAULT ...,POINT (-111.94 33.412),1748.0,04,013,319000,1,1500000US040133190001,040133190001,1,BG,635544.0,0.0
115787,ROBBERY-STRONG ARM ...,POINT (-111.96 33.389),3731.0,04,013,319705,1,1500000US040133197051,040133197051,1,BG,3187138.0,0.0
116605,AGGRAVATED ASSAULT-POLICE OFC ...,POINT (-111.89 33.415),105.0,04,013,319300,1,1500000US040133193001,040133193001,1,BG,1093172.0,0.0
123826,BURGLARY NO FORCE ...,POINT (-111.92 33.449),588.0,04,013,318400,1,1500000US040133184001,040133184001,1,BG,635617.0,0.0
124303,BURGLARY FROM VEHICLE ...,POINT (-111.94 33.422),4145.0,04,013,319000,3,1500000US040133190003,040133190003,3,BG,341050.0,0.0

In [12]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US040133187002    469
1500000US040133184002    319
1500000US040133197041    291
1500000US040133197031    255
1500000US040133199101    203
                        ...
1500000US040133199042      7
1500000US040133185013      5
1500000US040134222051      2
1500000US040133200023      1
1500000US040133200021      1
Name: count, Length: 113, dtype: int64

In [14]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_All_Crime_BG.csv')

In [20]:
result2 = result[result['OffenseCustom'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US040133187002    103
1500000US040133184002     40
1500000US040133197041     34
1500000US040133197031     29
1500000US040133192021     21
                        ...
1500000US040133199091      1
1500000US040133200014      1
1500000US040133195003      1
1500000US040133199062      1
1500000US040133199052      1
Name: count, Length: 106, dtype: int64

In [21]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_Violent_Crime_BG.csv')

In [22]:
result3 = result[result['OffenseCustom'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US040133187002    366
1500000US040133184002    279
1500000US040133197041    257
1500000US040133197031    226
1500000US040133199101    191
                        ...
1500000US040133199071      9
1500000US040133199042      7
1500000US040133185013      5
1500000US040133200023      1
1500000US040133200021      1
Name: count, Length: 112, dtype: int64

In [23]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_Property_Crime_BG.csv')

In [24]:
result4 = result[result['OffenseCustom'].isin(['MOTOR VEHICLE THEFT                                                             '])]
crime = result4['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US040133197041    33
1500000US040133184002    28
1500000US040133197031    24
1500000US040133191043    21
1500000US040133187002    19
                         ..
1500000US040133190001     1
1500000US040133200023     1
1500000US040133190004     1
1500000US040133192013     1
1500000US040133188003     1
Name: count, Length: 104, dtype: int64

In [25]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_MV_Crime_BG.csv')