In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [4]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/Crime_incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(320928, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,06/14/2016 01:20:00 AM,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,12/13/2016 05:00:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,07/19/2020 03:09:00 AM,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,11/17/2014 08:08:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,04/20/2015 10:22:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [8]:
dfCrime['Incident Datetime'] = pd.to_datetime(dfCrime['Incident Datetime'])
dfCrime.head()

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,2016-06-14 01:20:00,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,2016-12-13 05:00:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,2020-07-19 03:09:00,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,2014-11-17 08:08:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,2015-04-20 10:22:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [10]:
dfCrime = dfCrime.loc[(dfCrime['Incident Datetime'] >= '2018-01-01') & (dfCrime['Incident Datetime'] < '2019-01-01')]
print(dfCrime.shape)
dfCrime.head()

(15469, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
6862,18-2380652,2018-08-26 16:46:00,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,16,Sunday,1 Block FOUNTAIN PA,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
7984,19-1120425,2018-04-20 02:00:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,2,Friday,VIRGINIA ST & FRANKLIN ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
9840,18-2260290,2018-08-13 23:00:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,23,Monday,300 Block BARNARD ST,Buffalo,...,2,2002,167,2,2002,District A,016700,36029016700,360290001102,360290035022002
14475,18-3040437,2018-10-30 16:10:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,16,Tuesday,NPA ST,Buffalo,...,3,3005,1.10,3,3006,District A,000110,36029000110,360290001103,360290034003005
15144,18-1540878,2018-06-03 19:06:00,NaN,LARCENY/THEFT,Buffalo Police are investigating this report o...,Theft,19,Sunday,WASHINGTON ST & EXCHANGE ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN

In [12]:
list(dfCrime.columns)

['Case Number',
 'Incident Datetime',
 'Incident ID',
 'Incident Type Primary',
 'Incident Description',
 'Parent Incident Type',
 'Hour of Day',
 'Day of Week',
 'Address',
 'City',
 'State',
 'Location',
 'Latitude',
 'Longitude',
 'Created At',
 'updated_at',
 'zip_code',
 'neighborhood',
 'Council District',
 'Council District 2011',
 'Census Tract',
 'Census Block Group',
 'Census Block',
 '2010 Census Tract ',
 '2010 Census Block Group',
 '2010 Census Block',
 'Police District',
 'TRACTCE20',
 'GEOID20_tract',
 'GEOID20_blockgroup',
 'GEOID20_block']

In [14]:
sorted(list(dfCrime['Incident Type Primary'].unique()))

['AGGR ASSAULT',
 'ASSAULT',
 'BURGLARY',
 'CRIM NEGLIGENT HOMICIDE',
 'LARCENY/THEFT',
 'MANSLAUGHTER',
 'MURDER',
 'RAPE',
 'ROBBERY',
 'SEXUAL ABUSE',
 'THEFT OF SERVICES',
 'UUV']

In [18]:
violentCrimes = ['AGGR ASSAULT', 'RAPE', 'MURDER', 'SEXUAL ABUSE', 'ROBBERY']
dfCrime = dfCrime[dfCrime['Incident Type Primary'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(1296, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
7984,19-1120425,2018-04-20 02:00:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,2,Friday,VIRGINIA ST & FRANKLIN ST,Buffalo,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
130609,18-3420911,2018-12-08 21:41:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,21,Saturday,100 Block SKILLEN ST,Buffalo,...,1,1012,58.01,1,1016,District D,005801,36029005801,360290001101,360290027031012
130957,18-0430636,2018-02-12 14:30:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,14,Monday,STOCKBRIDGE AV & COMSTOCK AV,Buffalo,...,2,2005,47,3,3005,District E,004701,36029004701,360290001102,360290011002005
131067,18-2270989,2018-08-15 22:35:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,22,Wednesday,1300 Block DELAWARE AV,Buffalo,...,4,4007,169,4,4005,District D,016900,36029016900,360290002004,360290010004007
131097,18-2750205,2018-10-02 08:18:00,NaN,ROBBERY,Buffalo Police are investigating this report o...,Robbery,8,Tuesday,200 Block HOLDEN ST,Buffalo,...,3,3000,40.01,3,3000,District E,004003,36029004003,360290001103,360290167003000

In [22]:
dfCrime = dfCrime[['Incident Type Primary', 'Longitude', 'Latitude']]
dfCrime = dfCrime[dfCrime['Longitude'] != 'UNKNOWN']
dfCrime.head()

       Incident Type Primary Longitude Latitude
130609               ROBBERY   -78.895    42.96
130957               ROBBERY   -78.817   42.942
131067               ROBBERY   -78.868   42.922
131097               ROBBERY   -78.835   42.939
131152          SEXUAL ABUSE   -78.819   42.948

In [26]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Type Primary', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(1293, 2)

       Incident Type Primary                           geometry
130609               ROBBERY              POINT (-78.895 42.96)
130957               ROBBERY  POINT (-78.81699999999999 42.942)
131067               ROBBERY  POINT (-78.86799999999999 42.922)
131097               ROBBERY  POINT (-78.83499999999999 42.939)
131152          SEXUAL ABUSE             POINT (-78.819 42.948)

In [28]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Downloads/Rent-Walk-Local/cb_2018_36_bg_500k/cb_2018_36_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(15406, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,36,103,110401,1,1500000US361031104011,361031104011,1,BG,534139,0,"POLYGON ((-73.399 40.904, -73.394 40.904, -73...."
1,36,119,005600,1,1500000US361190056001,361190056001,1,BG,312476,180612,"POLYGON ((-73.773 40.885, -73.772 40.887, -73...."
2,36,067,011402,3,1500000US360670114023,360670114023,3,BG,45275086,887109,"POLYGON ((-76.479 43.228, -76.451 43.229, -76...."
3,36,069,051400,2,1500000US360690514002,360690514002,2,BG,46193661,0,"POLYGON ((-77.131 42.861, -77.121 42.861, -77...."
4,36,061,018600,2,1500000US360610186002,360610186002,2,BG,48762,0,"POLYGON ((-73.952 40.799, -73.95 40.799, -73.9..."

In [30]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident Type Primary                geometry
130609               ROBBERY   POINT (-78.895 42.96)
130957               ROBBERY  POINT (-78.817 42.942)
131067               ROBBERY  POINT (-78.868 42.922)
131097               ROBBERY  POINT (-78.835 42.939)
131152          SEXUAL ABUSE  POINT (-78.819 42.948)

In [32]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(1293, 13)

,Incident Type Primary,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
130609,ROBBERY,POINT (-78.895 42.96),5127,36,029,005801,1,1500000US360290058011,360290058011,1,BG,368009,0
130957,ROBBERY,POINT (-78.817 42.942),831,36,029,004700,3,1500000US360290047003,360290047003,3,BG,227556,0
131067,ROBBERY,POINT (-78.868 42.922),8454,36,029,016900,4,1500000US360290169004,360290169004,4,BG,188964,0
131097,ROBBERY,POINT (-78.835 42.939),13994,36,029,004001,3,1500000US360290040013,360290040013,3,BG,319978,0
131152,SEXUAL ABUSE,POINT (-78.819 42.948),14397,36,029,004700,1,1500000US360290047001,360290047001,1,BG,268841,0

In [34]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US360290165001    51
1500000US360290034002    16
1500000US360290035004    16
1500000US360290171005    15
1500000US360290168004    15
                         ..
1500000US360290023002     1
1500000US360290167001     1
1500000US360290093013     1
1500000US360290063014     1
1500000US360290045001     1
Name: count, Length: 254, dtype: int64

In [36]:
# export as a csv
crime.to_csv('Buffalo_Violent_Crime_BG.csv')