In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')
print(dfCrime.shape)
dfCrime.head()

(337854, 28)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17312/3922547607.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
0,109892033,TE2013102138,8/16/2013 12:45:00 PM,2013.0,8.0,12.0,33.0,16.0,Friday,9XX E BROADWAY RD,...,C,Alameda,S,20,85282.0,4.013320e+09,NaN,NaN,697343.0,875784.0
1,109892034,TE2013104042,8/19/2013 3:44:00 PM,2013.0,8.0,15.0,34.0,19.0,Monday,HARDY DR / W UNIVERSITY DR,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,NaN,689158.0,881039.0
2,109892035,TE2013104050,8/16/2013 6:00:00 PM,2013.0,8.0,18.0,33.0,16.0,Friday,6XXX S RURAL RD,...,C,Kiwanis/The Lakes,S,21,85283.0,4.013320e+09,NaN,NaN,696260.0,861054.0
3,109892036,TE2013104316,8/20/2013 7:59:00 AM,2013.0,8.0,7.0,34.0,20.0,Tuesday,1XXX N SCOTTSDALE RD,...,C,Papago/North Tempe,N,11,85288.0,4.013318e+09,NaN,Indian Bend,697930.0,890057.0
4,109892037,TE2013105261,8/22/2013 9:37:00 AM,2013.0,8.0,9.0,34.0,22.0,Thursday,2XXX E APACHE BLVD,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,NaN,705067.0,878463.0

In [7]:
dfCrime = dfCrime[dfCrime['OccurrenceYear'] == 2018]
print(dfCrime.shape)
dfCrime.head()

(28238, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
29656,109921689,TE201818686,2/12/2018 10:00:00 PM,2018.0,2.0,22.0,7.0,12.0,Monday,2XXX E FREMONT DR,...,C,Kiwanis/The Lakes,S,22,85282.0,4.013319e+09,NaN,Cole Park,705054.0,867024.0
62847,109954880,TE201811608,1/27/2018 11:03:00 PM,2018.0,1.0,23.0,4.0,27.0,Saturday,APACHE BLVD / S MCCLINTOCK DR,...,C,Apache,N,14,85281.0,4.013319e+09,NaN,NaN,702305.0,878426.0
102362,109994395,TE201818617,2/10/2018 12:00:00 AM,2018.0,2.0,0.0,6.0,10.0,Saturday,6XX W SESAME ST,...,C,Mills/Emerald,S,21,85283.0,4.013320e+09,NaN,Pepperwood,689762.0,862069.0
104263,109996296,TE201891739,8/6/2018 4:48:00 PM,2018.0,8.0,16.0,32.0,6.0,Monday,1XXX E RIO SALADO PKWY,...,C,Apache,N,15,85288.0,4.013318e+09,NaN,NaN,703327.0,884047.0
104267,109996300,TE201891474,8/6/2018 5:40:00 AM,2018.0,8.0,5.0,32.0,6.0,Monday,1XXX S MITCHELL DR,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,Mitchell Park,690447.0,879986.0

In [9]:
list(dfCrime.columns)

['OBJECTID',
 'PrimaryKey',
 'OccurrenceDatetime',
 'OccurrenceYear',
 'OccurrenceMonth',
 'OccurrenceHour',
 'OccurrenceWeek',
 'OccurrenceDatePart',
 'OccurrenceWeekday',
 'ObfuscatedAddress',
 'XCoordinate',
 'YCoordinate',
 'Disclaimer',
 'PlaceName',
 'OffenseCustom',
 'LocationTranslation',
 'Latitude',
 'Longitude',
 'RucrComp',
 'CharacterArea',
 'ReportDistrict',
 'ReportBeat',
 'PostalCode',
 'CensusTractID',
 'ParkName',
 'NeighborhoodName',
 'x',
 'y']

In [11]:
sorted(list(dfCrime['OffenseCustom'].unique()))

['ACCESS INTERFERENCE                                                             ',
 'ACCIDENT-FATALITY                                                               ',
 'ACCIDENT-HIT AND RUN                                                            ',
 'ACCIDENT-INJURY                                                                 ',
 'ACCIDENT-NO INJURY                                                              ',
 'AGGRAVATED ASSAULT                                                              ',
 'AGGRAVATED ASSAULT DV                                                           ',
 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
 'AGGRAVATED CRIMINAL DAMAGE                                                      ',
 'ANIMAL CRUELTY                                                                  ',
 'ARSON-MOBILE                                                                    ',
 'ARSON-OTHER PROPERTY                                                            ',
 'ARSON-STRUCTURE                                                                 ',
 'ASSAULT                                                                         ',
 'ASSIST OTHER AGENCY                                                             ',
 'BESTIALITY                                                                      ',
 'BURGLARY FORCE                                                                  ',
 'BURGLARY FROM VEHICLE                                                           ',
 'BURGLARY FROM YARD                                                              ',
 'BURGLARY NO FORCE                                                               ',
 'CHILD ABUSE                                                                     ',
 'CHILD CRIMES INFORMATION                                                        ',
 'CHILD NEGLECT                                                                   ',
 'CHILD PROSTITUTION                                                              ',
 'CITY CODE VIOLATION                                                             ',
 'COCAINE-POSSESSION                                                              ',
 'COMMERCIAL VEHICLE INSPECTION                                                   ',
 'COMPUTER TAMPERING                                                              ',
 'CONSPIRACY OF A CRIME                                                           ',
 'CONTRIBUTING DELINQUENCY MINOR                                                  ',
 'COUNTERFEIT MONEY                                                               ',
 'CRIMINAL DAMAGE                                                                 ',
 'CRIMINAL DAMAGE VEHICLE                                                         ',
 'CRIMINAL LITTERING/POLLUTING                                                    ',
 'CUSTODIAL INTERFERENCE                                                          ',
 'DANGEROUS DRUG-POSSESSION                                                       ',
 'DANGEROUS DRUG-SELL/MANUFACTUR                                                  ',
 'DEATH                                                                           ',
 'DELAY/OBSTRUCT POLICE OFFICER                                                   ',
 'DISORDERLY CONDUCT                                                              ',
 'DRIVE BY SHOOTING                                                               ',
 'DRUG PARAPHERNALIA                                                              ',
 'DUI-AGGRAVATED                                                                  ',
 'DUI-DRUGS                                                                       ',
 'DUI-LIQUOR                                                                      ',
 'ENDANGERMENT                                                                    ',
 'ESCAPE                                                                          ',
 'FAILURE TO RETURN RENTAL CAR                                                    ',
 'FAILURE TO RETURN RENTAL PROP                                                   ',
 'FALSE REPORTING                                                                 ',
 'FIRE INFORMATION                                                                ',
 'FORGERY                                                                         ',
 'FORGERY-PRESCRIPTION                                                            ',
 'FOUND FIREARM                                                                   ',
 'FRAUD                                                                           ',
 'FRAUD SCHEMES                                                                   ',
 'FRAUD-IMPERSONATION                                                             ',
 'FRAUD-USE OF CREDIT CARD                                                        ',
 'FUGITIVE FROM JUSTICE                                                           ',
 'HARASSMENT                                                                      ',
 'HOMICIDE                                                                        ',
 'HUMAN TRAFFICKING SEX ACTS                                                      ',
 'IDENTITY THEFT                                                                  ',
 'INDECENT EXPOSURE                                                               ',
 'INJURY                                                                          ',
 'INTERFERE EDUCATIONAL INST                                                      ',
 'INTERFERE JUDICIAL PROCEEDINGS                                                  ',
 'KIDNAPPING                                                                      ',
 'LIQUOR LAW VIOLATION                                                            ',
 'LURING MINOR SEX EXPLOITATION                                                   ',
 'MANSLAUGHTER                                                                    ',
 'MARIJUANA-POSSESSION                                                            ',
 'MARIJUANA-SELL/MANUFACTURE                                                      ',
 'MISSING ADULT                                                                   ',
 'MISSING JUVENILE                                                                ',
 'MISSING PERSON-RECOVERED FOJ                                                    ',
 'MOLESTATION OF A CHILD                                                          ',
 'MOTOR VEH THEFT-RECOVERED FOJ                                                   ',
 'MOTOR VEHICLE THEFT                                                             ',
 'MOTOR VEHICLE THEFT TRAILER                                                     ',
 'NARCOTIC DRUG-POSSESSION                                                        ',
 'NARCOTIC DRUG-SELL/MANUFACTURE                                                  ',
 'OFCR INVOLVED SHOOTING                                                          ',
 'OTHER CRIMINAL OFFENSE                                                          ',
 'OTHER DRUG OFFENSE                                                              ',
 'OTHER SEXUAL OFFENSE                                                            ',
 'OTHER TRAFFIC OFFENSE                                                           ',
 'PORNOGRAPHY-OBSCENE MATERIAL                                                    ',
 'POSSESS BURGLARY TOOLS                                                          ',
 'POSSESS FORGERY DEVICE                                                          ',
 'PRESCRIPTION DRUG-POSS/MANUFA                                                   ',
 'PROSTITUTION                                                                    ',
 'PUBLIC SEXUAL INDECENCY                                                         ',
 'RECKLESS BURNING                                                                ',
 'REMOVE/ALTER/DAMAGE VIN                                                         ',
 'RESISTING ARREST                                                                ',
 'ROBBERY-ARMED                                                                   ',
 'ROBBERY-STRONG ARM                                                              ',
 'RUNAWAY JUVENILE                                                                ',
 'SEX OFFENDER-FAIL REG/CHNG ADD                                                  ',
 'SEXUAL ABUSE                                                                    ',
 'SEXUAL ABUSE/FONDLING                                                           ',
 'SEXUAL ASSAULT                                                                  ',
 'SEXUAL CONDUCT WITH MINOR                                                       ',
 'SEXUAL EXPLOITATION OF A MINOR                                                  ',
 'SHOPLIFTING                                                                     ',
 'STALKING                                                                        ',
 'STOLEN PROPERTY-POSSESSION                                                      ',
 'STOLEN PROPERTY-RECOVERED FOJ                                                   ',
 'STOLEN PROPERTY-TRAFFICKING                                                     ',
 'SUICIDE                                                                         ',
 'SURREPTITIOUS VIEWING                                                           ',
 'SUSP/CANC/REV DRIVERS LICENSE                                                   ',
 'TERRORISM                                                                       ',
 'THEFT BY EMBEZZLEMENT                                                           ',
 'THEFT BY EXTORTION                                                              ',
 'THEFT BY PICK POCKETING                                                         ',
 'THEFT BY PURSE SNATCHING                                                        ',
 'THEFT FROM BUILDING                                                             ',
 'THEFT FROM COIN OPERT MACHINE                                                   ',
 'THEFT FROM MOTOR VEHICLE                                                        ',
 'THEFT OF A CREDIT CARD                                                          ',
 'THEFT OF BICYCLE                                                                ',
 'THEFT OF LICENSE PLATE                                                          ',
 'THEFT OF MOTOR VEHICLE PARTS                                                    ',
 'THEFT OF SERVICES                                                               ',
 'THEFT OTHER                                                                     ',
 'THREAT/INTIMIDATE PERSON                                                        ',
 'THREAT/INTIMIDATE PERSON W/GUN                                                  ',
 'THREAT/INTIMIDATE PROPERTY                                                      ',
 'TOWING VIOLATION/SIGNAGE                                                        ',
 'TRESPASSING                                                                     ',
 'UNLAWFUL FLIGHT                                                                 ',
 'UNLAWFUL IMPRISONMENT                                                           ',
 'UNLAWFUL USE OF TRANSPORTATION                                                  ',
 'URINATING/DEFACATING IN PUBLIC                                                  ',
 'VEHICLE IMPOUND                                                                 ',
 'VIOLATE HARASSMENT INJUNCTION                                                   ',
 'VIOLATE ORDER OF PROTECTION                                                     ',
 'VOYEURISM/PEEPING TOM                                                           ',
 'WEAPON OFFENSE                                                                  ']

In [13]:
violentCrimes = ['AGGRAVATED ASSAULT                                                              ',
                 'AGGRAVATED ASSAULT DV                                                           ',
                 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
                 'HOMICIDE                                                                        ',
                 'MANSLAUGHTER                                                                    ',
                 'MOLESTATION OF A CHILD                                                          ',
                 'ROBBERY-ARMED                                                                   ',
                 'ROBBERY-STRONG ARM                                                              ',
                 'SEXUAL ABUSE                                                                    ',
                 'SEXUAL ABUSE/FONDLING                                                           ',
                 'SEXUAL ASSAULT                                                                  ']
dfCrime = dfCrime[dfCrime['OffenseCustom'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(980, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
105041,109997074,TE201892001,8/7/2018 9:20:00 AM,2018.0,8.0,9.0,32.0,7.0,Tuesday,1XXX E DON CARLOS AVE,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,Alegre Community,703266.0,879432.0
136089,110028122,TE201891808,8/6/2018 8:30:00 PM,2018.0,8.0,20.0,32.0,6.0,Monday,1XXX E DON CARLOS AVE,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,Alegre Community,704557.0,879446.0
139316,110031349,TE201892516,7/19/2018 5:14:00 PM,2018.0,7.0,17.0,29.0,19.0,Thursday,1XX E 5TH ST,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,DT,85281.0,4.013319e+09,NaN,NaN,693853.0,882570.0
140917,110032950,TE20182702,1/7/2018 5:14:00 AM,2018.0,1.0,5.0,2.0,7.0,Sunday,2XXX E MCARTHUR DR,...,C,Apache,N,15,85288.0,4.013319e+09,Esquer Park,NaN,708824.0,879057.0
140921,110032954,TE2018434,1/1/2018 4:00:00 PM,2018.0,1.0,16.0,1.0,1.0,Monday,9XXX S PRIEST DR,...,C,Mills/Emerald,S,23,85284.0,4.013810e+09,NaN,NaN,685814.0,847874.0

In [15]:
dfCrime = dfCrime[['OffenseCustom', 'Latitude', 'Longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['OffenseCustom', 'geometry']]
dfCrime.head()

,OffenseCustom,geometry
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.905963 33.417498)
136089,AGGRAVATED ASSAULT ...,POINT (-111.901732 33.417536)
139316,SEXUAL ASSAULT ...,POINT (-111.936815 33.426121)
140917,ROBBERY-STRONG ARM ...,POINT (-111.887747 33.416464)
140921,AGGRAVATED ASSAULT DV ...,POINT (-111.963113 33.330755)

In [17]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Downloads/Rent-Walk-Local/cb_2018_04_bg_500k/cb_2018_04_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(4178, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,04,013,071600,2,1500000US040130716002,040130716002,2,BG,792496,13210,"POLYGON ((-112.3 33.594, -112.3 33.594, -112.3..."
1,04,013,071910,3,1500000US040130719103,040130719103,3,BG,355984,0,"POLYGON ((-112.23 33.593, -112.23 33.593, -112..."
2,04,013,082209,2,1500000US040130822092,040130822092,2,BG,682319,0,"POLYGON ((-112.3 33.434, -112.3 33.435, -112.2..."
3,04,019,004025,4,1500000US040190040254,040190040254,4,BG,3950996,0,"POLYGON ((-110.82 32.281, -110.82 32.28, -110...."
4,04,013,319903,3,1500000US040133199033,040133199033,3,BG,683166,0,"POLYGON ((-111.93 33.372, -111.93 33.371, -111..."

In [19]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

,OffenseCustom,geometry
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.91 33.417)
136089,AGGRAVATED ASSAULT ...,POINT (-111.9 33.418)
139316,SEXUAL ASSAULT ...,POINT (-111.94 33.426)
140917,ROBBERY-STRONG ARM ...,POINT (-111.89 33.416)
140921,AGGRAVATED ASSAULT DV ...,POINT (-111.96 33.331)

In [21]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(980, 13)

,OffenseCustom,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.91 33.417),65.0,04,013,319201,2,1500000US040133192012,040133192012,2,BG,382504.0,0.0
136089,AGGRAVATED ASSAULT ...,POINT (-111.9 33.418),65.0,04,013,319201,2,1500000US040133192012,040133192012,2,BG,382504.0,0.0
139316,SEXUAL ASSAULT ...,POINT (-111.94 33.426),3503.0,04,013,318700,2,1500000US040133187002,040133187002,2,BG,1192910.0,0.0
140917,ROBBERY-STRONG ARM ...,POINT (-111.89 33.416),105.0,04,013,319300,1,1500000US040133193001,040133193001,1,BG,1093172.0,0.0
140921,AGGRAVATED ASSAULT DV ...,POINT (-111.96 33.331),3218.0,04,013,810000,1,1500000US040138100001,040138100001,1,BG,2781571.0,0.0

In [23]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US040133187002    90
1500000US040133184002    46
1500000US040133197031    35
1500000US040133192012    34
1500000US040133197041    30
                         ..
1500000US040133199054     1
1500000US040133199053     1
1500000US040133194032     1
1500000US040133195001     1
1500000US040133199062     1
Name: count, Length: 106, dtype: int64

In [25]:
# export as a csv
crime.to_csv('Tempe_Violent_Crime_BG.csv')