In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [3]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_Reports_2012_Jul2022.csv')
print(dfCrime.shape)
dfCrime.head()

(200571, 16)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_5513/3572054425.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_Reports_2012_Jul2022.csv')

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
0,-1.359004e+07,4.536511e+06,1,502150,22010202,ACSO,3000 CASTRO VALLEY BL,3088 CASTRO VALLEY BL,CASTRO VALLEY,CA,94546.0,13B,MISD - BATTERY ON PERSON,-122.081392,37.695585,2022/06/27 22:14:00+00
1,-1.359703e+07,4.533177e+06,2,502149,22010200,ACSO,1800 VIA AMIGOS,1828 VIA AMIGOS,SAN LORENZO,CA,94580.0,240,FEL - TAKE VEHICLE W/O OWNER CONSENT/VEHICLE T...,-122.144170,37.671883,2022/06/27 21:45:00+00
2,-1.359428e+07,4.537706e+06,3,502144,22010198,ACSO,1600 MONO AV,1612 MONO AV,SAN LEANDRO,CA,94578.0,999,72 HOUR MENTAL HEALTH,-122.119540,37.704077,2022/06/27 21:13:00+00
3,-1.359306e+07,4.535300e+06,4,502140,22010195,ACSO,600 HARMONY DR,636 HARMONY DR,HAYWARD,CA,94541.0,999,72 HOUR MENTAL HEALTH,-122.108579,37.686977,2022/06/27 20:20:00+00
4,-1.354524e+07,4.545353e+06,5,502138,22010193,ACSO,3900 DYER RD,3988 DYER RD,LIVERMORE,CA,94551.0,23H,GRAND THEFT - ALL OTHER,-121.678985,37.758408,2022/06/10 06:00:00+00

In [5]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(200571, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
0,-1.359004e+07,4.536511e+06,1,502150,22010202,ACSO,3000 CASTRO VALLEY BL,3088 CASTRO VALLEY BL,CASTRO VALLEY,CA,94546.0,13B,MISD - BATTERY ON PERSON,-122.081392,37.695585,2022/06/27 22:14:00+00
1,-1.359703e+07,4.533177e+06,2,502149,22010200,ACSO,1800 VIA AMIGOS,1828 VIA AMIGOS,SAN LORENZO,CA,94580.0,240,FEL - TAKE VEHICLE W/O OWNER CONSENT/VEHICLE T...,-122.144170,37.671883,2022/06/27 21:45:00+00
2,-1.359428e+07,4.537706e+06,3,502144,22010198,ACSO,1600 MONO AV,1612 MONO AV,SAN LEANDRO,CA,94578.0,999,72 HOUR MENTAL HEALTH,-122.119540,37.704077,2022/06/27 21:13:00+00
3,-1.359306e+07,4.535300e+06,4,502140,22010195,ACSO,600 HARMONY DR,636 HARMONY DR,HAYWARD,CA,94541.0,999,72 HOUR MENTAL HEALTH,-122.108579,37.686977,2022/06/27 20:20:00+00
4,-1.354524e+07,4.545353e+06,5,502138,22010193,ACSO,3900 DYER RD,3988 DYER RD,LIVERMORE,CA,94551.0,23H,GRAND THEFT - ALL OTHER,-121.678985,37.758408,2022/06/10 06:00:00+00

In [7]:
dfCrime['DateTime'] = pd.to_datetime(dfCrime['DateTime'])
dfCrime = dfCrime.loc[(dfCrime['DateTime'] >= '2019-01-01') & (dfCrime['DateTime'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(18628, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
2279,-1.359383e+07,4.536129e+06,2280,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11D,LEWD OR LASCIVIOUS ACTS W/CHILD UNDER 14 YEARS,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2280,-1.359383e+07,4.536129e+06,2281,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11C,SEXUAL PENETRATION WITH FORCE/ETC,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2281,-1.359383e+07,4.536129e+06,2282,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11D,SEXUAL BATTERY,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2282,-1.359383e+07,4.536129e+06,2283,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11A,RAPE BY FORCE/FEAR/ETC,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2458,-1.359478e+07,4.532897e+06,2459,498283,22007172,ACSO,18200 VIA JOSE,18251 VIA JOSE,SAN LORENZO,CA,94580.0,11D,LEWD OR LASCIVIOUS ACTS W/CHILD UNDER 14 YEARS,-122.123967,37.669890,2019-01-01 09:39:00+00:00

In [9]:
list(dfCrime['CrimeCode'].unique())

['11D',
 '11C',
 '11A',
 '13B',
 '11B',
 '13A',
 '26C',
 '999',
 '250',
 '36B',
 '220',
 '240',
 '23H',
 '90Z',
 '26B',
 'R24',
 '23A',
 '270',
 '90F',
 '100',
 '23F',
 '280',
 '35A',
 '23G',
 '290',
 '13C',
 '90D',
 '90E',
 '90J',
 '120',
 '90C',
 '35B',
 '40A',
 '520',
 '23C',
 '90B',
 '23D',
 '26A',
 '90I',
 '90A',
 nan,
 '90H',
 '200',
 '09A',
 '39A',
 '370',
 '90G',
 '210',
 '40B',
 '09B',
 '23E',
 '23B']

In [11]:
dfCrime[dfCrime['CrimeCode'] == '13A']

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
6432,-1.358976e+07,4.535000e+06,6433,490410,22001034,ACSO,21900 DOLORES ST,21966 DOLORES ST,CASTRO VALLEY,CA,94546.0,13A,ELDER/DEPENDENT ADULT CRUELTY,-122.078875,37.684847,2019-08-01 15:19:00+00:00
38517,-1.358854e+07,4.535620e+06,38518,444289,20004125,ACSO,22000 CAMERON STREET,22032 CAMERON STREET,CASTRO VALLEY,CA,94546,13A,FORCE OR ADW NOT FIREARM:GBI LIKELY,-122.067971,37.689254,2019-12-24 11:59:00+00:00
38519,-1.358854e+07,4.535620e+06,38520,444289,20004125,ACSO,22000 CAMERON STREET,22032 CAMERON STREET,CASTRO VALLEY,CA,94546,13A,FORCE OR ADW NOT FIREARM:GBI LIKELY,-122.067971,37.689254,2019-12-24 11:59:00+00:00
40399,-1.359299e+07,4.536216e+06,40400,441253,20001728,ACSO,1400 167TH AV,1475 167TH AV,SAN LEANDRO,CA,94578,13A,WILLFUL CRUELTY TO CHILD:POSSIBLE INJURY/DEATH,-122.107920,37.693490,2019-12-25 10:45:00+00:00
40403,-1.359299e+07,4.536216e+06,40404,441253,20001728,ACSO,1400 167TH AV,1475 167TH AV,SAN LEANDRO,CA,94578,13A,MAYHEM,-122.107920,37.693490,2019-12-25 10:45:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60153,-1.359263e+07,4.534055e+06,60154,411527,19000453,ACSO,400 BLOSSOM WY,494 BLOSSOM WY,HAYWARD,CA,94541,13A,FORCE OR ADW NOT FIREARM,-122.104709,37.678124,2019-01-09 17:30:00+00:00
60354,-1.359173e+07,4.532849e+06,60355,411182,19000192,ACSO,300 SMALLEY AV,364 SMALLEY AV,HAYWARD,CA,94541,13A,ELDER/DEPENDENT ADULT CRUELTY,-122.096597,37.669548,2019-01-04 13:53:00+00:00
60410,-1.358674e+07,4.534367e+06,60411,411106,19000131,ACSO,23200 MAUD AV,23243 MAUD AV,HAYWARD,CA,94541,13A,FORCE OR ADW NOT FIREARM:GBI LIKELY,-122.051736,37.680342,2019-01-03 14:00:00+00:00
60422,-1.359224e+07,4.536122e+06,60423,411083,19000114,ACSO,17200 FOOTHILL BL,17290 FOOTHILL BL,SAN LEANDRO,CA,94546,13A,EXHIBIT FIREARM,-122.101133,37.692818,2019-01-03 08:03:00+00:00
60490,-1.359463e+07,4.535258e+06,60491,410966,19000020,ACSO,200 E LEWELLING BL,275 E LEWELLING BL,SAN LORENZO,CA,94580,13A,LYNCHING,-122.122641,37.686678,2019-01-01 12:12:00+00:00

In [13]:
violentCrimes = ['13A', '09A', '120', '11A', '11B', '11C', '11D']
dfCrime = dfCrime[dfCrime['CrimeCode'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(728, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
2279,-1.359383e+07,4.536129e+06,2280,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11D,LEWD OR LASCIVIOUS ACTS W/CHILD UNDER 14 YEARS,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2280,-1.359383e+07,4.536129e+06,2281,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11C,SEXUAL PENETRATION WITH FORCE/ETC,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2281,-1.359383e+07,4.536129e+06,2282,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11D,SEXUAL BATTERY,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2282,-1.359383e+07,4.536129e+06,2283,498520,22007351,ACSO,900 DELANO ST,974 DELANO ST,SAN LORENZO,CA,94580.0,11A,RAPE BY FORCE/FEAR/ETC,-122.115455,37.692868,2019-05-21 17:30:00+00:00
2458,-1.359478e+07,4.532897e+06,2459,498283,22007172,ACSO,18200 VIA JOSE,18251 VIA JOSE,SAN LORENZO,CA,94580.0,11D,LEWD OR LASCIVIOUS ACTS W/CHILD UNDER 14 YEARS,-122.123967,37.669890,2019-01-01 09:39:00+00:00

In [15]:
dfCrime = dfCrime[['CrimeCode', 'Longitude', 'Latitude']]
dfCrime.head()

     CrimeCode   Longitude   Latitude
2279       11D -122.115455  37.692868
2280       11C -122.115455  37.692868
2281       11D -122.115455  37.692868
2282       11A -122.115455  37.692868
2458       11D -122.123967  37.669890

In [17]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['CrimeCode', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(728, 2)

     CrimeCode                           geometry
2279       11D  POINT (-122.11545468 37.69286757)
2280       11C  POINT (-122.11545468 37.69286757)
2281       11D  POINT (-122.11545468 37.69286757)
2282       11A  POINT (-122.11545468 37.69286757)
2458       11D  POINT (-122.12396654 37.66988974)

In [21]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [23]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

     CrimeCode                geometry
2279       11D  POINT (-122.12 37.693)
2280       11C  POINT (-122.12 37.693)
2281       11D  POINT (-122.12 37.693)
2282       11A  POINT (-122.12 37.693)
2458       11D   POINT (-122.12 37.67)

In [25]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(728, 13)

,CrimeCode,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
2279,11D,POINT (-122.12 37.693),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
2280,11C,POINT (-122.12 37.693),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
2281,11D,POINT (-122.12 37.693),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
2282,11A,POINT (-122.12 37.693),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
2458,11D,POINT (-122.12 37.67),19773,06,001,436100,1,1500000US060014361001,060014361001,1,BG,364408,0

In [27]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060014340003    33
1500000US060014362002    27
1500000US060014309002    23
1500000US060014328003    23
1500000US060014340001    21
                         ..
1500000US060014359002     1
1500000US060014364012     1
1500000US060014507013     1
1500000US060014364013     1
1500000US060014514043     1
Name: count, Length: 112, dtype: int64

In [29]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Alameda_County_Violent_Crime_BG.csv')