In [9]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [11]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/Police_Department_Incident_Reports__2018_to_Present_20250412.csv')
print(dfCrime.shape)
dfCrime.head()

(947910, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023,Wednesday,2023/03/11 04:55:00 PM,125378606372,1253786,236046123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/11 03:00:00 PM,2023/03/11,15:00,2023,Saturday,2023/03/13 08:29:00 AM,125420606244,1254206,236045937,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(896213, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
6,2022/06/27 12:00:00 PM,2022/06/27,12:00,2022,Monday,2023/03/15 05:20:00 PM,125439371000,1254393,230184129,230742480.0,...,-122.408227,POINT (-122.40822672700406 37.78735926098589),19.0,NaN,1.0,NaN,NaN,NaN,3.0,6.0
8,2023/03/16 05:30:00 PM,2023/03/16,17:30,2023,Thursday,2023/03/16 06:02:00 PM,125482604134,1254826,230187101,230752550.0,...,-122.401324,POINT (-122.40132418490647 37.76228996810526),54.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
26,2023/03/21 03:50:00 PM,2023/03/21,15:50,2023,Tuesday,2023/03/21 04:01:00 PM,125656351040,1256563,230199764,230802198.0,...,-122.418271,POINT (-122.41827098126804 37.787037946181535),50.0,NaN,NaN,NaN,NaN,NaN,10.0,6.0
144,2021/07/03 12:00:00 PM,2021/07/03,12:00,2021,Saturday,2021/07/03 12:37:00 PM,104624471000,1046244,210417332,211841413.0,...,-122.446610,POINT (-122.44660957715965 37.801787342426636),17.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
145,2021/07/22 07:16:00 PM,2021/07/22,19:16,2021,Thursday,2021/07/23 01:35:00 PM,105341571000,1053415,216098495,NaN,...,-122.394829,POINT (-122.39482876133759 37.76524759917852),54.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0

In [13]:
dfCrime = dfCrime[dfCrime['Incident Year'] == 2018]
print(dfCrime.shape)
dfCrime.head()

(143670, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
1533,2018/12/01 12:00:00 PM,2018/12/01,12:00,2018,Saturday,2025/03/19 04:20:00 PM,146999809029,1469998,180951860,NaN,...,-122.393265,POINT (-122.39326477050781 37.79423141479492),108.0,1.0,NaN,NaN,4.0,NaN,3.0,6.0
1990,2018/11/10 03:00:00 PM,2018/11/10,15:00,2018,Saturday,2025/03/26 03:16:00 PM,147168868020,1471688,250170885,250852094.0,...,-122.486404,POINT (-122.48640441894531 37.74258041381836),40.0,NaN,NaN,NaN,NaN,NaN,7.0,10.0
3021,2018/03/07 07:00:00 AM,2018/03/07,07:00,2018,Wednesday,2023/08/24 05:33:00 AM,131240006374,1312400,190202001,NaN,...,-122.410731,POINT (-122.41073071858334 37.76817786907554),53.0,NaN,NaN,NaN,3.0,NaN,9.0,3.0
3071,2018/03/07 07:00:00 AM,2018/03/07,07:00,2018,Wednesday,2023/08/24 06:37:00 PM,131240106372,1312401,190202001,NaN,...,-122.410731,POINT (-122.41073071858334 37.76817786907554),53.0,NaN,NaN,NaN,3.0,NaN,9.0,3.0
4777,2018/03/23 12:00:00 PM,2018/03/23,12:00,2018,Friday,2023/12/05 04:53:00 PM,134480109029,1344801,230855007,233392528.0,...,-122.424538,POINT (-122.42453832626387 37.80130371865117),15.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0

In [17]:
violentCrimes = ['Aggravated Assault', 'Rape - Attempted', 'Robbery - Residential', 'Robbery - Street', 'Robbery - Carjacking',
                'Sex Offense', 'Robbery - Commercial', 'Rape', 'Homicide', 'Robbery - Other']
dfCrime = dfCrime[dfCrime['Incident Subcategory'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(6906, 35)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
66955,2018/06/10 12:00:00 AM,2018/06/10,00:00,2018,Sunday,2024/05/27 12:00:00 AM,139380914020,1393809,240331354,241480345.0,...,-122.403633,POINT (-122.40363311767578 37.77516174316406),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0
90912,2018/05/10 12:00:00 AM,2018/05/10,00:00,2018,Thursday,2024/06/11 11:35:00 AM,139774714020,1397747,240365303,241631159.0,...,-122.403633,POINT (-122.40363311767578 37.77516174316406),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0
92493,2018/11/13 12:00:00 AM,2018/11/13,00:00,2018,Tuesday,2024/06/13 09:18:00 AM,139833814020,1398338,240369963,241650865.0,...,-122.403633,POINT (-122.40363311767578 37.77516174316406),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0
105784,2018/09/24 01:50:00 PM,2018/09/24,13:50,2018,Monday,2018/09/24 01:58:00 PM,142819403014,1428194,180725035,NaN,...,-122.403488,POINT (-122.40348815917969 37.7879638671875),19.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0
111158,2018/11/13 12:00:00 AM,2018/11/13,00:00,2018,Tuesday,2024/07/10 07:15:00 AM,140581514020,1405815,240429078,241920469.0,...,-122.403633,POINT (-122.40363311767578 37.77516174316406),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0

In [19]:
dfCrime = dfCrime[['Incident ID', 'Longitude', 'Latitude']]
dfCrime.head()

        Incident ID   Longitude   Latitude
66955       1393809 -122.403633  37.775162
90912       1397747 -122.403633  37.775162
92493       1398338 -122.403633  37.775162
105784      1428194 -122.403488  37.787964
111158      1405815 -122.403633  37.775162

In [21]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident ID', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(6906, 2)

        Incident ID                                      geometry
66955       1393809  POINT (-122.4036331176758 37.77516174316406)
90912       1397747  POINT (-122.4036331176758 37.77516174316406)
92493       1398338  POINT (-122.4036331176758 37.77516174316406)
105784      1428194   POINT (-122.4034881591797 37.7879638671875)
111158      1405815  POINT (-122.4036331176758 37.77516174316406)

In [23]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Downloads/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [25]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

        Incident ID               geometry
66955       1393809  POINT (-122.4 37.775)
90912       1397747  POINT (-122.4 37.775)
92493       1398338  POINT (-122.4 37.775)
105784      1428194  POINT (-122.4 37.788)
111158      1405815  POINT (-122.4 37.775)

In [27]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(6906, 13)

,Incident ID,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
66955,1393809,POINT (-122.4 37.775),10013,06,075,018000,2,1500000US060750180002,060750180002,2,BG,509339,0
90912,1397747,POINT (-122.4 37.775),10013,06,075,018000,2,1500000US060750180002,060750180002,2,BG,509339,0
92493,1398338,POINT (-122.4 37.775),10013,06,075,018000,2,1500000US060750180002,060750180002,2,BG,509339,0
105784,1428194,POINT (-122.4 37.788),15071,06,075,011700,2,1500000US060750117002,060750117002,2,BG,286064,0
111158,1405815,POINT (-122.4 37.775),10013,06,075,018000,2,1500000US060750180002,060750180002,2,BG,509339,0

In [29]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060750117002    249
1500000US060750615001    214
1500000US060750176015    170
1500000US060750125012    145
1500000US060750176013    136
                        ...
1500000US060750327003      1
1500000US060750452003      1
1500000US060750129021      1
1500000US060750478011      1
1500000US060750477021      1
Name: count, Length: 482, dtype: int64

In [31]:
# export as a csv
crime.to_csv('SF_Violent_Crime_BG.csv')