In [17]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [19]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/Crime_Reports_2012_Jul2022.csv')
print(dfCrime.shape)
dfCrime.head()

(200571, 16)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_13337/3206766379.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Rent-Walk-Local/Crime_Reports_2012_Jul2022.csv')

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
0,-1.359004e+07,4.536511e+06,1,502150,22010202,ACSO,3000 CASTRO VALLEY BL,3088 CASTRO VALLEY BL,CASTRO VALLEY,CA,94546.0,13B,MISD - BATTERY ON PERSON,-122.081392,37.695585,2022/06/27 22:14:00+00
1,-1.359703e+07,4.533177e+06,2,502149,22010200,ACSO,1800 VIA AMIGOS,1828 VIA AMIGOS,SAN LORENZO,CA,94580.0,240,FEL - TAKE VEHICLE W/O OWNER CONSENT/VEHICLE T...,-122.144170,37.671883,2022/06/27 21:45:00+00
2,-1.359428e+07,4.537706e+06,3,502144,22010198,ACSO,1600 MONO AV,1612 MONO AV,SAN LEANDRO,CA,94578.0,999,72 HOUR MENTAL HEALTH,-122.119540,37.704077,2022/06/27 21:13:00+00
3,-1.359306e+07,4.535300e+06,4,502140,22010195,ACSO,600 HARMONY DR,636 HARMONY DR,HAYWARD,CA,94541.0,999,72 HOUR MENTAL HEALTH,-122.108579,37.686977,2022/06/27 20:20:00+00
4,-1.354524e+07,4.545353e+06,5,502138,22010193,ACSO,3900 DYER RD,3988 DYER RD,LIVERMORE,CA,94551.0,23H,GRAND THEFT - ALL OTHER,-121.678985,37.758408,2022/06/10 06:00:00+00

In [20]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(200571, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
0,-1.359004e+07,4.536511e+06,1,502150,22010202,ACSO,3000 CASTRO VALLEY BL,3088 CASTRO VALLEY BL,CASTRO VALLEY,CA,94546.0,13B,MISD - BATTERY ON PERSON,-122.081392,37.695585,2022/06/27 22:14:00+00
1,-1.359703e+07,4.533177e+06,2,502149,22010200,ACSO,1800 VIA AMIGOS,1828 VIA AMIGOS,SAN LORENZO,CA,94580.0,240,FEL - TAKE VEHICLE W/O OWNER CONSENT/VEHICLE T...,-122.144170,37.671883,2022/06/27 21:45:00+00
2,-1.359428e+07,4.537706e+06,3,502144,22010198,ACSO,1600 MONO AV,1612 MONO AV,SAN LEANDRO,CA,94578.0,999,72 HOUR MENTAL HEALTH,-122.119540,37.704077,2022/06/27 21:13:00+00
3,-1.359306e+07,4.535300e+06,4,502140,22010195,ACSO,600 HARMONY DR,636 HARMONY DR,HAYWARD,CA,94541.0,999,72 HOUR MENTAL HEALTH,-122.108579,37.686977,2022/06/27 20:20:00+00
4,-1.354524e+07,4.545353e+06,5,502138,22010193,ACSO,3900 DYER RD,3988 DYER RD,LIVERMORE,CA,94551.0,23H,GRAND THEFT - ALL OTHER,-121.678985,37.758408,2022/06/10 06:00:00+00

In [23]:
dfCrime['DateTime'] = pd.to_datetime(dfCrime['DateTime'])
dfCrime = dfCrime.loc[(dfCrime['DateTime'] >= '2018-01-01') & (dfCrime['DateTime'] < '2019-01-01')]
print(dfCrime.shape)
dfCrime.head()

(20090, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
4083,-1.359133e+07,4.534679e+06,4084,494205,22003964,ACSO,21400 OCEAN VIEW DRIVE,21439 OCEAN VIEW DRIVE,HAYWARD,CA,94541.0,999,INFORMATIONAL REPORT,-122.092971,37.682558,2018-01-15 09:31:00+00:00
5758,-1.359475e+07,4.538573e+06,5759,491508,22001880,ACSO,15000 FOOTHILL BL,15001 FOOTHILL BL,SAN LEANDRO,CA,94578.0,250,FORGERY,-122.123696,37.710244,2018-10-23 12:42:00+00:00
5807,-1.358292e+07,4.513331e+06,5808,491427,22001814,ACSO,6000 CAMPANULA CT,6036 CAMPANULA CT,NEWARK,CA,94560.0,999,INFORMATIONAL REPORT,-122.017433,37.530634,2018-01-01 00:01:00+00:00
10169,-1.359069e+07,4.535360e+06,10170,485269,21017309,ACSO,21400 BEDFORD DR,21400 BEDFORD DR,CASTRO VALLEY,CA,94546.0,999,INFORMATIONAL REPORT,-122.087286,37.687406,2018-12-18 13:15:00+00:00
16756,-1.358801e+07,4.534436e+06,16757,475672,21009838,ACSO,22800 VERMONT ST,22826 VERMONT ST,HAYWARD,CA,94541.0,13B,INFLICT CORPORAL INJURY ON SPOUSE/COHABITANT,-122.063213,37.680834,2018-03-29 00:01:00+00:00

In [29]:
list(dfCrime['CrimeCode'].unique())

['999',
 '250',
 '13B',
 '13C',
 '11D',
 '23H',
 '26C',
 '36B',
 '90H',
 '11A',
 '11B',
 '23A',
 '220',
 '36A',
 '11C',
 '23F',
 '90Z',
 '13A',
 'R24',
 '23D',
 '90F',
 '240',
 '26B',
 '23G',
 '290',
 '35B',
 '35A',
 '90D',
 '09A',
 '90C',
 '40B',
 '200',
 '520',
 '280',
 '90I',
 '23C',
 '120',
 '90J',
 '100',
 '90E',
 '40A',
 '90G',
 '370',
 '90B',
 '26A',
 '90A',
 '270',
 nan,
 '210',
 '39A']

In [33]:
dfCrime[dfCrime['CrimeCode'] == '13A']

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
53204,-1.358703e+07,4.537920e+06,53205,422027,19008767,ACSO,19600 CULL CANYON RD,19600 CULL CANYON RD,CASTRO VALLEY,CA,94552,13A,CRUELTY TO CHILD WITH POSSIBLE INJURY OR DEATH,-122.054342,37.705601,2018-11-11 00:01:00+00:00
54485,-1.359432e+07,4.537561e+06,54486,420062,19007206,ACSO,1500 MONO AV,1551 MONO AV,SAN LEANDRO,CA,94578,13A,EXHIBIT FIREARM,-122.119822,37.703046,2018-02-07 14:00:00+00:00
58059,-1.359456e+07,4.535262e+06,58060,414702,19002741,ACSO,0 E LEWELLING BL,50 E LEWELLING BL,SAN LORENZO,CA,94580,13A,EXHIBIT FIREARM,-122.122010,37.686707,2018-12-20 12:00:00+00:00
60200,-1.359164e+07,4.534570e+06,60201,411432,19000377,ACSO,21300 MISSION BL,21328 MISSION BL,HAYWARD,CA,94541,13A,ELDER/DEPENDENT ADULT CRUELTY,-122.095778,37.681786,2018-10-22 07:00:00+00:00
60527,-1.359251e+07,4.536665e+06,60528,410922,18023008,ACSO,16600 EHLE ST,16615 EHLE ST,SAN LEANDRO,CA,94578,13A,CRUELTY TO CHILD WITH POSSIBLE INJURY OR DEATH,-122.103589,37.696679,2018-12-31 19:29:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80412,-1.359361e+07,4.535904e+06,80413,382276,18000206,ACSO,1100 ELGIN ST,1127 ELGIN ST,SAN LORENZO,CA,94580.0,13A,FORCE OR ADW NOT FIREARM:GBI LIKELY,-122.113510,37.691274,2018-01-04 14:41:00+00:00
80576,-1.359484e+07,4.535886e+06,80577,382046,18000026,ACSO,600 EMPIRE ST,609 EMPIRE ST,SAN LORENZO,CA,94580.0,13A,CRUELTY TO CHILD WITH POSSIBLE INJURY OR DEATH,-122.124536,37.691146,2018-01-01 13:17:00+00:00
80593,-1.359518e+07,4.539002e+06,80594,382031,18000013,ACSO,2000 PLACER DR,2011 PLACER DR,SAN LEANDRO,CA,94578.0,13A,DISCHARGE FIREARM IN NEGLIGENT MANNER,-122.127553,37.713293,2018-01-01 08:48:00+00:00
80597,-1.359094e+07,4.533530e+06,80598,382019,18000008,ACSO,MEEKLAND AV/ SMALLEY AV,MEEKLAND AV/ SMALLEY AV,HAYWARD,CA,94541.0,13A,WILLFUL DISCHARGE FIREARM IN NEGLIGENT MANNER,-122.089451,37.674394,2018-01-01 03:36:00+00:00
80604,-1.359514e+07,4.538007e+06,80605,382013,18000006,ACSO,15000 ROBIN ST,15055 ROBIN ST,SAN LEANDRO,CA,94578.0,13A,DISCHARGE FIREARM IN NEGLIGENT MANNER,-122.127234,37.706217,2018-01-01 00:11:00+00:00

In [35]:
violentCrimes = ['13A', '09A', '120', '11A', '11B', '11C', '11D']
dfCrime = dfCrime[dfCrime['CrimeCode'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(766, 16)

,X,Y,OBJECTID,RecId,CrimeId,AgencyId,Block,Street,City,State,Zip,CrimeCode,CrimeDescription,Longitude,Latitude,DateTime
18538,-1.359381e+07,4.536801e+06,18539,472983,21007714,ACSO,1400 162ND AV,1456 162ND AV,SAN LEANDRO,CA,94578.0,11D,LEWD OR LASCIVIOUS ACTS W/CHILD UNDER 14 YEARS,-122.115283,37.697648,2018-01-01 17:44:00+00:00
19174,-1.359204e+07,4.537763e+06,19175,471979,21006928,ACSO,19000 STANTON AV,19041 STANTON AV,CASTRO VALLEY,CA,94546.0,11D,SEXUAL BATTERY -AGAINST VICTIM`S WILL FOR SEXU...,-122.099329,37.704484,2018-05-05 00:01:00+00:00
38165,-1.359371e+07,4.536470e+06,38166,444852,20004583,ACSO,16300 E 14TH ST,16385 E 14TH ST,SAN LEANDRO,CA,94578,11A,RAPE BY FORCE/FEAR/ETC,-122.114393,37.695292,2018-08-01 00:01:00+00:00
38166,-1.359371e+07,4.536470e+06,38167,444852,20004583,ACSO,16300 E 14TH ST,16385 E 14TH ST,SAN LEANDRO,CA,94578,11B,SODOMY,-122.114393,37.695292,2018-08-01 00:01:00+00:00
39365,-1.358795e+07,4.540013e+06,39366,442904,20003036,ACSO,5700 THOUSAND OAKS DR,5721 THOUSAND OAKS DR,CASTRO VALLEY,CA,94552,11D,SEXUAL BATTERY,-122.062594,37.720473,2018-12-31 15:28:00+00:00

In [37]:
dfCrime = dfCrime[['CrimeCode', 'Longitude', 'Latitude']]
dfCrime.head()

      CrimeCode   Longitude   Latitude
18538       11D -122.115283  37.697648
19174       11D -122.099329  37.704484
38165       11A -122.114393  37.695292
38166       11B -122.114393  37.695292
39365       11D -122.062594  37.720473

In [39]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['CrimeCode', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(766, 2)

      CrimeCode                           geometry
18538       11D  POINT (-122.11528291 37.69764786)
19174       11D   POINT (-122.09932879 37.7044838)
38165       11A  POINT (-122.11439341 37.69529229)
38166       11B  POINT (-122.11439341 37.69529229)
39365       11D    POINT (-122.06259429 37.720473)

In [41]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Downloads/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [43]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

      CrimeCode                geometry
18538       11D  POINT (-122.12 37.698)
19174       11D   POINT (-122.1 37.704)
38165       11A  POINT (-122.11 37.695)
38166       11B  POINT (-122.11 37.695)
39365       11D   POINT (-122.06 37.72)

In [45]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(766, 13)

,CrimeCode,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
18538,11D,POINT (-122.12 37.698),3385,06,001,433900,2,1500000US060014339002,060014339002,2,BG,138061,0
19174,11D,POINT (-122.1 37.704),13211,06,001,430600,3,1500000US060014306003,060014306003,3,BG,909364,0
38165,11A,POINT (-122.11 37.695),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
38166,11B,POINT (-122.11 37.695),13210,06,001,434000,3,1500000US060014340003,060014340003,3,BG,354540,0
39365,11D,POINT (-122.06 37.72),10960,06,001,430200,1,1500000US060014302001,060014302001,1,BG,3451080,0

In [47]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US060014340003    37
1500000US060014331021    27
1500000US060014358001    26
1500000US060014356011    23
1500000US060014328003    22
                         ..
1500000US060014328001     1
1500000US060014354003     1
1500000US060014325013     1
1500000US060014091002     1
1500000US060014054013     1
Name: count, Length: 120, dtype: int64

In [49]:
# export as a csv
crime.to_csv('Alameda_County_Violent_Crime_BG.csv')