In [73]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point
from shapely.wkt import loads

In [75]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Calls_for_Service_2021.csv')
print(dfCrime.shape)
dfCrime.head()

(428315, 21)

,NOPD_Item,Type,TypeText,Priority,InitialType,InitialTypeText,InitialPriority,MapX,MapY,TimeCreate,...,TimeArrive,TimeClosed,Disposition,DispositionText,SelfInitiated,Beat,BLOCK_ADDRESS,Zip,PoliceDistrict,Location
0,G3084321,24,MEDICAL,2D,34C,AGGRAVATED BATTERY BY CUTTING,2D,37369000,3513814,07/25/2021 06:12:16 AM,...,07/25/2021 06:15:21 AM,07/25/2021 09:15:02 AM,RTF,REPORT TO FOLLOW,N,8I01,007XX Canal St,70130.0,8,POINT (0 0)
1,H0004621,64J,CARJACKING,2C,64J,CARJACKING,2C,3679675,530274,08/01/2021 12:57:35 AM,...,08/01/2021 01:01:56 AM,08/01/2021 04:17:30 AM,UNF,UNFOUNDED,N,8I02,003XX O'Keefe Ave,70112.0,8,POINT (-90.07387558 29.95212763)
2,H1188521,103D,DOMESTIC DISTURBANCE,2C,103D,DOMESTIC DISTURBANCE,2C,37369000,3513814,08/10/2021 03:44:08 PM,...,NaN,08/10/2021 04:01:25 PM,RTF,REPORT TO FOLLOW,N,7I01,XX Marywood,NaN,0,POINT (0 0)
3,H2582621,65J,CARJACKING- NO WEAPON,2C,65,SIMPLE ROBBERY,1D,3727068,561263,08/21/2021 02:57:07 PM,...,08/21/2021 03:04:28 PM,08/21/2021 06:19:18 PM,RTF,REPORT TO FOLLOW,N,7L02,136XX Lourdes St,70129.0,7,POINT (-89.92302882 30.03581617)
4,H3395221,21,COMPLAINT OTHER,1J,67A,AUTO THEFT,1D,3691377,550019,08/28/2021 04:08:03 AM,...,08/28/2021 09:11:53 AM,08/28/2021 09:45:55 AM,RTF,REPORT TO FOLLOW,N,3U04,043XX Louisa Dr,70126.0,3,POINT (-90.03621945 30.00605965)

In [76]:
sorted(list(dfCrime['TypeText'].unique()))

['ABANDONED BOAT',
 'ABANDONED VEHICLE',
 'AGGRAVATED ARSON',
 'AGGRAVATED ASSAULT',
 'AGGRAVATED ASSAULT DOMESTIC',
 'AGGRAVATED BATTERY',
 'AGGRAVATED BATTERY BY CUTTING',
 'AGGRAVATED BATTERY BY SHOOTING',
 'AGGRAVATED BATTERY DOMESTIC',
 'AGGRAVATED BURGLARY',
 'AGGRAVATED BURGLARY DOMESTIC',
 'AGGRAVATED CRIMINAL DAMAGE',
 'AGGRAVATED ESCAPE',
 'AGGRAVATED KIDNAPPING',
 'AGGRAVATED RAPE',
 'AGGRAVATED RAPE MALE VICTIM',
 'AGGRAVATED RAPE UNFOUNDED BY SPECIAL VICTIMS OR CHILD ABUSE',
 'AIRPLANE CRASH',
 'AREA CHECK',
 'ARMED ROBBERY',
 'ARMED ROBBERY WITH GUN',
 'ARMED ROBBERY WITH KNIFE',
 'ASSET SEIZURE',
 'ATTACHMENT',
 'AUTO ACCIDENT',
 'AUTO ACCIDENT CITY VEHICLE',
 'AUTO ACCIDENT FATALITY',
 'AUTO ACCIDENT POLICE VEHICLE',
 'AUTO ACCIDENT WITH INJURY',
 'AUTO SMASH & GRAB',
 'AUTO THEFT',
 'BARRICADE ERECTED',
 'BICYCLE THEFT',
 'BLIGHTED PROPERTY',
 'BOMB SCARE',
 'BURGLAR ALARM, LOCAL',
 'BURGLAR ALARM, SILENT',
 'BURGLAR ALARM, SILENT, FAR NO RESPONSE',
 'BUSINESS BURGLARY',
 'BUSINESS CHECK',
 'CAD TEST',
 'CARJACKING',
 'CARJACKING- NO WEAPON',
 'COMPLAINT OTHER',
 'CONTRIBUTING TO DELINQUENCY',
 'CRIME AGAINST NATURE',
 'CRIMINAL DAMAGE DOMESTIC',
 'CRIMINAL MISCHIEF',
 'CRIMINAL MISCHIEF DOMESTIC',
 'CRUELTY TO ANIMALS',
 'CURFEW VIOLATION',
 'DEATH',
 'DESECRATION OF GRAVES',
 'DIRECTED PATROL',
 'DIRECTED TRAFFIC ENFORCEMENT',
 'DISCHARGING FIREARM',
 'DISPERSE SUBJECTS',
 'DISTURBANCE (OTHER)',
 'DOMESTIC DISTURBANCE',
 'DRIVING WHILE UNDER INFLUENCE',
 'DRUG VIOLATIONS',
 'DRUNK',
 'EMS UNIT NEEDS ASSISTANCE',
 'EXPLOSION',
 'EXTORTION (THREATS)',
 'EXTORTION (THREATS) DOMESTIC',
 'FIGHT',
 'FIRE',
 'FIREWORKS',
 'FLOOD EVENT',
 'FLOODED VEHICLE',
 'FORGERY',
 'FUGITIVE ATTACHMENT',
 'HIT & RUN',
 'HIT & RUN CITY VEHICLE',
 'HIT & RUN FATALITY',
 'HIT & RUN POLICE VEHICLE',
 'HIT & RUN WITH INJURIES',
 'HOLD UP ALARM',
 'HOMELESS',
 'HOMICIDE',
 'HOMICIDE BY CUTTING',
 'HOMICIDE BY SHOOTING',
 'HOMICIDE DOMESTIC',
 'HOSTAGE SITUATION',
 'ICING ON ROADS',
 'ILLEGAL CARRYING OF WEAPON',
 'ILLEGAL CARRYING OF WEAPON- GUN',
 'ILLEGAL CARRYING OF WEAPON- KNIFE',
 'IMPERSONATING AN OFFICER',
 'INCIDENT REQUESTED BY ANOTHER AGENCY',
 'INDECENT BEHAVIOR',
 'ISSUING WORTHLESS CHECKS',
 'JUVENILE ATTACHMENT',
 'LOST PROPERTY',
 'MEDICAL',
 'MEDICAL - NALOXONE',
 'MEDICAL SEXUAL ASSAULT KIT PROCESSING',
 'MEET AN OFFICER',
 'MENTAL PATIENT',
 'MISDEMEANOR SEXUAL BATTERY',
 'MISSING ADULT',
 'MISSING JUVENILE',
 'MUNICIPAL ATTACHMENT',
 'NEGLIENT INJURY',
 'NOISE COMPLAINT',
 'OBSCENITY, EXPOSING',
 'OFFICER NEEDS ASSISTANCE',
 'OFFICER NEEDS ASSISTANCE, LIFE IN DANGER',
 'PANDERING',
 'PARADE ITEM NUMBER',
 'PEEPING TOM',
 'PICKPOCKET',
 'POSSESSION OF STOLEN PROPERTY',
 'PROSTITUTION',
 'PROTEST',
 'PROWLER',
 'PUBLIC GATHERING',
 'QUALITY OF LIFE ISSUE',
 'RECKLESS DRIVING',
 'RECOVERY OF REPORTED STOLEN VEHICLE',
 'RECOVERY OF VEHICLE',
 'REFERRAL TO MHSD',
 'RESIDENCE BURGLARY',
 'RESIDENCE CHECK',
 'RETURN FOR ADDITIONAL INFO',
 'SEX OFFENDER REGISTRATION CHECK',
 'SEXTING',
 'SEXUAL BATTERY',
 'SHOPLIFTING',
 'SILENT 911 CALL',
 'SIMPLE ARSON',
 'SIMPLE ARSON DOMESTIC',
 'SIMPLE ASSAULT',
 'SIMPLE ASSAULT DOMESTIC',
 'SIMPLE BATTERY',
 'SIMPLE BATTERY DOMESTIC',
 'SIMPLE BURGLARY',
 'SIMPLE BURGLARY DOMESTIC',
 'SIMPLE BURGLARY VEHICLE',
 'SIMPLE CRIMINAL DAMAGE',
 'SIMPLE ESCAPE',
 'SIMPLE KIDNAPPING',
 'SIMPLE RAPE',
 'SIMPLE RAPE MALE VICTIM',
 'SIMPLE RAPE UNFOUNDED BY SPECIAL VICTIMS OR CHILD ABUSE',
 'SIMPLE ROBBERY',
 'SIMPLE ROBBERY, PROPERTY SNATCHING',
 'SIMULTANEOS STOLEN/RECOVERY VEHICLE',
 'SOLICITING FOR PROSTITUTION',
 'SUICIDE',
 'SUICIDE ATTEMPT',
 'SUICIDE THREAT',
 'SUSPICIOUS PACKAGE',
 'SUSPICIOUS PERSON',
 'THEFT',
 'THEFT BY EMBEZZLEMENT',
 'THEFT BY FRAUD',
 'THEFT FROM EXTERIOR OF VEHICLE',
 'TOW IMPOUNDED VEHICLE (PRIVATE)',
 'TRAFFIC ATTACHMENT',
 'TRAFFIC CONGESTION',
 'TRAFFIC INCIDENT',
 'TRAFFIC STOP',
 'TROOP N AREA - BUSINESS - RESIDENCE CHECK',
 'TRUANT VIOLATION',
 'UNAUTHORIZED USE OF VEHICLE',
 'UNCLASSIFIED DEATH',
 'UNDERPASS MONITORING OR CLOSURE',
 'VEHICLE NO-PURSUIT',
 'VEHICLE PURSUIT',
 'VIDEO VOYEURISM',
 'VIOLATION OF PROTECTION ORDER',
 'WALKING BEAT',
 'WARR STOP WITH RELEASE']

In [77]:
violentCrimes = ['AGGRAVATED ASSAULT', 'AGGRAVATED ASSAULT DOMESTIC', 'AGGRAVATED RAPE', 'AGGRAVATED RAPE MALE VICTIM', 
                 'AGGRAVATED RAPE UNFOUNDED BY SPECIAL VICTIMS OR CHILD ABUSE', 'ARMED ROBBERY', 'ARMED ROBBERY WITH GUN', 
                 'ARMED ROBBERY WITH KNIFE', 'HOMICIDE', 'HOMICIDE BY CUTTING', 'HOMICIDE BY SHOOTING', 'HOMICIDE DOMESTIC',
                'SIMPLE RAPE', 'SIMPLE RAPE MALE VICTIM', 'SIMPLE RAPE UNFOUNDED BY SPECIAL VICTIMS OR CHILD ABUSE']
dfCrime = dfCrime[dfCrime['TypeText'].isin(violentCrimes)]
print(dfCrime.shape)
dfCrime.head()

(3658, 21)

,NOPD_Item,Type,TypeText,Priority,InitialType,InitialTypeText,InitialPriority,MapX,MapY,TimeCreate,...,TimeArrive,TimeClosed,Disposition,DispositionText,SelfInitiated,Beat,BLOCK_ADDRESS,Zip,PoliceDistrict,Location
31,C0968521,37,AGGRAVATED ASSAULT,2E,62C,SIMPLE BURGLARY VEHICLE,1G,3670965,538400,03/08/2021 12:48:25 PM,...,03/08/2021 04:08:09 PM,03/08/2021 05:34:05 PM,RTF,REPORT TO FOLLOW,N,3D02,041XX Blk Canal St,70119.0,3,POINT (-90.1011 29.97473164)
83,I2542821,37,AGGRAVATED ASSAULT,2E,103F,FIGHT,2D,3670964,531606,09/22/2021 10:10:13 PM,...,09/22/2021 10:20:12 PM,09/23/2021 05:32:36 AM,RTF,REPORT TO FOLLOW,N,6N02,012XX S Salcedo St,70125.0,6,POINT (-90.10133625 29.95604998)
546,I2592121,37,AGGRAVATED ASSAULT,2E,21,COMPLAINT OTHER,1J,3664096,537522,09/23/2021 10:09:34 AM,...,09/23/2021 10:09:34 AM,09/23/2021 10:53:10 AM,RTF,REPORT TO FOLLOW,Y,3A01,Edinburgh St & Live Oak St,70118.0,3,POINT (-90.1228236 29.97251625)
569,I2594721,42,AGGRAVATED RAPE,1A,42,AGGRAVATED RAPE,2C,37369000,3513814,09/23/2021 10:37:23 AM,...,09/23/2021 01:53:25 PM,09/23/2021 03:08:33 PM,RTF,REPORT TO FOLLOW,N,6N02,X Drexel Dr,70125.0,6,POINT (0 0)
572,I2595021,37,AGGRAVATED ASSAULT,2E,37,AGGRAVATED ASSAULT,2E,3684411,538481,09/23/2021 10:38:24 AM,...,09/23/2021 10:46:30 AM,09/23/2021 11:15:29 AM,GOA,GONE ON ARRIVAL,N,5A04,N Derbigny St & Frenchmen St,70116.0,5,POINT (-90.05863099 29.97454758)

In [78]:
dfCrime = dfCrime[['TypeText', 'Location']]
dfCrime = dfCrime[dfCrime['Location'] != 'POINT (0 0)']
dfCrime.head()

               TypeText                          Location
31   AGGRAVATED ASSAULT      POINT (-90.1011 29.97473164)
83   AGGRAVATED ASSAULT  POINT (-90.10133625 29.95604998)
546  AGGRAVATED ASSAULT   POINT (-90.1228236 29.97251625)
572  AGGRAVATED ASSAULT  POINT (-90.05863099 29.97454758)
631  AGGRAVATED ASSAULT  POINT (-90.10701633 29.97936493)

In [83]:
dfCrime.dtypes

TypeText    object
Location    object
dtype: object

In [85]:
# Convert text column to geometry
dfCrime['geometry'] = dfCrime['Location'].apply(loads)

# Convert to GeoDataFrame
gdfPoints = gpd.GeoDataFrame(dfCrime, geometry='geometry', crs="EPSG:4269")

In [87]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("cb_2022_us_bg_500k/cb_2022_us_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(242297, 12)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER,geometry
0,04,019,940800,2,1500000US040199408002,040199408002,2,Block Group 2,BG,2033911373,68536,"POLYGON ((-112.41 31.857, -112.38 31.859, -112..."
1,04,003,000901,4,1500000US040030009014,040030009014,4,Block Group 4,BG,486316,0,"POLYGON ((-109.55 31.334, -109.55 31.339, -109..."
2,06,073,018102,3,1500000US060730181023,060730181023,3,Block Group 3,BG,324091,3579,"POLYGON ((-117.37 33.182, -117.37 33.182, -117..."
3,06,073,007200,3,1500000US060730072003,060730072003,3,Block Group 3,BG,720442,709604,"POLYGON ((-117.26 32.725, -117.26 32.726, -117..."
4,06,073,017702,3,1500000US060730177023,060730177023,3,Block Group 3,BG,317237,0,"POLYGON ((-117.3 33.052, -117.3 33.053, -117.3..."

In [89]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(2793, 15)

,TypeText,Location,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,NAMELSAD,LSAD,ALAND,AWATER
31,AGGRAVATED ASSAULT,POINT (-90.1011 29.97473164),POINT (-90.101 29.975),70966,22,071,006500,2,1500000US220710065002,220710065002,2,Block Group 2,BG,235153,0
83,AGGRAVATED ASSAULT,POINT (-90.10133625 29.95604998),POINT (-90.101 29.956),14974,22,071,007000,2,1500000US220710070002,220710070002,2,Block Group 2,BG,838818,0
546,AGGRAVATED ASSAULT,POINT (-90.1228236 29.97251625),POINT (-90.123 29.973),179309,22,071,007501,1,1500000US220710075011,220710075011,1,Block Group 1,BG,224016,0
572,AGGRAVATED ASSAULT,POINT (-90.05863099 29.97454758),POINT (-90.059 29.975),71307,22,071,002900,1,1500000US220710029001,220710029001,1,Block Group 1,BG,252258,0
631,AGGRAVATED ASSAULT,POINT (-90.10701633 29.97936493),POINT (-90.107 29.979),50281,22,071,005400,1,1500000US220710054001,220710054001,1,Block Group 1,BG,258824,0

In [91]:
crime = result['AFFGEOID'].value_counts()
crime

AFFGEOID
1500000US220710134003    61
1500000US220710017511    56
1500000US220710017204    44
1500000US220710071012    39
1500000US220710134002    35
                         ..
1500000US220710017011     1
1500000US220710123001     1
1500000US220710025022     1
1500000US220710127002     1
1500000US220710101001     1
Name: count, Length: 374, dtype: int64

In [95]:
# export as a csv
crime.to_csv('NO_Violent_Crime_BG.csv')